### ISSUE TITLE
Body margins

### ISSUE THREAD

**Issue by Phyxion** [cpriest/SnapLinksPlus#100]
If body margins are set then the dashed rectangle + selection rectangles aren't drawn at the correct position.

**Comment by cpriest** [comment]
I believe this may be fixed in the development version (not yet released).  I tested this with my own test page and seems to be no problem.  

Would you re-open this ticket if it still persists after the 3.0.3 release?

**Comment by Phyxion** [comment]
I just tried the latest commit and the problem still persists. Please check https://tweakers.net/ and see that everything's rendered incorrect.

**Comment by Phyxion** [comment]
This issue is not fixed @cpriest, now the AMO version is unusable 👎

**Comment by cpriest** [comment]
The latest master release should take care of this issue, could you confirm?

**Comment by cpriest** [comment]
I ended up using your method, I could not find a more automatic way, though the way I implemented it takes care of both (and all subsequent such issues) by containing all SnapLinks elements within its own adjusted container.

**Comment by Phyxion** [comment]
I'll check it out in a minute, thanks 👍

**Comment by Phyxion** [comment]
Works great now :) 
BTW, "strict_min_version": "45.0.0" isn't accepted in AMO (at least my AMO account doesn't like it).

**Comment by Phyxion** [comment]
Removed last post since it seems that was my own version still working. After a Firefox restart I noticed that nothing is opened anymore. For (most) sites the selection rectangles are shown but that's it.

**Comment by cpriest** [comment]
Yeah, that's because I'm making this available to chrome as well, there 
are some differences and prior I hadn't figured out how to make phing 
modify files in a way that would take care of that during the build.

**Comment by cpriest** [comment]
Right, in the 'developer' build, all actions are disabled.  If you look 
in background.es6 you can just comment out lines 34/35 and they'll work 
as usual.

Any line with // #DevCode is filtered out for a production build.

**Comment by cpriest** [comment]
Actually, just an update.  I just pushed a change to what I had posted above.  Now in globals.es6 you can just set Dev.Skip.AllActions to false and it will act upon elements as expected in production.

**Comment by Phyxion** [comment]
Thanks, I didn't know that but it's working now 👍

**Comment by Phyxion** [comment]
There are still some issues with the locations of the rectangles, e.g. here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1059272
The docs link has a rectangle beneath the link.

This is using the latest build. I also noticed that ESC doesn't seem to work anymore.

**Comment by cpriest** [comment]
Good catch, on both, I'll be sure to address both issues.  Thanks!

**Comment by Phyxion** [comment]
Thanks, can confirm that's OK now 👍

**Comment by cpriest** [comment]
Curious of your thoughts on the new website... wanted to get that out there, more specifically the welcome page for new users.  Just some basic "how does this work" introduction.  Thoughts?

http://cpriest.github.io/SnapLinksPlus/
http://cpriest.github.io/SnapLinksPlus/welcome.html

**Comment by Phyxion** [comment]
My thoughts on the welcome page:
- I don't think 'More information' should be collapsed (and nor should that header be visible). The description can be directly below. Something more along the lines of [this](http://i.imgur.com/X3Lfzgh.png). Although I would probably also explain there that it opens links without Control.
- Maybe the Greatest types / Greatest Font size can be combined in one section (with bullet points or something similar).

Rest looks fine to me 👍

**Comment by cpriest** [comment]
cool, thx
