### ISSUE TITLE
2 x Feature Requests (= flexibility boost)

### ISSUE THREAD

**Issue by baldsoprano** [cpriest/SnapLinksPlus#101]
(A) Apart from being able to trigger a single "default action" as you select the links, why not make Snap Links Plus be able to reach other actions as well by using custom modifier keys? (the  "Ask me what to do" dialog is not an option for me being a very slow solution). Please see my two Examples at the end. 

This would speed up my work very much in the case of SINGLE LINKS (too), because I will not have to leftclick and then select the action from a list any more.

(B) Also, wouldn't it be brilliant if SnapLinksPlus could reach ALL THE ACTIONS from the context menu of the links? (yes, I also have actions in my context menu which were created by OTHER addons, but I miss very much the "Open Links in New Private Window" action too, which is built into firefox).

THE ABOVE ENHANCEMENTS, IN MY OPINION, WOULD TURN SNAP LINKS PLUS FROM A VERY USEFUL ADDON INTO A TREMENDOUSLY USEFUL ONE.

Example1:
I would like to be able to open the selected links in a PRIVATE window if I hold down "Alt" while releasing the mouse button.

Example2:
I'd like to open the selected links in Chrome(browser) when I hold down "Ctrl + Alt" while releasing the mouse button. This would be executed via the  "Open With" addon, which does have a button/item in the context menu.

PS: I use your addon continuously. Very often I don't use ctrl+click on SINGLE links any more, because it's more convenient to select them with a single hand to open them in new tabs. Thank you for your work.

**Comment by cpriest** [comment]
Your welcome, there isn't any further development happening for the v2 line as v3 is under development.  Some of what you mention above is something I've wanted for SLP for quite some time.  The next v3 release will have a great addition of features from the current minimal release.

However it will be some time before anything will be 'customizable' per say.  v2 is set it up such that holding ctrl while releasing to popup the alternate action menu.  I would like v3 to be able to customize any combination of keys during release to select the action.  I'll take the above into account when I get to that part of the program.

**Comment by remi-garcia** [comment]
Closed in favor of #351
