### ISSUE TITLE
Version 3.0.0.2 cant configure Icon messed up

### ISSUE THREAD

**Issue by rayman89** [cpriest/SnapLinksPlus#102]
I installed the version 3.0.0.2 and I'm not able to change it's config and the icon for the extension shows an screenshot instead of the icon.

**Comment by cpriest** [comment]
Yeah, 3.0.0.2 is a minimal first release, it has no configuration 
options and only lasso's all <A> links.  The next version release will 
have considerably more functionality, but still no options UI, that will 
be in a forthcoming release.
