### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by NTsvetkov** [cpriest/SnapLinksPlus#104]
Hi,

I'm using SnapLinks 3.0.0.2 with firefox 48.0.2 64bit and multiprocess enabled.

Can't find where config option gone?

**Comment by cpriest** [comment]
At the moment there is no configuration options, the goal was to get the 
base functionality in place first before e10s hit release stage.

The next update will contain the bulk of the existing features from v2, 
sans configuration UI which will be next on the list.

**Comment by cpriest** [comment]
Unfortunately the config options are not going to be landing with the next release.  I'm still figuring out the new "Web Extensions" platform, as far as I know, there is not even a 'backdoor' way to expose the configuration options (which are presently hard-coded).  Working on the project though.
