### ISSUE TITLE
Addon ocassionally glitches context menu

### ISSUE THREAD

**Issue by hydreg** [cpriest/SnapLinksPlus#108]
On some pages addon creates a glitch that prevents context menu from appearing on right click. I have to reload the page to get it to work properly. It seems to happen randomly. I'm using version 3.0.0.2 on Firefox 49.0.1 and Windows 10, though it happens on Windows 7 as well (I had it happen on my Win7 PC at work). It was happening often enough for me to disable the addon, I'm not getting the glitch anymore.

**Comment by cpriest** [comment]
Thanks for the report, but this has already been reported and fixed in the next release.

**Comment by davidhedlund** [comment]
Can you please reference this issue with the duplicate bug. I'm interested in finding out.

**Comment by davidhedlund** [comment]
https://github.com/cpriest/SnapLinksPlus/issues/97
