### ISSUE TITLE
how to use...????

### ISSUE THREAD

**Issue by retardexpress** [cpriest/SnapLinksPlus#109]
i know is this isnt the right spot to post..

but i downloaded snap links
and i cant find any instructions anywhere on how to use it!

installed on several computers.. NOTHING happens..
dont know short cuts, menus or anything else

maybe a user guide, or getting started link would be helpful..?

thanks!

-SUPER FRUSTRATED

**Comment by Hrxn** [comment]
Right mouse click, keep button pressed, and drag...

**Comment by retardexpress** [comment]
Ok sounds good!  Is there a user guide or some instructions somewhere I missed on how to use the plugin?

**Comment by cpriest** [comment]
There isn't at the moment, never has been really.  I'll see about getting something put together about that.

**Comment by cpriest** [comment]
The new version has taken care of this issue via the welcome page.
