### ISSUE TITLE
Allow for ctrl-left btn drag

### ISSUE THREAD

**Issue by karloluiten** [cpriest/SnapLinksPlus#110]
I see all is being rewritten, awesome.

Problem for me is that I use gestures with my right mouse button. SnapLinks used to give me the option to use an other combo for drawing 'boxes'.

Can that come back? Thanks a lot!

**Comment by cpriest** [comment]
This functionality will definitely be back once the GUI options work has begun (after the coming release).  The focus for this next release has been getting as much of the original 'default' functionality back with the re-write.  Ergo, customization at this point is not possible but that is in the coming future.
