### ISSUE TITLE
Feature Request: Optional Delay For Opening Each New Tab

### ISSUE THREAD

**Issue by rlgurney** [cpriest/SnapLinksPlus#114]
First of all, I love your add-on!  Would it be possible to add a feature that gives the option of adding a slight delay between each new tab opened via SnapLinks?  One of the sites I frequent gives 503 errors if too many links are opened at once, leading me to open them ~5 at a time vs. an entire page.  If the request to load the tab could be delayed somehow, preventing a mass request, that would be great.

Thanks!

**Comment by cpriest** [comment]
Sure, I'll put the feature in, it was in v2 (though not configurable).  I would like to be able to have per site customization options in the future.  This will make the most sense to be added when I have at least a minimal options GUI setup, expect that in v3.2.0

**Comment by NavyRet** [comment]
Any word on when this might me implemented?

**Comment by cpriest** [comment]
This should be pretty easy to implement in the next release.  I'm going to mark it the next non-beta release as that one will be focused on "issues" rather than enhancements.

**Comment by romanmd86** [comment]
+1 vote for this feature. I consider it essential for SnapLinksPlus, as users use this addon to open multiple links at once, like 10-20-50 etc., not 2-3 links. And opening multiple links at once gets you instant IP ban on some sites for 1 hour, on other sites - HTTP 503, or captchas.

**Comment by romanmd86** [comment]
To solve this issue I am using SnapLinksPlus with 'Load Background Tabs Lazily' add-on or 'Load Tabs Progressively Fixed' (FF56).

**Comment by dgramstorff** [comment]
Perfect, thanks for the tip!

**Comment by cpriest** [comment]
I hope to be able to work on this project again starting middle of next week and knock out a bunch of these small feature requests.

**Comment by dgramstorff** [comment]
Great!  I will stay tuned.  It's an excellent addon as is.  Firefox with
Snap Links is performing better for me than Chrome and Linkclump.

**Comment by cpriest** [comment]
Snap Links is available for Chrome as well, was part of the reason for 
the rewrite.

**Comment by NavyRet** [comment]
OK. I give up. I see 3.2 up there, but no way to get it. Am I crazy or what?

**Comment by cpriest** [comment]
Not sure where you're seeing v3.2 available?  3.1.2.4  is the latest release

**Comment by EinGauner** [comment]
Hi,

Is this still going to be a thing and how long do you expect development to take before it's released?

**Comment by cpriest** [comment]
This project isn't a priority for me at the moment, but I'm open to contributions.

**Comment by cpriest** [comment]
Yep, working on this ticket this morning.

**Comment by cpriest** [comment]
This feature is added in f0dbf44 and should be out with the next 3.1.6 release.
