### ISSUE TITLE
Can't use copy to clipboard anymore (open new links instead)

### ISSUE THREAD

**Issue by Flekain** [cpriest/SnapLinksPlus#116]
Hi,

Up until now selected link with right click were copied to my clipboard (the behavior that I wanted) but now they are opened in new tabs. I tried to find an option to change the default behavior but I couldn't find anything.

Is it a bug or is just me not finding where to change the settings ?

Thank you,

**Comment by Hrxn** [comment]
Not implemented yet, maybe try version 2.x

**Comment by cpriest** [comment]
The next version release will have this feature, you'll need to hold down ctrl to have it copy links to the clipboard.  Next release is due out soon, possibly this week.
