### ISSUE TITLE
Inoperative with Wikipedia timeline links

### ISSUE THREAD

**Issue by Keith94** [cpriest/SnapLinksPlus#118]
For example here:
https://en.wikipedia.org/wiki/James_Bond_in_video_games#History

The links in the timeline listed on the right side can't be selected with Snap Links Plus.

**Comment by cpriest** [comment]
Looks like they are using <area> tags rather than anchor links, should be easy to get into 3.1 before the release.

**Comment by cpriest** [comment]
Hmm, looks like AREA rects don't follow logical standards.  Won't be as trivial but I'll see what I can do.

**Comment by Keith94** [comment]
Thanks, any ETA for next release?

**Comment by cpriest** [comment]
I hate to make any promise as I've already said twice I would have it 
released "this week," I just have to leave it as "as soon as I can."

**Comment by Keith94** [comment]
I can't reproduce this issue anymore with the above link.
