### ISSUE TITLE
Still doesn't work on FF 49.0.2 (Mac-Yosemite)

### ISSUE THREAD

**Issue by ghilliedancer** [cpriest/SnapLinksPlus#120]
FF updated automatically and suddenly Snap Links didn't work anymore. I downloaded it again and it doesn't work. It doesn't even show as being able to work. The image isn't there and Preferences aren't there, only Disable are Remove. I've tried redoing it several times. I can't find any information on how to make it work. I went back to FF 48.something, and now Snap Links says it isn't available for FF 48! Please, please make it work with FF 49 or put the old one back up for FF 48 until the new one works. Multi-LInks is slow, won't grab links when images are turned off, and doesn't do checkboxes. I've included a screenshot of how Snap Links appears in my Add-Ons:

![screen shot 2016-10-28 at 11 48 50 pm](https://cloud.githubusercontent.com/assets/23133564/19827767/36f563ea-9d69-11e6-8a54-e6dbaa2c2b05.png)

**Comment by cpriest** [comment]
The new 3.1 version is due to be released soon, you can try the beta version by downloading https://github.com/cpriest/SnapLinksPlus/raw/master/dist/SnapLinks-3.1.0b1.xpi.  You'll need to go to about:debug and click "Load Temporary Extension" to use this unsigned version.

**Comment by cpriest** [comment]
Note, there is also a welcome page with instructions on use of 3.1 available here:
http://cpriest.github.io/SnapLinksPlus/welcome.html
