### ISSUE TITLE
Right-clicking some links causes page to jump

### ISSUE THREAD

**Issue by Keith94** [cpriest/SnapLinksPlus#122]
On this page: http://3dsurroundgaming.com/img/Plugins/Archive/

Simply right-clicking any links makes the page content shift down and up on every right-click.

EDIT: Seems like right-clicking anywhere on the page causes the issue.

**Comment by Phyxion** [comment]
Can confirm.

**Comment by Keith94** [comment]
Thanks man. :) Any idea what's causing it?

**Comment by Keith94** [comment]
Same right-click issue here: https://raw.githubusercontent.com/cpriest/SnapLinksPlus/master/README.md
