### ISSUE TITLE
Tree Style Tab support no longer working

### ISSUE THREAD

**Issue by Keith94** [cpriest/SnapLinksPlus#123]
Clint, previously you had added support for [Tree Style Tab](https://addons.mozilla.org/addon/tree-style-tab/) (see #30).

However, I think it's no longer supported in version 3.0.0.2 (still works in version 2.4.3).

Is it possible to re-implement the fix in the next version? Thanks!

**Comment by cpriest** [comment]
Wow I've no idea what I did for that but I'll look into it.  Won't be in the next release as a lot of people are waiting on it, but could put it out as a minor version update after this gets out the door.

Is Tree Style Tab being maintained?

**Comment by Keith94** [comment]
>Is Tree Style Tab being maintained?

Yes, it still receives regular updates.

**Comment by cpriest** [comment]
Hmm, it doesn't look like is going to be working for much longer when XUL style add-ons are phased out...  I'm actually not sure that I can work with it, but I'll see what I can do.

**Comment by Keith94** [comment]
This also doesn't support a similar add-on called Tab Tree, maybe something can be done.

See traxium/tabtree/pull/146.

**Comment by Keith94** [comment]
Migration to WebExtensions is now planned for Tree Style Tab (piroor/treestyletab#1224).

**Comment by cpriest** [comment]
Good to know, I'll see about getting this put in place sometime soon.

**Comment by cpriest** [comment]
Good to know, I'll see about getting this put in place sometime soon.

**Comment by Keith94** [comment]
Update: Tree Style Tab is now a [WebExtension](https://addons.mozilla.org/firefox/addon/tree-style-tab/). It provides [API for other addons](https://github.com/piroor/treestyletab/wiki/API-for-other-addons) which should be useful.
