### ISSUE TITLE
Latest beta doesn't work in Firefox 49.0.2 in Ubuntu 16.04

### ISSUE THREAD

**Issue by sfinam** [cpriest/SnapLinksPlus#124]
Addon installs 
The welcome page is shown
Green rectangle appears as expected
Nothing gets opened or checked even if it is highlighted by the rectangle and has an outline

**Comment by cpriest** [comment]
Hmm, on that #3, what steps are you doing exactly that cause the issue?

**Comment by sfinam** [comment]
Last 4 strings if I filter by JS only

```
ReferenceError: ActionHandler is not defined[Learn More]SnapLinks.es6:196:7
Key event not available on some keyboard layouts: key=“c” modifiers=“accel,alt”browser.xul
Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift”browser.xul
ReferenceError: ActionHandler is not defined[Learn More]SnapLinks.es6:196:7
```

**Comment by sfinam** [comment]
Sorry, closed by mistake

**Comment by cpriest** [comment]
Hmm, can you see if any errors are showing up in the browser error 
console?  Ctrl+shift+J by default...

**Comment by cpriest** [comment]
Sorry, was having a mail problem and it just went through.

**Comment by cpriest** [comment]
Are you running the development version or the packaged b2.xpi?

**Comment by sfinam** [comment]
The packaged xpi from this repo

**Comment by sfinam** [comment]
Also, just to add some  context - the version from the market that was there 5 days ago (haven't checked if it was updated since then)  opened links without any issues (checkboxes didn't work though, not sure if that was expected), so this is a regression for me.

**Comment by FatOrangutan** [comment]
I'm having the exact same problem, on FF v51.0a2.

**Comment by cpriest** [comment]
Sorry for the long delay, found the problem.  The latest b3 available in the dist folder (b3) should work fine.  I've installed the XPI and tested a few of the sites that were problematic before.  Give that a try, here is a link to the download: [SnapLinks-3.1.0b3.xpi](https://github.com/cpriest/SnapLinksPlus/raw/master/dist/SnapLinks-3.1.0b3.xpi)

If you're still having any issue, please re-open this ticket.  I'll probably be releasing this today/tomorrow sometime.

**Comment by FatOrangutan** [comment]
b3 works perfectly for me. Thanks!
