### ISSUE TITLE
Some Warnings

### ISSUE THREAD

**Issue by shawnhcorey** [cpriest/SnapLinksPlus#125]
Two warnings are issued:

`1478692887464	addons.webextension.snaplinks@snaplinks.mozdev.org	WARN	Loading extension 'snaplinks@snaplinks.mozdev.org': Reading manifest: Error processing author: An unexpected property was found in the WebExtension manifest.
`

`1478692887465	addons.webextension.snaplinks@snaplinks.mozdev.org	WARN	Loading extension 'snaplinks@snaplinks.mozdev.org': Reading manifest: Error processing minimum_chrome_version: An unexpected property was found in the WebExtension manifest.
`

---

Firefox 49.0.2

Linux Mint 17.3

`Linux 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by cpriest** [comment]
Thanks, those aren't a big concern but the latest beta version should have that fixed if you want to try it out.  It should be released in the next day or two: [SnapLinks-3.1.0b3.xpi](https://github.com/cpriest/SnapLinksPlus/raw/master/dist/SnapLinks-3.1.0b3.xpi)
