### ISSUE TITLE
Not working on AMO

### ISSUE THREAD

**Issue by FatOrangutan** [cpriest/SnapLinksPlus#126]
Nothing happens while I'm dragging with the right mouse button pressed, and when I let go, the normal context menu pops up.

Tested links: https://addons.mozilla.org/en-US/firefox/, https://addons.mozilla.org/en-US/firefox/addon/snaplinksplus/ etc. I think it is not working on any part of any page on that site, while it does work as expected on others.

I tested with a fresh profile on FF v50, Snap Links v3.1.0.4 from AMO.

**Comment by Keith94** [comment]
This is because Firefox 50 is blocking execution of these kinds of extensions on pages where it could harm the user, so it won't work on that domain (https://addons.mozilla.org/).

**Comment by cpriest** [comment]
That is rather interesting, I am seeing in the browser error log on that site "Content Security Policy: The page's settings blocked the loading of a resource.  Looks like a lot of this is happening on that page w/ more than just SnapLinks...  I'll ask someone about that.

**Comment by cpriest** [comment]
Looks like it's fairly common issue at the moment, nothing I can do about this for the time being.

https://bugzilla.mozilla.org/show_bug.cgi?id=1310082
