### ISSUE TITLE
Please remove making newly opened tabs active

### ISSUE THREAD

**Issue by No1sonuk** [cpriest/SnapLinksPlus#128]
Please remove the "feature" of making the first newly-opened tab active.  It's annoying in that I regularly open multiple new tabs from a list, and switching the focus to a new tab makes it harder to keep track.

The older versions never did this, so why change it now?
Alternatively, reinstate the options menu (a good idea anyway), and make it optional.

**Comment by cpriest** [comment]
This will be an option when the options panel portion is written.  The addon now works as the v2 "default options" did.  But this will be configurable when the next release comes out.

**Comment by FatOrangutan** [comment]
Until then, if you would like, you can replace the following line in the file \src\background-scripts\background.es6:

    active: (--TabsLeft) == 0,	// Activate the last tab to be opened

with

    active: false,	// Don't activate any of the tabs opened

You will have to sign the add-on again.

**Comment by Keith94** [comment]
@FatOrangutan That works, thanks!

**Comment by No1sonuk** [comment]
@cpriest Thanks.  Any idea how long that'll be?

@FatOrangutan How do I do that?

**Comment by thaliel** [comment]
where do I find that file in order to change it?

**Comment by FatOrangutan** [comment]
@No1sonuk, @thaliel Do the following:

1) Right click this link and click save as and save to a folder of your choice -> https://addons.mozilla.org/firefox/downloads/latest/snaplinksplus/addon-332432-latest.xpi?src=search
2) Open / extract the downloaded file with your compression utility of choice - WinRAR, WinZip and even Window's built-in zip extraction feature would work, since .xpi files are essentially .zip files.
3) Inside, go to the `src` folder, go to the `background-scripts` folder, and open the `background.es6` file with a text editor of your choice.
4) Change the line as per my previous comment, save and repackage the whole thing as a .xpi.

I have uploaded an unsigned add-on with the above change (being the only change I made) [here](https://ufile.io/d0716).

**Comment by Hjalmberi** [comment]
@FatOrangutan thank you for helping out so fast! Tried to install the unsigned add-on from the link above (check for add-ons being signed turned off), got an error - add-on can't be installed because it appears to be corrupt

**Comment by FatOrangutan** [comment]
@Hjalmberi I just checked again and I am able to install it fine and it works as expected.

Can you confirm that you are on the Developer Edition, Nightly or Unbranded Build and have `xpinstall.signatures.required;false` in about:config? Stable won't install unbranded builds (it will call them corrupted) even if you have `xpinstall.signatures.required;false` - that pref does nothing on Stable and Beta.

You can also try signing that add-on yourself, based on instructions [here](https://wiki.mozilla.org/Add-ons/Extension_Signing).

**Comment by Hjalmberi** [comment]
@FatOrangutan, thank you, updating to Nightly worked like a charm

**Comment by zededd** [comment]
@FatOrangutan thank you for the help... sadly, I'm not getting anywhere with authorising the addon myself (it lost me at JWT... uneducated in programming) and would rather not have to install a different firefox for one addon...
I'll have another go when I'm back off holiday. Thanks again for the tutorial

**Comment by No1sonuk** [comment]
@FatOrangutan Thanks.  I've used your xpi with Nightly.

**Comment by levantou** [comment]
I couldn't get that fix to work in the regular version, but it works great in Nightly. Thank you.

**Comment by cpriest** [comment]
The latest beta release has been published here: https://github.com/cpriest/SnapLinksPlus/releases/tag/v3.1.1b1

This is, as of yet, an unsigned version so you may not be able to install without a few hoops.  I'm hoping to have the signature situation figured out soon (mozilla would not sign without putting it on addons.mozilla.org which I don't want as it's a beta version).
