### ISSUE TITLE
Scrolling/middle button and Snaplinks

### ISSUE THREAD

**Issue by bluebellrose** [cpriest/SnapLinksPlus#129]
scrolling doesn't seem to work with snaplinks. Or if it does it's very slow. I use it for yarolds and rely on it being able to scroll to get everything in one go.  It's also very slow when I open a lot of links. I usually open 250 at a time using snaplinks. It lags a bit. Previously before the update it didn't do that.
I wonder if it has anything to do with the multi process thingy.

**Comment by cpriest** [comment]
Well, opening 250 links is pretty intensive.  I've never had a situation where I've told a browser to open that many links and expected it to do it without lag.  If you can post a link where you're seeing the problem with the mouse wheel I can give it a test.  

Are you scrolling with your mouse wheel or by dragging outside of the window?

**Comment by bluebellrose** [comment]
I'm scrolling with the middle mouse button and occasionally with the down arrow key on the keyboard. it never used to lag with the previous version. I even tried disabling flashblock and changed the shockwave plugin to ask to activate to see if that helped. helped a bit with the lag but still lags a bit before opening the tabs. The previous version 2.4.3 doesn't do that to me. Links open right away.  The newest version seems to take a few seconds before the links start opening in new tabs. 
I use snaplinks primary on this site https://swle.yarold.eu/main.php

**Comment by cpriest** [comment]
I can look into this at some point, but this is a rather extreme edge case, so I can't promise when I can look into it or even if I will be able to do anything about it.  < 250 links at one time crushes my main firefox instance and always has (though I have around 30 add-ons installed)

**Comment by bluebellrose** [comment]
I don't seem to be the only one havng this issue though. I have flashblock or flash set to ask to activate and adblock, so opening 250 links is no biggie for me.

**Comment by remi-garcia** [comment]
I can't reproduce this issue. No lag while dragging over hundreds of links and scrolling (sometimes about 600 to 900, not opening them though).
I think this can be closed

**Comment by cpriest** [comment]
The performance was enhanced greatly with the last release, it's not likely an issue anymore.  Please comment if it still presents a problem.
