### ISSUE TITLE
Download action doesn't appear to work

### ISSUE THREAD

**Issue by yourealwaysbe** [cpriest/SnapLinksPlus#13]
I have Firefox 23.0.1 and Snaplinks 2.3.4b2 running on Arch Linux with the XMonad window manager.  When i set the default action to "Download" and select, nothing happens.  It works fine opening the links in new tabs.

**Comment by remi-garcia** [comment]
Duplicate of #33 since this is not a bug anymore but a new feature to add
Should be closed
