### ISSUE TITLE
Switching to opened tabs immediately

### ISSUE THREAD

**Issue by RandoLando** [cpriest/SnapLinksPlus#133]
It seems that the latest update will automatically switch to which ever tabs you've opened, rather than allow them to be opened in the background like previous versions.

Can this option be offered in a/the future update?

**Comment by Detruire** [comment]
This has already been reported, see #128, #130, and #132.

**Comment by cpriest** [comment]
The latest beta release has been published here: https://github.com/cpriest/SnapLinksPlus/releases/tag/v3.1.1b1

This is, as of yet, an unsigned version so you may not be able to install without a few hoops.  I'm hoping to have the signature situation figured out soon (mozilla would not sign without putting it on addons.mozilla.org which I don't want as it's a beta version).
