### ISSUE TITLE
Snap Links Plus Issue

### ISSUE THREAD

**Issue by joshnprange** [cpriest/SnapLinksPlus#135]
I've been using Snap Links for about a year without fault. This morning it is not working for me and a few others that also use the tool. When we click and drag with right click, it opens the green rectangle to grab hyper links, but it does not open the links. The green rectangle remains on the page and only goes away when you try it again.

**Comment by cpriest** [comment]
Please post what version of the add-on you are using and the page(s) you are experiencing this on, can't tell you much without seeing the problem.

**Comment by joshnprange** [comment]
https://addons.mozilla.org/en-US/firefox/addon/snaplinksplus/

This is the page that we all access snap links from and we are all having the same issue. The tool did not used to work with check boxes, but it did with links. Now its the opposite.

**Comment by joshnprange** [comment]
Error is happening on all pages that we try to open links from using snap links.

**Comment by joshnprange** [comment]
http://cpriest.github.io/SnapLinksPlus/welcome.html

This page also opened when we launched Firefox today and we wondered if it is under development on the next version, that may be the reason it is acting up.

**Comment by joshnprange** [comment]
![snap links issue](https://cloud.githubusercontent.com/assets/23615663/20464359/f14831e4-af13-11e6-8e34-54b07bef4536.PNG)

![snap links page issue](https://cloud.githubusercontent.com/assets/23615663/20464360/f26f355e-af13-11e6-8638-156a855dfcd1.PNG)

**Comment by cpriest** [comment]
Ok, the add-on won't work on addons.mozilla.org because of their Content Security Policy, elsewhere however though it should be working.  

In your first image, that little square in the upper right tells me that some error is being generated.  If you could refresh the page where the trouble is occurring (F5), then open up the browser console (Ctrl + Shift + J) and hit the delete button (upper left), then try to use SnapLinks and post whatever errors are showing in the browser console here.

Also, what version of FireFox are you using?  Lastly have you tried restarting firefox?  While this shouldn't be necessary, perhaps something is gunked up.  3.1.0.4 has been released a few days now and nobody has had any problems (except for the CSP issue on addons.mozilla.org)

**Comment by joshnprange** [comment]
![browser control](https://cloud.githubusercontent.com/assets/23615663/20481899/96b28bc2-afb7-11e6-9574-2da3c23fad68.PNG)

**Comment by joshnprange** [comment]
![firefox](https://cloud.githubusercontent.com/assets/23615663/20500231/9fc7b624-b002-11e6-8efa-6c33ba43adba.PNG)

**Comment by joshnprange** [comment]
Firefox has been restarted along with computer multiple times in an attempt to fix.

**Comment by cpriest** [comment]
Apparently it's not compatible with FF 45.5 any longer.  I'll be updating the minimum version to FF 50 with the next release, but you'll need to update your FF to a more current version for it to work apparently.  It may work in FF 46/47/48/49 as well, not sure offhand.

**Comment by joshnprange** [comment]
Alright when is the next release expected to go live? We work for a large company that does not have the most responsive IT team so we will have to ask about updating FF.

**Comment by cpriest** [comment]
I see, well I'm hoping to have a beta version (signed) this morning or this afternoon.  You might just try to go to Help -> About Firefox and have it auto-update, unless your IT dept has your computers heavily locked down.

**Comment by cpriest** [comment]
The latest beta release has been published here: https://github.com/cpriest/SnapLinksPlus/releases/tag/v3.1.1b1

This is, as of yet, an unsigned version so you may not be able to install without a few hoops.  I'm hoping to have the signature situation figured out soon.

**Comment by joshnprange** [comment]
Just had our IT team update my Firefox to version 50.0.2 and Snap Links is up and running again. Thanks for the help!
