### ISSUE TITLE
Remove activating newly opened tab from v3.1.0.4

### ISSUE THREAD

**Issue by kostek00** [cpriest/SnapLinksPlus#137]
"The first tab by document order opened will also become active"
This option is bad. Why? I want to open many pages from one site but can't open them all at once. Because of this change now I will have to keep rotating between pages to open them all which is annoying as hell.

Don't force users with such options. Or make configurations where users can decide how plugin should behave.

**Comment by cpriest** [comment]
Please see numerous other tickets, such as #134.
