### ISSUE TITLE
Not Compatible with FF 45+

### ISSUE THREAD

**Issue by catdel** [cpriest/SnapLinksPlus#139]
I origionally Accessed SnapLinksPlus from the following link;
https://addons.mozilla.org/en-US/firefox/addon/snaplinksplus/

the above link says that SLP is compatible with Firefox 45+ which is not true.

The reason I have advised the above is becasue I have attempted to use the addon in Firefox 45.5.0 and the addon installs but does not respond to commands, I have received a reply in the follwing thread to confirm this;
https://github.com/cpriest/SnapLinksPlus/issues/127#issuecomment-261378016

Due to the above informaiton I recommend that the Firefox landing page for the addon be edited or alternatively the addon be fixed to be compatible with Firefox 45.5.0

**Comment by cpriest** [comment]
The latest beta release has been published here: https://github.com/cpriest/SnapLinksPlus/releases/tag/v3.1.1b1

This is, as of yet, an unsigned version so you may not be able to install, but this also has a minimum version of FF 50 for use.
