### ISSUE TITLE
Buggy with rutracker search results

### ISSUE THREAD

**Issue by Keith94** [cpriest/SnapLinksPlus#142]
Steps to reproduce:

1. Go to https://rutracker.org/forum/index.php
2. Type something in the search bar and hit enter
3. Try to select the search result links with SLP

Result: Nothing gets selected and the context menu opens when releasing right mouse button

**Comment by cpriest** [comment]
To my knowledge, there is nothing I can do about this.  The results are loaded into an IFRAME which is not populated with the SnapLinks script code.  The last I recall about an IFRAME was that it was a security border which cannot be traversed, even by the owning page.  I'll leave it open until that can be confirmed though.

**Comment by Keith94** [comment]
Well FYI [Multi Links Plus](https://github.com/Smile4ever/firefoxaddons/tree/master/Multi%20Links%20Plus) implementation doesn't have this bug, so there must be a better way..

**Comment by cpriest** [comment]
That's a XUL based add-on and will no longer work in the future without being re-written.

**Comment by remi-garcia** [comment]
This works now. Can be closed.

**Comment by cpriest** [comment]
Thank you @remi-garcia for the triage/going through the tickets.  I'll go ahead and close those you mentioned.
