### ISSUE TITLE
How to Configure?

### ISSUE THREAD

**Issue by wackybadger** [cpriest/SnapLinksPlus#147]
Generally speaking, the Snap Links Plus seems buggier than it used to be, but my current problem is that I cannot figure out how to change the options.  I recently had to reset Firefox and reinstall my add-on's.  There is no Options button for Snap Links in the Add-on's page and holding down Alt or another key while right-clicking does not bring up a context menu as it did before.

**Comment by thaliel** [comment]
A newer version with basic config options should come out soon. In the meantime, you can use 2.4 by installing it from the version history

**Comment by cpriest** [comment]
The latest version (waiting review from Mozilla) has a few options in it, but not as many as v2 does.
