### ISSUE TITLE
Buggy with standalone images

### ISSUE THREAD

**Issue by Keith94** [cpriest/SnapLinksPlus#148]
Steps to reproduce:

1. Go to https://z0x.us/pb934
2. Left-click the top of the image to view it full size
3. Right-click anywhere on the image

Results:
Page scrolls down every time right-click is pressed

**Comment by cpriest** [comment]
Thanks for the report, I see the problem and I'll get a fix for it.

**Comment by remi-garcia** [comment]
Cannot reproduce. Please reopen if you still have this issue.
