### ISSUE TITLE
Allow Space key to scroll the page while dragging

### ISSUE THREAD

**Issue by yfdyh000** [cpriest/SnapLinksPlus#152]
I remember it works in 2.x on Firefox.

**Comment by cpriest** [comment]
I can see the code that would be causing it, I've no idea why I would have put that there.  It's blocking all keys while a drag event is going on.  I'll have it with out with the next beta release.  I'm rather surprised that the current 'release' version is still waiting in queue, it's been almost 3 weeks now.

**Comment by cpriest** [comment]
I tested this with the latest build and it seems to be working fine.  Please re-open if you still see an issue.  *should* be releasing a new beta version for Firefox/Chrome very soon.

**Comment by cpriest** [comment]
Just thought I'd post that the FireFox beta has been released and is ready for updating, see https://github.com/cpriest/SnapLinksPlus.
