### ISSUE TITLE
When not all links are in same format...

### ISSUE THREAD

**Issue by REHVC** [cpriest/SnapLinksPlus#154]
When not all the links on a page are in the same format (some are normal text, some are underlined, some are bold) SnapLinks only selects the ones with formatting (underlined/bold), but not the ones that are in normal text.
When seperately selecting the ones with normal text (on the exact same page), SnapLinks does selects them.

Hopefully you have an idea what's causing this and can fix it.

Thanks!

**Comment by cpriest** [comment]
This is a feature, please see the welcome page

**Comment by cpriest** [comment]
This is a feature, please see the [welcome page](http://cpriest.github.io/SnapLinksPlus/welcome.html) for more information on usage.
