### ISSUE TITLE
Add option to disable/inverse link filtering

### ISSUE THREAD

**Issue by Keith94** [cpriest/SnapLinksPlus#158]
The links on this page look like the same size, but can't all be selected simultaneously: http://classicgamefixes.wixsite.com/home/game-list

For example:
![firefox_2016-12-24_00-15-41](https://cloud.githubusercontent.com/assets/5490615/21466021/22b7d17a-c96e-11e6-9c3e-251f18f98570.png)

**Comment by FatOrangutan** [comment]
They do *look* the same, but if you use Inspect Element, you will see that some of those elements have `font-weight: bold` while others don't:
![capture](https://cloud.githubusercontent.com/assets/8336638/21467868/ac0c7ce2-ca21-11e6-9485-acd15abfc844.PNG)

**Comment by Keith94** [comment]
Oh, looks like I can hold `Alt` to select all links at once.

@cpriest Will there eventually be an option to always select all links by default?

**Comment by cpriest** [comment]
This is actually a feature of the add-on since before I took it over, as 
was the 'hold down a key to bypass.'

An option could be put in to disable or inverse this functionality if 
desired.

**Comment by Keith94** [comment]
>An option could be put in to disable or inverse this functionality if desired.

Yes please!

**Comment by cpriest** [comment]
About to add this feature:

![image](https://user-images.githubusercontent.com/159323/37561197-aa20bbd6-2a16-11e8-906b-16ad16752a9a.png)

**Comment by cpriest** [comment]
Will be available in next beta release.
