### ISSUE TITLE
not selecting checkboxes

### ISSUE THREAD

**Issue by Honei01** [cpriest/SnapLinksPlus#159]
Hey i have an issue withe the tool when i want to check multiple checkboxes in an online browser game.
<img width="366" alt="screenshot_1" src="https://cloud.githubusercontent.com/assets/25008318/21768291/27e0b2f8-d679-11e6-83dd-c190cdcee2b1.png">

the main site is: travian.de

don´t know if you can do anything about it whith this information.

thanks for developing, besides that issue it's a great tool.

**Comment by cpriest** [comment]
Unfortunately I can't get to the screen where I could see the HTML behind that screen shot, they may not be actual checkboxes.  Can you right click on one of them and click "Inspect Element."  What should show up is a console view with a line highlighted.  That should say <input type="checkbox"> with some other attributes.  Alternatively just screenshot that part of the screen and post it here.

**Comment by Honei01** [comment]
yeah, already thougt that. . .
sry fo the delay. 

you mean this?

<input id="slot142889" name="slot[142889]" class="markSlot check" onclick="Travian.Game.RaidList.markSlotForRaid(3220, 142889, this.checked);" type="checkbox">

**Comment by cpriest** [comment]
Hmm, well they are using an input box however the plugin would be checking/unchecking it directly rather than 'clicking' it, looks like the site has an onclick handler.  Are the boxes getting checked/unchecked but that's not having the effect you're expecting?

**Comment by Honei01** [comment]
yes exactly. The boxes get checked but are not really checked in the end, so not working when you hit the "send" button at the end of the page. you can also uncheck them normaly by klicking and check them the right way by klicking again. they look the same if clicked or selected with the tool.

**Comment by cpriest** [comment]
Makes sense, I'll consider this a bug and check for the onclick attribute.

**Comment by cpriest** [comment]
Just thought I'd post that the FireFox beta has been released and is ready for updating, see https://github.com/cpriest/SnapLinksPlus.
