### ISSUE TITLE
Suggestions & Bug Report

### ISSUE THREAD

**Issue by TimidScript** [cpriest/SnapLinksPlus#162]
Latest version suddenly stopped working in FireFox 51.0.1 (32bit).

Suggestion, ability to open new tabs at the end of the tab list rather than next to parent tab.

**Comment by cpriest** [comment]
Do you have any further details on what's going on?  This is the first I've heard of a problem and I'm using FF 53.0a2.  The suggestion is already in the plans.

**Comment by TimidScript** [comment]
Hi
Don't know what happened yesterday. But today it is working again. It suddenly stopped working on three different FireFox profiles, and one was pretty clean (few addons). Today it is working again. I have no clue. Only difference is I booted up the machine before starting FireFox again.
