### ISSUE TITLE
Addon disables right-click on certain Gfycat pages

### ISSUE THREAD

**Issue by Lemons224** [cpriest/SnapLinksPlus#163]
On the site Gfycat this addon disables right-click on pages like this: https://gfycat.com/YellowOblongCopperhead

With Snap Links on I cannot right click on that page and other pages like it (which I want to do if I ever want to save the video). When I turn SL off I can right-click again. I'm using Firefox browser and latest version of Snap Links.

**Comment by Keith94** [comment]
Works correctly for me with Snap Links 3.1.1.3 and Firefox 53.0a2

![image](https://cloud.githubusercontent.com/assets/5490615/22535636/2a8cb3ae-e8b1-11e6-961e-e7b16c74c908.png)

**Comment by cpriest** [comment]
If this is still an issue, the next beta/release will have the option to change which button is used to activate.
