### ISSUE TITLE
Blocks functionality of the Right Links add-on

### ISSUE THREAD

**Issue by theSLY** [cpriest/SnapLinksPlus#164]
Snap Links Plus 3.1.1.3 blocks functionality of the _Right Links_ add-on using Firefox 51, multi-process mode, Windows 8.1:
[https://addons.mozilla.org/en-US/firefox/addon/right-links/](https://addons.mozilla.org/en-US/firefox/addon/right-links/)

**Comment by cpriest** [comment]
I'll see if I can get them to play nicely together, I can see how SLP would do that since it captures the right mouse click and prevents propagation.

**Comment by cpriest** [comment]
This is fixed by way of configurability in the next beta release of SnapLinks.

**Comment by cpriest** [comment]
Just thought I'd post that the FireFox beta has been released and is ready for updating, see https://github.com/cpriest/SnapLinksPlus.
