### ISSUE TITLE
Screenshots not detected reliably

### ISSUE THREAD

**Issue by Keith94** [cpriest/SnapLinksPlus#165]
At this URL: http://sonome.dareno.me/projects/sg0.html#screenshots

Try selecting all four screenshots with SLP. Notice some aren't detected.

![2017-02-19_23-43-42](https://cloud.githubusercontent.com/assets/5490615/23116114/961bf198-f6fd-11e6-9720-2bb7390bd5e0.gif)

**Comment by cpriest** [comment]
Strange, I can see the behavior as well.  There was another report of a similar nature that's probably related.  I'll look into it when I get a chance to.

**Comment by cpriest** [comment]
Just thought I'd post that the FireFox beta has been released and is ready for updating, see https://github.com/cpriest/SnapLinksPlus.
