### ISSUE TITLE
Snaplinks website not working with chrome

### ISSUE THREAD

**Issue by bluebellrose** [cpriest/SnapLinksPlus#167]
The add to chrome button on the snaplinks 3.0 website isn't working. This was brought to my attention by one of my members that it wasn't working. I have refered her to Linkclump for now.

**Comment by Smile4ever** [comment]
@cpriest This is an important issue and needs fixing on the Snap Links Plus website. Even a link to the Chrome webstore would be better than a non functioning button.

If you don't have time for this, please point me to the relevant HTML and JavaScript code for the website.

**Comment by cpriest** [comment]
I'd appreciate the help, the website is hosted with github's pages on this branch: https://github.com/cpriest/SnapLinksPlus/tree/gh-pages

**Comment by cpriest** [comment]
The version for chrome that's been uploaded is still the 3.0b1 version, haven't had time to update the version there.

**Comment by bluebellrose** [comment]
apparently it's not registering again. Got a report of nothing happens when the add to chrome button is pressed again. When I tried accessing the url directly i got a 404 error.

**Comment by Smile4ever** [comment]
@cpriest Is the commit I made present on the live website?

**Comment by cpriest** [comment]
@Smile4ever well strangely, I must have lost that when I switched to using master/docs as the source for the git hub pages.  I put the link back but it was 404ing at google.  I think they took the extension down as I had not updated it.  I've temporarily taken out the link for chrome.

I am working on this project again though, getting it set up with CircleCI for automated builds, beta channel pushes, etc.

**Comment by cpriest** [comment]
Just an update, I've got the latest master branch working well in Chrome so will publish again to chrome on the next release and update the link for this ticket if necessary.

**Comment by cpriest** [comment]
I will get the latest released beta version back up on chrome as soon as I can (this week hopefully).  I have to see why the original release went missing and create a new Beta channel/version of the software on the chrome store.

**Comment by cpriest** [comment]
There is now a beta release version of SnapLinks for Chrome, link is on the home page
