### ISSUE TITLE
Scrolling and using Snaplinks

### ISSUE THREAD

**Issue by CZAlmon** [cpriest/SnapLinksPlus#168]
When using Snaplinks scrolling does not work as it should. For the past week (I have had Snaplinks for 3-4 weeks) when I try to use Snaplinks and scroll up (No matter how many links, could be 0 links or 20), I only ever scroll a single line at a time, when normally I scroll at least 10-20 lines at a time. Middle clicking and scrolling that way works, but scrolling normally and using Snaplinks just is not working correctly. Just a week/week and a half ago I could scroll normally and use Snaplinks to open however many links.

**Comment by cpriest** [comment]
There hasn't been any change to SnapLinks in several months; perhaps it's something else you've changed?
