### ISSUE TITLE
need more enhacement on mouse scroll

### ISSUE THREAD

**Issue by B3H3M0T** [cpriest/SnapLinksPlus#169]
use mouse scroll when use snap link was possible, but the scroll movement was so small it only move 1mm when 1  scroll using mouse.

**Comment by cpriest** [comment]
This is not an issue on my end, using the scroll wheel.  Is that what you're talking about or are you talking about auto-scrolling when dragging past the bottom of the window?

**Comment by cpriest** [comment]
Closing, no response.
