### ISSUE TITLE
New Tabs under the Parent Tabs

### ISSUE THREAD

**Issue by Reg65** [cpriest/SnapLinksPlus#172]
I don't know if this is a general FireFox issue or something specific to "Tree Style Tabs" however my previous multi tab opener "multi links" (which is not multi process friendly or I would still be using it without looking at alternatives) would open links "UNDER" the tab I opened from. Even without it using "right click" and then opening another tab positions the new tab under the parent tab. 

SnapLinksPlus does not honor nor acknowledge a parent tab but instead just opens tabs as an apendage to the current tab set. This is so inconvenient that I often just use "multi tabs" even knowing that it disables my multi process capabilities which by the way is a burden being a heavy user.

It would be outstanding if you (c|w)ould (just having fun) fix this one anomaly.

Cheers!

Reg
Cell: 702-675-8440 (yeah, I know you will never call me but you know I am real since you have my cell phone number, not some flacky BS crap person).

BTW, if you want a conversation, I will talk with you but I suspect you already have a clear understanding of the issue.

**Comment by cpriest** [comment]
Yeah, this has already been reported and I have already confirmed that Tree Style Tabs is going to be re-written as well (and thus their API I would need to call will be available).

Unfortunately, I just don't have any time for this project at the moment.  Always willing to accept pull requests though if you're able to put in some time.

**Comment by cpriest** [comment]
Just thought I'd post that the FireFox beta has been released and is ready for updating, see https://github.com/cpriest/SnapLinksPlus.
