### ISSUE TITLE
Checkboxes in options page aren't visible

### ISSUE THREAD

**Issue by Keith94** [cpriest/SnapLinksPlus#173]
In FF Nightly, the options can't be configured (checkboxes are not displayed)

![image](https://cloud.githubusercontent.com/assets/5490615/26189306/cb88971a-3b58-11e7-82fe-e14e219e870c.png)

**Comment by Smile4ever** [comment]
This is a known bug in Nightly, see [bug 1354336 - Addon options checkboxes inactive](https://bugzilla.mozilla.org/show_bug.cgi?id=1354336)

**Comment by cpriest** [comment]
Thanks for finding that @Smile4ever !
