### ISSUE TITLE
sometimes lasso doesn't detect links in version 3+ in Firefox

### ISSUE THREAD

**Issue by orangeplanet** [cpriest/SnapLinksPlus#174]
Attached are a couple of screen shots produced in the Firefox legacy version 45 and Snap Links Plus version 3.1.0.4
![snip1](https://cloud.githubusercontent.com/assets/7536637/26325036/4ca91d26-3f03-11e7-877d-e79a42023b81.png)
![snip2](https://cloud.githubusercontent.com/assets/7536637/26325040/501b42b8-3f03-11e7-9554-b3580cad021e.png)

This is the behavior that I was referring to in my review regarding version 3+ and FF 52 and FF 53.  For a while, I could only get version 2.4.3 to work in any recent release of Firefox.  This morning, however, I uninstalled the extension in FF 53 and reinstalled Snap Links version 3.1.1.3 and that seems to have resolved it.  Reinstalling also resolved the problem in my copy of FF 52.  But doesn't seem to help with FF 45.   Not sure if it is a "bug" or something on my end,  but I captured these two images and thought I'd let you know in case you want to investigate.

**Comment by cpriest** [comment]
Thanks for the report, it may not be compatible as far back as FF 45, that's quite out of date now.  I appreciate the report though.  Not sure as to why reinstalling would have fixed whatever issue you had been having, very strange.

**Comment by cpriest** [comment]
Just thought I'd post that the FireFox beta has been released and is ready for updating, see https://github.com/cpriest/SnapLinksPlus.

Please see if this issue still exists with the beta version.
