### ISSUE TITLE
Support pages that are still loading: insert content scripts at document_start, not document_idle

### ISSUE THREAD

**Issue by Smile4ever** [cpriest/SnapLinksPlus#175]
If you add this to manifest.json, Snap Links Plus will be usable on pages that take a while to load:

    "run_at": "document_start"

For more information, see https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/content_scripts

**Comment by cpriest** [comment]
Looks like they're moving along quickly on web extensions compatibility, nice to see.  I'll definitely add this in when I get back to the project, I'll probably use document_end though which is much sooner than 'complete.'

**Comment by cpriest** [comment]
This is fixed in master, surprised you didn't just issue a pull request for this, probably would have been released months ago...

**Comment by cpriest** [comment]
Just thought I'd post that the FireFox beta has been released and is ready for updating, see https://github.com/cpriest/SnapLinksPlus.

**Comment by cpriest** [comment]
Just thought I'd post that the FireFox beta has been released and is ready for updating, see https://github.com/cpriest/SnapLinksPlus.
