### ISSUE TITLE
Copy urls

### ISSUE THREAD

**Issue by rayman89** [cpriest/SnapLinksPlus#180]
Please add the option to copy the urls instead of opening the links.

**Comment by cpriest** [comment]
This is already a feature, check out the documentation.

**Comment by Keith94** [comment]
Copy to Clipboard is only available in v2 branch; not yet implemented in v3 AFAIK.

**Comment by Hrxn** [comment]
Holding down <kbd>Ctrl</kbd> while doing the selection should enable to copy links to the clipboard.

**Comment by Keith94** [comment]
Oh, you're right. I was not aware of that. ;)

**Comment by rayman89** [comment]
Where  is the documentation? @cpriest

**Comment by Hrxn** [comment]
http://cpriest.github.io/SnapLinksPlus/welcome.html
