### ISSUE TITLE
Snaplinks breaks Tree Style Tab 

### ISSUE THREAD

**Issue by ICDeadPeeps** [cpriest/SnapLinksPlus#183]
http://piro.sakura.ne.jp/xul/_treestyletab.html.en

The way SnapLinks opens new tabs, Tree Style Tab doesn't show them as a chlid tab and doesn't show them properly in the tree structure.

Please talk with the developer of Tree Style Tab tab and fix it.

**Comment by cpriest** [comment]
This has already been reported.
