### ISSUE TITLE
No detection links

### ISSUE THREAD

**Issue by WagnerGMD** [cpriest/SnapLinksPlus#186]
Hello,

do you think you will able to detect links on the page **about:about** and **about:newtab** ?
Because as for now, Snap Links Plus_v3.1.1.3 doesn't seem to detect them.

Best regards.

**Comment by cpriest** [comment]
Highly unlikely as a web extension but I can check into it sometime.  
Might be some permission available.

**Comment by WagnerGMD** [comment]
Glad to see one answer (it's almost rare these last months sic...).Sorry for my late reply (busy IRL) but I got an idea finally.
Then do you mean it could be realize (not web extension) ? Do you think you will be able create an addon for another browser (like Waterfox, etc) ? 
Because when Firefox_v57 will be publish, the legacy addon might have a support (at least with Waterfox according to this [reddit topic](https://www.reddit.com/r/waterfox/comments/5ysn9e/proposal_please_turn_waterfox_56_into_an_esr_and/deut7uq/?sh=9b2f3c1e&st=J26S7X20))

**Comment by Hrxn** [comment]
> PS : We can't make an addon with one language like Python or maybe Rust no ?

No, only JS.

**Comment by WagnerGMD** [comment]
Thank you @Hrxn it's clear.

**Comment by cpriest** [comment]
I looked into this unfortunately, those are 'privileged' pages and web extensions are not allowed to function on those pages, TMK.

**Comment by WagnerGMD** [comment]
Despite the bad news, @cpriest thank you I understand.

**Comment by WagnerGMD** [comment]
Sorry @cpriest but I believe it's useless to open another issue, right ? Even today the web extensions remain very limited.
Because I imagine the answer will be the same about the **recaptcha** (from Google) ? **Snap Links Plus** can't help to solve it.

**Comment by cpriest** [comment]
I'm not sure what recaptcha you're speaking of, this problem was about it being on a secured page `about:`.  If you're seeing something on an http/https site, that may be something solvable.

**Comment by WagnerGMD** [comment]
That's right, **recaptcha** is something totally different. A lot of website use this to protect them (to resume, it's about the security and just one puzzle (with pictures) to solve).
Do you need a few examples ? I could try to find them if you want.

**Comment by cpriest** [comment]
I'm trying to understand what you're wanting to do and what is not being allowed?  Could you create a quick gif-video and post to the thread here?  A URL with an example would be great too.

If the recaptcha is in an IFRAME then you'd need to start the drag within the iframe (closer to the actual link).  It could be that what you're trying to lasso isn't an <A>nchor or other elements that are targeted by SnapLinks.  Perhaps just a URL where you see the problem to start with and I can look at that first.

**Comment by cpriest** [comment]
I just ran across a particularly popular recaptcha (reCAPTCHA in fact), and looked into it.  It doesn't use an <A> tag, but I did notice it had some aria roles that may be of use for 'targeting.'

**Comment by cpriest** [comment]
Ah yes, I've seen those before.  The next time I see one I'll diagnose what's up and post in a new ticket for it.

**Comment by WagnerGMD** [comment]
If you don't have the time or didn't find any example @cpriest, let me know.
Several days or less ? I don't know but I assume I will be able to find a few examples. Because it's somewhere in my memories... And I believe I will find them. I just need time.
