### ISSUE TITLE
Question: Custom hot-key combination?

### ISSUE THREAD

**Issue by stefanos82** [cpriest/SnapLinksPlus#189]
With linkclump on Chrome I am given the option to choose the hot-keys of my choice, but with SnapLinksPlus I have to use mouse's right-click only.

I really like the combination of Shift key + mouse's Left-click.

I have looked at the preferences area and could not find any option like that, unless it's hidden somewhere and cannot see it.

Any suggestion?

Cheers.

**Comment by cpriest** [comment]
It's not currently possible.  I haven't had any time to work on SLP in a 
long time, it was originally planned and more but life got in the way of 
future development at the moment.

Pull Requests are welcome though, I can review them for release.

**Comment by Qwash** [comment]
This could fix incompatibility with ScrollAnywhere and other addons 😞

**Comment by cpriest** [comment]
I'm going to try and get back to SnapLinks soon but would love to get some help with it.

**Comment by jacobshare** [comment]
+1

**Comment by a2sheppy** [comment]
Yeah, triggering just on a right-click is troublesome since it can result in being accidentally triggered when using context menus.

**Comment by jellypadder** [comment]
ehh, this is exactly what i was about to ask about.  in an older version i used to be able to hold down my shift button+left mouse button to open links.  i find the right click hard to use with the way i have my computer set up.

**Comment by rayman89** [comment]
Yes please add the options like before to decide what to do by default with the links and its key modifiers.

**Comment by m2pt5** [comment]
Having it trigger on just right-clicking causes way too many issues, please add the key-to-activate option.

**Comment by Markieta** [comment]
+1 for Shift+LMB

Using the RMB is tricky on a laptop trackpad.

**Comment by cpriest** [comment]
This is already available in the beta release version currently on AMO or Chrome.

**Comment by m2pt5** [comment]
The beta on AMO doesn't seem to be publicly accessible, it just says "0 versions".

**Comment by cpriest** [comment]
You're right, I don't know why they aren't listed on the versions page now, they were before (and are listed in the developer pages).  Here is a link to [v3.1.2b2](https://addons.mozilla.org/firefox/downloads/file/894992/snap_links_plus-3.1.2b2-an+fx.xpi?src=devhub) which may or may not work without my login.  I've emailed AMO about the issue to see what's up.

**Comment by m2pt5** [comment]
That link works, thanks.

**Comment by cpriest** [comment]
Ah great ok.  I'll update the main page.  Looks like they are discontinuing 'beta builds' feature and have not quite gotten around to making it work well with automatic signature.  For now I'll keep the latest developer build linked directly from the read me page.

**Comment by stefanos82** [comment]
The latest beta version does not work. i can see the lasso and the highlighted links, but nothing opens as a new tab.

I chose Shift and Left Click and nothing opened.

I then chose Shift and Right Click...nothing yet.

I then chose only Left Click...still nothing.

Am I missing something I should do to make it work?

**Comment by m2pt5** [comment]
It's probably a conflict with another extension, it works fine for me, the only issue being that the right-click menu pops up when I release the mouse button. (I'm using Shift+Right.)

**Comment by stefanos82** [comment]
I doubt it.

Here's my extensions' list:

![image](https://user-images.githubusercontent.com/1777466/37897378-b96a7bc0-30ee-11e8-8651-d1d5357d60b5.png)

**Comment by rayman89** [comment]
@cpriest I don't see the option to copy links to clipboard as default behavior when letting go of the lasso in the beta version.

**Comment by cpriest** [comment]
If you turned on developer mode under advanced preferences there is a 'skip all actions' which would cause this.

**Comment by cpriest** [comment]
@rayman89 That feature hasn't been implemented.  I'm not sure the multi-key binding option will be implemented.  The original extension had essentially the default action or 'ask me' if holding down another key.  At this point, I intend to implement that functionality.

**Comment by stefanos82** [comment]
@cpriest I haven't done anything other than install it and associate my hotkey combination.

![image](https://user-images.githubusercontent.com/1777466/38058888-2087dc26-32ed-11e8-9ab8-b4deb77203c5.png)

**Comment by cpriest** [comment]
Hmm, try another key combination.  I think Firefox may reserve shift for 'always safe.'

**Comment by m2pt5** [comment]
With FF 57, Mozilla added new WebExtensions APIs. Since Waterfox is staying on 56, there may be one or more that this addon uses that it does not have.

**Comment by cpriest** [comment]
Ah, this extension is for FireFox and Chrome.  If you'd like to submit a pull request for compatibility fixes for other browsers, feel free so long as they don't break the primary browser targets.

I have a well documented [Your First Code Contribution](https://github.com/cpriest/SnapLinksPlus/blob/master/Contributing.md#your-first-code-contribution) document I put together to help you get a local environment setup.  I'd be happy to help with any questions.  

A good place to start to see where the error may be happening would be the error console (Ctrl + J in Firefox) or the Page Console (F12 in most browsers).

**Comment by Markieta** [comment]
Link doesn't work for me either.

**Comment by cpriest** [comment]
It would appear that they have completely abandoned the beta program now, all of the beta channel versions are now 'Disabled by Mozilla.'

I guess I will submit the new version for 'release' status, but that will need to go through the review process and may take a week or two, unfortunately.

I guess watch the main page for the 3.1.2.3 version whenever it gets approved.

**Comment by FatOrangutan** [comment]
>I guess I will submit the new version for 'release' status, but that will need to go through the review process and may take a week or two, unfortunately.

[Add-ons (even on the release channel) are now published immediately, and reviewed afterwards.](https://blog.mozilla.org/addons/2017/09/21/review-wait-times-get-shorter/)

**Comment by cpriest** [comment]
Ah, didn't catch that. I did notice it was available immediately though 
which is nice.

**Comment by Markieta** [comment]
Working fine on Firefox Quantum 59.0.2. Thank you @cpriest!
