### ISSUE TITLE
photos.google.com

### ISSUE THREAD

**Issue by Keith94** [cpriest/SnapLinksPlus#190]
Individual links can't be detected/opened properly

https://photos.google.com/share/AF1QipNMiecIyfj8TnIZVMgphm-JFOB24xap5NSDf_kywDWtF1zhIr2cTmLIcWKo8Ny1fg?key=WnZhbWtWWUZieGJFYXhNV2Q0djBBNWxteTlSbnd3

**Comment by cpriest** [comment]
This is due to boundary indexing, will fix in next beta release.

**Comment by cpriest** [comment]
Just thought I'd post that the FireFox beta has been released and is ready for updating, see https://github.com/cpriest/SnapLinksPlus.
