### ISSUE TITLE
Can't select multiple radio buttons in a row

### ISSUE THREAD

**Issue by sfinam** [cpriest/SnapLinksPlus#191]
I've used this addon a lot to fill some checklists we have, but it won't mark radio buttons for me anymore if they are inside the table for me for some reason (worked in v2, never worked in v3, doesn't work with the latest version from the github readme link as well). I use Firefox 55.0.2 64bit in Ubuntu Linux, SnapLinks v3.1.1.3.

I've saved a web page to show how it looks, here is the file:
[sample_checklist.zip](https://github.com/cpriest/SnapLinksPlus/files/1236910/sample_checklist.zip)

SnapLinks won't select any of the radio buttons there for me, but still works on links.

**Comment by cpriest** [comment]
I've been working on this project and I fixed an issue that I thought related to this.  I have downloaded the sample file and see that it's not working here, though I'd say the HTML is fairly non-standard, after looking at the HTML I was surprised that even the label was highlighted properly.  In any case, I think it is fixable without much trouble, but it's not fixed just yet.

**Comment by cpriest** [comment]
Just thought I'd post that the FireFox beta has been released and is ready for updating, see https://github.com/cpriest/SnapLinksPlus.

**Comment by sfinam** [comment]
Thank you! Updated and I can confirm this issue is fixed now for me.
