### ISSUE TITLE
How to use it? Which modifier keys?

### ISSUE THREAD

**Issue by AllanLRH** [cpriest/SnapLinksPlus#205]
Hi there!

How do I use this plugin (Mac OS High Sierra, Firefox 57)? I can't find the correct combination of modifier-keys.
The right-click on a mac touchpad is achieved by ctrl-clicking, but when I drag the mouse cursor while holding down the ctrl-key, it's not registered by SnapLinks.

**Comment by AllanLRH** [comment]
Never mind, figured it out: I can right-drag using two fingers at the touchpad, as per this setting (it might be configured different on other machines):

<img width="780" alt="screen shot 2017-11-29 at 10 42 22" src="https://user-images.githubusercontent.com/2641327/33368489-266d2c44-d4f2-11e7-88c8-c656fae356f0.png">

**Comment by AllanLRH** [comment]
Actually it doesn't seem to work on pages where you're able to scroll, since scrolling are also done with two fingers.

**Comment by cpriest** [comment]
That would have to do with your input device, not snap links.
