### ISSUE TITLE
Link selecting broken on imagefreegoldmine.wikidot.com

### ISSUE THREAD

**Issue by nellymoose118** [cpriest/SnapLinksPlus#209]
http://imagefreegoldmine.wikidot.com is a popular goldmine for magistream players and unfortunately it seems SnapLinks is currently broken on this site as it doesn't seem to recognize any links displayed.

**Comment by cpriest** [comment]
Just thought I'd post that the FireFox beta has been released and is ready for updating, see https://github.com/cpriest/SnapLinksPlus.

Can you see if the beta version has addressed this issue?
