### ISSUE TITLE
Tree Style Tab and Snap Link Plus when opening google search results of 2 or more tabs it creates a unnessary child tab

### ISSUE THREAD

**Issue by ng4ever** [cpriest/SnapLinksPlus#210]
Anyway to fix this?

If you need a screenshot of the issue I will provide.

**Comment by cpriest** [comment]
Please check this in the upcoming beta release and see if it's still an issue.

If it is, re-open this ticket and post a public URL and instructions on how to reproduce as its probably related to the website you're working with.
