### ISSUE TITLE
Not working on tumblr

### ISSUE THREAD

**Issue by tp78903** [cpriest/SnapLinksPlus#211]
https://static.tumblr.com/0037f338ab8c6dc4d344d79ff6af6b8f/ojudpkb/fSEow5yql/tumblr_static_8ojfjqr0xps8sksg0ckgoo88o.jpg
^ Right-click rectangle is stuck at the top section of the image

http://studiofow.tumblr.com/FAQ
^ Right-click menu works but right-click drag doesn't. Log in and turn off safe mode first.

**Comment by cpriest** [comment]
Just thought I'd post that the FireFox beta has been released and is ready for updating, see https://github.com/cpriest/SnapLinksPlus.

Can you see if the beta version has addressed this issue?
