### ISSUE TITLE
How do I use Snap Link Plus for Android?

### ISSUE THREAD

**Issue by davidhedlund** [cpriest/SnapLinksPlus#213]

**Comment by cpriest** [comment]
I don't know that it would work on Android as it presently activates on a right click-drag

**Comment by davidhedlund** [comment]
https://addons.mozilla.org/en-US/firefox/addon/snaplinksplus/versions/ says
> Version 3.1.1.3 Released Dec. 20, 2016 69.2 KiB Works with Firefox for Android 50.0 and later, Firefox 50.0 and later
> Source code released under MIT/X11 License What's this?

**Comment by cpriest** [comment]
I'm not sure why it would say for Android, I've never tested it there.

That being said, if you had some way of telling your android what a 
right click was then it would work just fine.  It's not specifically 
written to work with touch events.  If you want to open up a new ticket 
requesting support for touch interfaces, that would be good.

**Comment by davidhedlund** [comment]
Thanks.
