### ISSUE TITLE
How can I set SL+ simply to *BOOKMARK* a group of selected links (FF58.0.2, Win7, x64), as opposed to *OPENING* them all at once?

### ISSUE THREAD

**Issue by Joenewnew** [cpriest/SnapLinksPlus#216]
Hello, Clint,

How can I set Snaplinks-Plus simply to *BOOKMARK* a group of selected links (in FF58.0.2, Win7, x64), as opposed to *OPENING* them all at once?

Thanks very much!

Joe

**Comment by cpriest** [comment]
This is not presently a feature of the v3 branch, but it's on the roadmap.

**Comment by Joenewnew** [comment]
Hi, Clint,

Thanks for replying. Do you have any idea of when, just roughly, that
function might become available? I'm not conversant with coding; would the
bookmarking feature require a major branch-type project?

Also, if you don't mind me asking, what is going on with Firefox's massive
v. 57+ rebuild? They seem to have lost a lot of add-on functions. Is there
a bright side to that?

I very much appreciate your work, so I hope you'll pardon me if my
questions are dumb. Thanks again, and have a great week!

**Comment by cpriest** [comment]
> Do you have any idea of when, just roughly, that function might become available?

I haven't even looked to see if that feature is implementable via the new API, but it most likely is.

> Also, if you don't mind me asking, what is going on with Firefox's massive
v. 57+ rebuild? They seem to have lost a lot of add-on functions. Is there
a bright side to that?

*Technical Answer:* The reasons behind this are simple, electrolysis is coming, XUL/XPCOM are on the way out and chrome style plugins are the new standard, which also happens to be both restartless and compatible with chrome, opera and in the future, other browsers.

Links are available on the main page of this project.

Short Answer: Yes, the future is very bright.

**Comment by Joenewnew** [comment]
Thanks for the informative reply, Clint. Being completely in the dark about
something we use every day can get pretty tiring. :o) Have a great one!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
