### ISSUE TITLE
Please add an option to open the new tabs at the end of the tab bar instead of always at the beginning

### ISSUE THREAD

**Issue by btanner2** [cpriest/SnapLinksPlus#217]
Hi,

If you open links with this add-on, all these links are opened in tabs which are placed at the beginning of the tab bar. This makes it a bit complicated, because you have always the last open tabs on top instead at the end. Could you please fix this? It would be more natural to place the last opened tabs even at the end of the list. 

Thanks a lot

Brian

Snap Links 3.1.1.3
FireFox 58.0.2 (64-Bit)

**Comment by cpriest** [comment]
The currently released version should be opening the tabs after the current tab (but not necessarily at the end).  Is it opening before the current tab?

**Comment by btanner2** [comment]
Hi,

You are right. New tabs are opened after the current tab. But this is part of the issue. Look, if you need to open a lot of links which are spread over the page, you are almost not able to open them in one single action. This means, you have to scroll, switch page or doing something else. If this happened, the second selection of all links will open again after the current tab. Since the current tab hasn’t changed, you will always see your last opened links at first. A small example, if you open 5 different links three times you will get this tab result:

11 12 13 14 15
6 7 8 9 10
1 2 3 4 5

This happens pretty often, you only have to use the add-on on amazon.com for example. It would be excellent if you could include an option to >>always<< open tabs at the end. This would benefit all users from your add-on. I think the pre 57 Version had something similar included?

Last but not least: Thanks for your great add-on. It saves me a lot of hours. :)

Kind regards
Brian

**Comment by cpriest** [comment]
I see, this feature has already been requested then, #193, which is scheduled for v3.2 release (next version).  It should appear in the beta channel first, which is nearly ready for release to the new beta channel coming up.
