### ISSUE TITLE
Snapping links doesn't work with Reddit modmail

### ISSUE THREAD

**Issue by ghost** [cpriest/SnapLinksPlus#222]
This is what happens, I can't go any lower than that:

![sans titre](https://user-images.githubusercontent.com/23002529/37555951-dc5a67f4-29ef-11e8-983f-c889f0e864fb.png)

Works fine with [CopyAllUrl](https://github.com/vincepare/CopyAllUrl_Chrome), not sure if it helps.

**Comment by cpriest** [comment]
I'd bet that is in an iframe if I had to guess, but I can look into it.  What happens if you start dragging elsewhere?

Also, can you point me to a specific public page that you know it's happening on, with another screenshot (if it's different positioning)?

**Comment by cpriest** [comment]
So I'm not seeing any problem on reddit, but my page looks quite different than the image you pasted:

![image](https://user-images.githubusercontent.com/159323/37561024-0e39f074-2a12-11e8-9709-1ea225a0a604.png)

**Comment by jrmio** [comment]
Well, as mentioned in the title above, you need to access the [modmail](https://mod.reddit.com/mail/all) to reproduce the issue.

**Comment by cpriest** [comment]
I've made some changes that may take care of these problems, please check in the next release and let me know if there are further problems.

**Comment by cpriest** [comment]
Closing the other new ticket #283 to keep the issue over here.  Is there anywhere else you can find this happening that is public?

**Comment by jrmio** [comment]
I'm sorry but no public website where this occur comes to mind at this time. I will let you know if I find anything, but accessing the modmail for test purposes is pretty [easy](https://www.reddit.com/subreddits/create) (HMU if you need help).
