### ISSUE TITLE
when using the lasso, if it contains links and checkboxes, checkboxes wil not be toggled

### ISSUE THREAD

**Issue by secretuser** [cpriest/SnapLinksPlus#223]
I use snaplinks for checkbox toggling, and it all goes well when there are only links or only checkboxes, but when both are inside the lasso, only the links will work and there is no way for me to only toggle checkboxes. Am I missing a modifier to do so or is this usecase not implemented yet? 

anyway, thanks for your work on the extension

**Comment by cpriest** [comment]
It uses the 'greatest number' in mixed mode.  Meaning if you have 
lasso'd 4 checkboxes and 5 radio buttons it will go with the radio 
buttons.  There is not presently any way to tell it 'checkboxes only' 
right now.
