### ISSUE TITLE
Selected links no longer open after most recent update

### ISSUE THREAD

**Issue by spb331** [cpriest/SnapLinksPlus#224]
Hi, I'm using SnapLinksPlus in Waterfox (equivalent to FF 56.0.x), and since today's update to 3.1.2.3, selected links are not opening. The selecting part works fine, it shows the lasso area, highlights each selected link and provides the number of links selected, but no action happens on those links. The extension was completely functional for me previously. I did install a couple of new extensions (Text MultiCopy and Link Text and Location Copier) along with the SnapLinksPlus update, but I've disabled both of those with no effect on the SnapLinks issue.

**Comment by Numbergod** [comment]
Also not working since upgrading to this release in Firefox 56.0.2 (64-bit) on Win7.

Previous release was working perfectly.

**Comment by cpriest** [comment]
Can you tell me what is showing for snap links in the error console?

**Comment by HouyiTheArcher** [comment]
Same issue for me. Latest AMO version of SnapLinks with latest FF ESR (52.7.3)

I enabled logging, but the only thing it outputs is:

ActUpon(Links) -  Object { Links: Array[4], FilteredLinks: Array[0], Clickable: Array[0], FilteredClickable: Array[0], Checkboxes: Array[0], RadioButtons: Array[0], GreatestType: "Links" }

Links are visibly selected, but new tabs do not open.

**Comment by cpriest** [comment]
I have just released an interim version which disables DevMode and a couple of other dev mode options on startup (to reset those preferences).  One of them was on by default (skip actions) which is probably the cause of this.

I'll let that release be out for a day or so before putting out another release which doesn't always set those options to false.

**Comment by spb331** [comment]
Just installed the interim version and it has indeed fixed the issue. Thanks!

**Comment by Numbergod** [comment]
Also not working since upgrading to this release in Firefox 56.0.2 (64-bit) on Win7.

Previous release was working perfectly.

**Comment by cpriest** [comment]
@Numbergod Yep, it's already been requested.
