### ISSUE TITLE
After closing a new tab, focus is randomly chosen between the original old tab and the next new tab

### ISSUE THREAD

**Issue by LucionGid** [cpriest/SnapLinksPlus#225]
As the title says, I have used this addon for quite a while now and this is the first time such behavior is observed. 

Let's say that the original tab is tabA and i use snaplink to open tabB, tabC, tabD and tabE from this tabA, then switch my focus to tabB. With the older versions, if i close the now focused tabB using Ctrl+W, the next automatically focused tab will be tabC (which makes sense according to the order). However, it seems that with the newest version, the automatically focused tab after closing tabB is randomly chosen between tabA and tabC, which is quite frustrating.

To make the matter worse, this behavior is not limited to tabB. Let's say that from the beginning i switch my focus to tabC instead of tabB. Now if i close the focused tabC, such random behavior also applies and there are chances that i'm thrown back to tabA instead of moving on to tabD.

I hope that this issue is fixed in future update.

**Comment by cpriest** [comment]
Duplicate: #221

**Comment by cpriest** [comment]
There is now an interim release being made available which disables the new feature which causes this issue.  The next release will have it behind a disabled-by-default option.
