### ISSUE TITLE
"Added support for FireFox Containers" 

### ISSUE THREAD

**Issue by DilectableBananaButterfly** [cpriest/SnapLinksPlus#226]
It's unclear what "Added support for FireFox Containers" means but one would assume that a link selected in container A would be opened in container A.

In 3.1.2.4, this is not the case. Selected links in Container A are still opened in the default perspective.

**Comment by cpriest** [comment]
Hmm, it's possible that the quick reversion of some new functionality 
disabled that temporarily.  I'll double-check before the next release.

**Comment by cpriest** [comment]
This should be fixed in v3.1.6 (the next release).
