### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by davidhedlund** [cpriest/SnapLinksPlus#227]
Can you please add these release notes to https://addons.mozilla.org/en-US/firefox/addon/snaplinksplus/versions/?page=1#version-3.1.2.3 ?

> v3.1.2b1
> Added ability to control which modifier keys and which mouse button is used for activation
> Fixed issues with chrome
> Fixed an issue with radio button selection
> Fixed an issue with checkboxes
> Added support for FireFox Containers
> Added support for Child/Parent tabs (Tab Tree View)
> Updated Options/Config to include expanded functionality

To https://addons.mozilla.org/en-US/firefox/addon/snaplinksplus/versions/?page=1#version-3.1.1.3
> v3.1.1
> A few configuration options now available
> Enable/Disable switching focus to new tab.
> Show/Hide the number of selected links.
>

**Comment by davidhedlund** [comment]
https://github.com/SalvatoreMeschini/CheckThemAll/issues/3

**Comment by davidhedlund** [comment]
Thank you very much for fixing the checkbox issues. Snap Links Plus is **super useful** now.

**Comment by cpriest** [comment]
Your welcome, sorry it took so long.  Life...

**Comment by davidhedlund** [comment]
There are no release notes at https://addons.mozilla.org/en-US/firefox/addon/snaplinksplus/versions/ on version:
* 3.1.6
* 3.1.5
* 3.1.1.3

I'd like to know the release notes for debugging purpose. Can you please add it and actively add release notes for further releases?

**Comment by cpriest** [comment]
Yeah, I'll try and do that as soon as I can.

**Comment by davidhedlund** [comment]
> Yeah, I'll try and do that as soon as I can.

Thanks. I understand if you are too busy right now and there's no rush, I just want to be able to follow your project in the future.

**Comment by davidhedlund** [comment]
Can you please re-open the issue until you have fixed it?

**Comment by cpriest** [comment]
Yes, no problem.  Out of curiosity are you not able to re-open this ticket?

**Comment by davidhedlund** [comment]
> Yes, no problem. Out of curiosity are you not able to re-open this ticket?

I can check if you close it again.

**Comment by davidhedlund** [comment]
> Yes, no problem. Out of curiosity are you not able to re-open this ticket?

No, it's not possible to re-open issues closed by the owner. You cannot re-open this [issue](https://github.com/prezesp/scoop-viewer/issues/13) for example, right?

**Comment by davidhedlund** [comment]
I can only close issues that I have opened.

**Comment by cpriest** [comment]
I see; I hadn't realized that.  I've been telling people to re-open the ticket if it persists after a release.  Thanks!

**Comment by davidhedlund** [comment]
> I see; I hadn't realized that. I've been telling people to re-open the ticket if it persists after a release. Thanks!

I can imagine how confusing this must have been for you. I'm glad that you figured it out eventually.

**Comment by cpriest** [comment]
Yeah, I use GitHub extensively at work in private repos where everyone has rights to open/close tickets, etc.  I guess I set it up so long ago I'd forgotten that it can be locked down (or defaults to that, which would make sense).

**Comment by cpriest** [comment]
They've been updated.
