### ISSUE TITLE
Improved screenshots

### ISSUE THREAD

**Issue by davidhedlund** [cpriest/SnapLinksPlus#228]
I suggest two new screenshots to https://addons.mozilla.org/en-US/firefox/addon/snaplinksplus/ captured on your [demo page](http://cpriest.github.io/SnapLinksPlus/welcome.html):
* One screenshot when the links are lassoed.
* One screenshot when the check boxes are lassoed.

**Comment by grahamperrin** [comment]
If it's possible for a screenshot to show how to lasso without showing the contextual menu, that'll be smart.

**Comment by cpriest** [comment]
> If it's possible for a screenshot to show how to lasso without showing the contextual menu, that'll be smart.

That sounds like a bug?  Are you getting the contextual menu after you release the mouse button (and there is a green lasso on screen)?
