### ISSUE TITLE
white text in selected links counter

### ISSUE THREAD

**Issue by thaliel** [cpriest/SnapLinksPlus#229]
this happened by accident (I think) before, but it is always happening over on this particular site
https://i.imgur.com/hcEcofw.png
Links are still being counted, but you cannot read how many are selected beaceuase the text is white.It is perfectly fine anywhere else. Thought there might be a chance of getting any insight on why this is happening

**Comment by cpriest** [comment]
Most likely it's happening because of the nature of CSS.

Does that happen on the home page as well?

![](https://i.imgur.com/hcEcofw.png)

**Comment by thaliel** [comment]
it does. I can at least get dark greytext when changing to a different theme. Never even imagined a site's custom css style can affect thhe look of an extension
