### ISSUE TITLE
Network error while attempting to fetch resource.

### ISSUE THREAD

**Issue by Bronzdragon** [cpriest/SnapLinksPlus#233]
This extension has an error while a sourcemap is being fetched.

![image](https://user-images.githubusercontent.com/1936103/38820749-a33ccc46-4196-11e8-8596-24187a01c2a5.png)

**Comment by cpriest** [comment]
Strange, that doesn't really need to be present in the FF build anyways, I'll see about having it removed but it shouldn't fail to load.  Are there any details as to why it failed?
