### ISSUE TITLE
Please have a option to open links in child tabs when using tree style tabs addon from the current tab

### ISSUE THREAD

**Issue by ng4ever** [cpriest/SnapLinksPlus#234]
If possible. 

Thanks.

**Comment by cpriest** [comment]
Technically this is a duplicate but was turned off in an emergency rollout due to an undesirable effect that Firefox causes when the child tabs feature is enabled.  I haven't gotten back to the issue.

**Comment by cpriest** [comment]
The next version release has an option to enable tree style tab functionality, but comes with some downsides as detailed in another ticket.
