### ISSUE TITLE
[Feature request] Context menu support

### ISSUE THREAD

**Issue by i486** [cpriest/SnapLinksPlus#237]
Hi, This is a really nice addon! 

It would be really great if you add some different way to open links. 

Current default is "letting go of the right click"

I'd like to open links with context menu like this

1. Select links with rectangle
2. Let go of the selection without opening tabs
3. Open context menu
4. SnapLinksPlus > Open selected links in background tabs, etc

Thanks

**Comment by damoclark** [comment]
Extending on this idea, subsequent right-click drags could then select additional links that are not in proximity to the first group.  And subsequent right-click drags could also deselect previous selections if dragged across again to omit some links from a broader cluster.  

Think along the lines of holding shift/ctrl key when dragging selection of files in Apple Finder or Windows Explorer.

And the final selection is then enacted with a right click context menu option.

**Comment by remi-garcia** [comment]
Closed in favor of #351
