### ISSUE TITLE
Seamonkey

### ISSUE THREAD

**Issue by WaltP9999** [cpriest/SnapLinksPlus#238]
SL+ worked in Seamonkey 2.49.1 but does not install on 2.49.3.

Are you planning to continue support?

Thanks

**Comment by cpriest** [comment]
Was never officially supported, but if seamonkey supports web extensions then it should be fine.

**Comment by cpriest** [comment]
Are you installing it from mozilla addons?

**Comment by WaltP9999** [comment]
No. From the add-ons page, or direct download
