### ISSUE TITLE
javascript:void links

### ISSUE THREAD

**Issue by hulst88** [cpriest/SnapLinksPlus#240]
The addon is not reconizing javascript:void links.
So it will not open them individually 

And there is not time delay. Is that possible?
![afbeelding](https://user-images.githubusercontent.com/39407562/40233775-92c655d6-5aa4-11e8-9d1f-014b91db5520.png)

**Comment by cpriest** [comment]
Can you post the HTML for one of those links?  What are you expecting it to do?

The time delay is already a requested feature #153.

**Comment by hulst88** [comment]
Hi Sir,

Those "genereer badge opnieuw" buttons are going tot print a html file and
I want to select all those to print badges behind those links.
It worked with a different plugin but that one stopped a year back

<tr><td>Maitre Andre</td><td>Chaudron</td><td>Walter </td><td>Film
gezien</td><td></td><td>n.v.t.</td><td></td><td><a href="
http://www.raisecurity.com/achterkant/37/211236/604/">Details</a></td><td><a
href="http://www.raisecurity.com/achterkant/41/again/211236/604/">Mail
opnieuw</a></td><td><a href="javascript:void(0);"
onclick="document.getElementById('badgeFrame').src = '
http://www.raisecurity.com/achterkant/generate_html_badge.php?name=Walter++Chaudron&amp;exhibitor=Maitre+Andre&amp;exhibition_id=604&amp;exhibition_name=RAI+Amsterdam';
return false;">Genereer badge opnieuw</a></td></tr>

thnx for reviewing

2018-05-18 15:38 GMT+02:00 Clint Priest <notifications@github.com>:

**Comment by cpriest** [comment]
```html
<tr>
	<td>Maitre Andre</td>
	<td>Chaudron</td>
	<td>Walter</td>
	<td>Film
		gezien
	</td>
	<td></td>
	<td>n.v.t.</td>
	<td></td>
	<td><a href="
http://www.raisecurity.com/achterkant/37/211236/604/">Details</a></td>
	<td><a
			href="http://www.raisecurity.com/achterkant/41/again/211236/604/">Mail
		opnieuw</a></td>
	<td><a href="javascript:void(0);"
		   onclick="document.getElementById('badgeFrame').src = '
http://www.raisecurity.com/achterkant/generate_html_badge.php?name=Walter++Chaudron&amp;exhibitor=Maitre+Andre&amp;exhibition_id=604&amp;exhibition_name=RAI+Amsterdam';
return false;">Genereer badge opnieuw</a></td>
</tr>
```

**Comment by cpriest** [comment]
Someone else implemented a way to make this work in v2, I'll have to go check out the method he used for these types of legacy cases.

**Comment by cpriest** [comment]
This is an old ticket, I was just testing this and the click is happening for A elements, but there is no delay.  Are you seeing the same?  Ticket #114 is already present for the delay feature request.  

I'm going to close this ticket unless there is some other issue going on here.  Based on your picture it looks like SnapLinks is highlighting them, so it should be `.click()`ing the element.  I will be adding a delay from the other ticket.

Feel free to re-open if there still remains an issue.
