### ISSUE TITLE
Add option to copy links with right click only

### ISSUE THREAD

**Issue by kang21** [cpriest/SnapLinksPlus#246]
Can you add an option to copy links by dragging right click only, instead of pressing ctrl after dragging right click.
Thanks

**Comment by cpriest** [comment]
I can consider it as a possible future feature.

**Comment by DrDustwolf** [comment]
I would like this feature too.

**Comment by Lain25** [comment]
Yes that feature is essential, I would be very grateful for it.

**Comment by remi-garcia** [comment]
Done in #303 
Should be in next release.

**Comment by cpriest** [comment]
Gosh I need to get a release done, my apologies.
