### ISSUE TITLE
New tabs are not being opened in the correct sequence.

### ISSUE THREAD

**Issue by jedikalimero** [cpriest/SnapLinksPlus#248]
Usually, when you middle click a link, it opens in a new tab to the right. Then, if you middle click on another link, it opens in another tab to the right of the previous new tab. Tabs keep being created to the right of the last tab created until you move to another tab. In this way, you have to the right of your current tab all the new tabs you have opened from links in this tab in the sequence the links were clicked.

But SLP does not behave this way.
Imagine you have a thumbnails gallery of 16 pictures and just in the middle of the gallery there is a publicity banner that you want to avoid. You would drag around the first 8 pictures so SLP would open 8 tabs to the right of the current one in the correct sequence 1,2,3,4,5,6,7,8. You then drag around the last 8 pictures and SLP opens another 8 tabs but these tabs are not opened to the right of the last created tab but again to the right of the current tab!

So you end up with the tabs in an incorrect sequence: 9,10,11,12,13,14,15,16,1,2,3,4,5,6,7,8

**Comment by cpriest** [comment]
Duplicates #239

**Comment by cpriest** [comment]
Ah, in this case it's still a duplicate, but of a different ticket (open 
tabs next to current tab, or at the end).

I'm assuming you'd want them opened with 7 8 9 after the 6th one, right?

**Comment by jedikalimero** [comment]
Obviously, since this is the order you would obtain if you go middle clicking the thumbnails in order without using SLP.
The behavior of Firefox or Chrome (and one that makes sense) is that as long as you don't move to another tab, all new tabs are always created to the right of the last new tab created, not to the right of the current tab.
SLP does it right when opening several links at the same time in one single selection but fails when opening those links with several selections.

Also notice that when you open several links in a single selection and then you open a single link in the standard way (middle click, ctrl+left click or context menu option), the new tab is also created to the right of the current tab, not to the right of the last tab SLP created. So this is an indication that Firefox is not counting the tabs that SLP created in order to know where to create the new tab.

**Comment by jedikalimero** [comment]
Is always better to have the option to allow several different behaviours, of course. But the default behaviour should be the same as default Firefox.

**Comment by btanner2** [comment]
Is this issue probably a duplicate of https://github.com/cpriest/SnapLinksPlus/issues/193 ?

**Comment by cpriest** [comment]
I think this one may be different.

Sorry I haven't released yet, I tried this morning and found my tooling 
was not working properly with the latest node, need to sort that out but 
will release as soon as I can.

**Comment by btanner2** [comment]
Thanks for all your efforts :) I am really looking forward to the updated version. :)

**Comment by jedikalimero** [comment]
Btanner2, notice the issue you mention is about creating tabs at the right of the current one OR at the right of the rightmost one.
This issue is about creating tabs at the right of the rightmost one RECENTLY CREATED so all tabs appear in the correct order they would if their links had been clicked manually instead of with the aid of SLP. This way, a sequence of links would always appear in the correct order even if it had to be clicked with two or more uses of SLP instead of just one.

**Comment by jedikalimero** [comment]
Cpriest, thanks for all your effort! I wish I had any idea of programming so I could help you with this and some many others with their add ons!
Keep up the good work. You keep the Firefox community alive.

**Comment by cpriest** [comment]
@jedikalimero

Actually, it's really not too hard and there are a *ton* of resources on 
how to learn, even games to learn how to program.

These are aimed at kids but who says they get to have all the fun?
   * https://codecombat.com/

Other articles:
   * https://skillcrush.com/2017/04/03/free-coding-games/
   * 
https://medium.mybridge.co/12-free-resources-learn-to-code-while-playing-games-f7333043de11

I encourage you and anyone else to get hooked, I was fortunate enough to 
get hooked when I was under 10.  I love to write code, just don't have a 
lot of time to do it with family and work.

**Comment by btanner2** [comment]
@jedikalimero: I am not sure if with both mean exactly the same issue or not. I have tested the new checkbox from https://github.com/cpriest/SnapLinksPlus/issues/193 with this example:

1 2 3 4 5
6 7 X 9 10
11 12 13 14 15

X means your banner. I have opened the links with SLP in the following order to avoid the banner:

First: 1 2 3 4 5
Second: 6 7
Third: 9 10
Fourth: 11 12 13 14 15

Result: 1 2 3 4 5 6 7 9 10 11 12 13 14 15 => correct!

Without https://github.com/cpriest/SnapLinksPlus/issues/193 I got the following result:

11 12 13 14 15 9 10 6 7 1 2 3 4 5  => not correct!

Would this solve your issue?

Kind regards
Brian

**Comment by jedikalimero** [comment]
I don't know how to try the modified add on. I'm using current version available at Mozilla (release 3.1.2.4 from 5 months ago).

For what I have read, this works ok if the tab with your thumbnail gallery is the rightmost tab. But I understand that if the tab is, lets say, number 42 of 50 (being number 1 the leftmost), the new tabs would open to the right of tab 50 instead of to the right of tab 42. Am I right?

Anyway it is a great improvement over the current situation since we now have the tabs listed in the correct order. I would be more than happy with that solution! How can I install the modified add on?

**Comment by btanner2** [comment]
Hi,
well the easiest way would be if @cpriest would release this version. I hope he can do this this week.

Unfortunately add-ons have to be signed by the developers to work in the normal Firefox Version. If you change the add-on by yourself it will automatically turned into an unsigned add-on which prevents Firefox to run this add-on properly. 

If you want to do this anyway, you need a different version from Firefox like developer Version which can run unsigned add-ons too: https://www.mozilla.org/de/firefox/developer/. If you have this, you can download the source from SLP here: https://github.com/cpriest/SnapLinksPlus/archive/master.zip 

Download the original SLP Addon from Mozilla too and unzip it (xpi = zip). Merge the master into the unzipped folder. Check this link how to load add-ons on the fly:

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension

Happy testing : - ) 

If there is an easier way, please let me know.

Brian

**Comment by cpriest** [comment]
My apologies,

I'm just going to roll back to an older version of node and use the 
older version of gulp as I haven't had time to re-write that. I'll try 
and get it out asap.

**Comment by cpriest** [comment]
Good news, I was able to get everything rolled back to a working state 
and have published the new 3.1.3 to FF & Chrome.

Thanks @btanner2!

**Comment by jedikalimero** [comment]
Great news! Thank you cpriest!

**Comment by jedikalimero** [comment]
And thank you for the lonks about learning! I will try to do something despite I haven't proggrammed anything since my days with the Commodore Amiga

**Comment by jedikalimero** [comment]
> @jedikalimero: Just test your banner-page again if everything works as expected now :-)

More or less. As I suspected, It works as I wanted when the gallery is the rightmost tab, but when the gallery is not the rightmost tab, the new tabs don't open to the right of it, but to the right of the rightmost tab.
But that's good enough for me since I can have all the pictures now in the correct order even if they are not next to the gallery tab. 👍
Thank you!

**Comment by cpriest** [comment]
Yeah, no problem at all, it's open source.  The world needs more 
developers!  I've offered to help anyone understand something if they 
were interested, even built out a detailed contributing page.

Truth is, I don't have the time to add every feature to this extension, 
though I'm not opposed to them.

**Comment by cpriest** [comment]
I might be mistaken, but I believe this was fixed by a patch from @btanner2 a while back?  I'm dedicating some time to SL3 for a while here and just catching up on some tickets.  Looks like this is no longer an issue, if it still is, please re-open.
