### ISSUE TITLE
SLP acts erratically in Image Twist (attached image NSFW)

### ISSUE THREAD

**Issue by jedikalimero** [cpriest/SnapLinksPlus#250]
I have noticed SLP doesn't act properly in the thumbnail galleries hosted in Image Twist.

Here is an example:
https://imagetwist.com/?per_page=47&fld_id=249650&usr_login=0x10&op=user_public&page=1

Here is a screen capture where you can see only two thumbnails have been selected:

![captura de pantalla 2018-08-11 03 26 36](https://user-images.githubusercontent.com/18701653/43987341-0ba4043a-9d17-11e8-83aa-c3f2dcae35d3.png)

Unfortunately I don't have any clue what can be the cause of this erratic behaviour.

**Comment by cpriest** [comment]
When this happens, what does it do if you hold down alt, ctrl or shift?  
Does that highlight all of the images?

**Comment by jedikalimero** [comment]
- When I hold ALT and then right click and drag, nothing happens. No SLP or context menu.
- Same when I hold CTRL, except this time, when I release right mouse button or CTRL, the regular context menu appears.
- With SHIFT, the behaviour is the same as with CTRL.

It still doesn't work correctly if I disable the link filtering by font weight.

My preferences are "No modifier" and "right click"

**Comment by cpriest** [comment]
Sorry I dropped the ball on this ticket.  When I said hold down alt/ctrl/shift, I meant after the drag was started.

So start the selection process, then hold down alt and lasso the links, what does it show then?

**Comment by cpriest** [comment]
Fixed in v3.1.7
