### ISSUE TITLE
Rightclick context menu on picoctf terminal doesn't work

### ISSUE THREAD

**Issue by Anutrix** [cpriest/SnapLinksPlus#251]
Rightclick context menu on [picoctf](https://2017game.picoctf.com) web terminal doesn't work when SnapLinks is enabled. 
Alternative/Quickfix: Messing around and trying to fix it I found that holding left click when right-clicking in Picoctf terminal shows its context menu even when Snaplinks is enabled. Hope this helps someone.

**Comment by cpriest** [comment]
see #253

**Comment by Anutrix** [comment]
One possible solution is that we could add an option in settings that would allow users to choose default/current behaviour or trigger rightclick regardless even if dragged.

**Comment by cpriest** [comment]
Unfortunately I think that would just lead to a lot of confused users 
since it's such an intricate situation to explain.  To someone who knows 
some JS/HTML programming it's relatively simple to say that we capture 
the mouse-down event.  To a novice though that's pretty useless.
