### ISSUE TITLE
if activation for the lasso is set to MIDDLE mouse key, the firefox shortcut for opening links in tabs (which is also MIDDLE mouse key by default) is not working anymore

### ISSUE THREAD

**Issue by tokariu** [cpriest/SnapLinksPlus#253]
I prefer to use snaplinks with the middle mouse button.
if set to MIDDLE you can draw the lasso with the middle mouse button, which works just fine.
BUT middle-button-clicking a link in firefox is also the default shortcut for opening a link in a new tab and if you want to open a link with a MIDDLE mouse button *click*, it won't work.
SnapLinks blocks the middle-click-trigger for firefox to open the link in a new tab. 

what happens? you middle-click on a link and nothing happens. if you middle-click the link, hold it and move a little, snaplinks catches the move, draws the lasso and opens the link in a new tab. (this is the workaround for now: middle click, hold it, move a bit - instead of just middle-clicking it)

what should it do?
snaplinksplus should not interfer with middle-clicking a link in firefox. snaplinksplus should just catch the event when the button gets hold + moved. that way the firefox default shortcut would work beside the snaplinksplus middle click.

**Comment by cpriest** [comment]
Unfortunately, I know of no way around this, the initial mouse-down event needs to be prevented from propagating.  I do, upon button release, if the mouse has not moved more than a certain distance fire a replacement mousedown event and then let the mouseup event occur but this is not ideal. 

If I find a way to take care of this issue I'll be sure to implement it, it's been an issue since v1 really.

**Comment by Anutrix** [comment]
One possible solution is that we could add an option in settings that would allow users to choose default/current behaviour or trigger rightclick regardless even if dragged.

**Comment by Anutrix** [comment]
Another option would be show context menu if no links are found when dragged.

**Comment by tokariu** [comment]
there seems to be a general problem with firefox quantum / WE when it's about default mouse shortcuts and addons using them too.
for instance, I use a mouse gesture addon (gesturefy / foxy gestures) with right mouse button as trigger. now when this addon is active I can't right click on html5 videos to get the context menu. I need to disable these addons or set the trigger to another mouse key. 

this problem seems to be covering more addons and that tells me the problem is deeper or conceptual on firefox' side. it's these little annoying things that still keeps me from using quantum based firefox as a main browser.

@cpriest " I do, upon button release, if the mouse has not moved more than a certain distance fire a replacement mousedown event and then let the mouseup event occur but this is not ideal."
--> if that would work, shouldn't it correctly open the link upon middle clicking it? or do you have to move a bit for the event to fire? because if I just click nothing happens.

**Comment by cpriest** [comment]
Come to think of it, I may not have updated the code when I allowed all 
buttons/modifiers on the re-fire, that may be the middle-click problem 
you're speaking of, I'll look into that.

**Comment by cpriest** [comment]
Yes, this is "on the list" as it were, I had intended to make it such
that each action could be assigned its own combination/activation
method, but things get in the way.  I don't know if it will ever get
implemented TBH without additional developers jumping on board.

**Comment by cpriest** [comment]
I'm going to post for some help w/ regards to this issue and some other similar issues, hopefully, I will find out a way to make this work properly.
