### ISSUE TITLE
Config options

### ISSUE THREAD

**Issue by rayman89** [cpriest/SnapLinksPlus#254]
Please add to the config the ability to copy links to clipboard as default action. (I know you can hold down control to copy the links to clipboard but please add the option to save time and confusion. Many times I ended with a ton of tabs opened and a ton of lag just because I forgot to press control.) Thank you.

**Comment by zephyrer** [comment]
🤝🤝🤝

**Comment by rayman89** [comment]
@cpriest any news on this? Do you plan to add it?

**Comment by cpriest** [comment]
When I can find the time to add this as a feature I do.  As sole breadwinner with two daughters, I don't have a lot of free time these days.  I really need some development help with the project to get it having any forward momentum if you know anyone.

**Comment by TheWeezel** [comment]
Well I know this is over a year old at this point but I also believe this would be an exceptionally useful feature.

**Comment by cpriest** [comment]
This actually is done I just haven't switched back to this project to actually get a release out the door.  I will try to get that done soon.

**Comment by cpriest** [comment]
This has been released in 3.1.8 (a few days ago).
