### ISSUE TITLE
Containers and switch focus to new tab not working

### ISSUE THREAD

**Issue by nebulousness** [cpriest/SnapLinksPlus#259]
After the latest update the addon ignores the option to "switch focus to new tab" and always switchs to the new tab. This only happens when using on a tab thatis in a container, non-container tabs work normally.
I've tried toggling the setting on/off and reinstalling. This is using nightly 65.0a1 and the Sticky Containers addon.

**Comment by cpriest** [comment]
I think this issue will be fixed in the next release, probably related to the new permission requirement for containers.  Please re-open if v3.1.6 doesn't take care of the problem.
