### ISSUE TITLE
Rectangle when right-clicking image

### ISSUE THREAD

**Issue by csanadm** [cpriest/SnapLinksPlus#263]
A (for me) very important feature is not working in the latest releases. In older versions, it was possible to draw a rectangle anywhere, even on a figure without mapped links. This was a great side-feature, as one could e.g. estimate coordinates of points on graphs, check the horizontal alignment of points, etc. This rectangle shows up in the current version, but not at the correct location. Let me attach a screenshot showing this behavior, where the rectangle is not appearing where the mouse is, but at the top of the browser area. It would be great if the original behavior would be brought back, where the rectangle follows the mouse.
![snaplinks_rectangle](https://user-images.githubusercontent.com/38218165/49792965-4acee580-fd34-11e8-9eb6-2bb3cc1f507b.png)

**Comment by csanadm** [comment]
Actually a very long time ago (~2016, with version 3, or when Snap Links Plus was introduced), but for some time I could revert to some older version. This just happens when loading an image in Firefox.

**Comment by cpriest** [comment]
Ok, I'll look into it when I can.
