### ISSUE TITLE
https://cpriest.github.io/SnapLinksPlus/welcome.html dead

### ISSUE THREAD

**Issue by davidhedlund** [cpriest/SnapLinksPlus#266]
SnapLinksPlus 3.1.5 opens a new tab with this dead link https://cpriest.github.io/SnapLinksPlus/welcome.html on installation.

Perhaps you want it to open https://github.com/cpriest/SnapLinksPlus/wiki instead?

**Comment by cpriest** [comment]
Thanks, I forgot to add some redirects in there for the older clients on the new website build-out.  All set now.

**Comment by davidhedlund** [comment]
Thanks.
