### ISSUE TITLE
Multiple selection for copy

### ISSUE THREAD

**Issue by Lain25** [cpriest/SnapLinksPlus#268]
Hi,
would it be possible to have a multi-copy feature for copying links to clipboard? For example while keeping pressed Alt key and drawing rectangle around links in various places of the website it would copy them to clipboard (that would also require changing default action to copy links to clipboard instead of opening those links).

**Comment by cpriest** [comment]
There isn't presently a way to change the default action, but if you start the drag and hold down shift or ctrl when you release it will copy them to the clipboard.  I don't recall the key offhand but its listed in the tutorial.
