### ISSUE TITLE
Snap Links Plus generates high CPU load on some websites

### ISSUE THREAD

**Issue by dinkumoil** [cpriest/SnapLinksPlus#269]
# Description
The _Snap Links Plus_ addon generates high CPU load (up to 25% for one of the multiple Firefox processes) on some websites, e.g. at the [startpage of the community forum of Notepad++](https://notepad-plus-plus.org/community/). This behaviour is bad especially on my notebook because it eats up its battery.

I have created a fresh user profile, installed only _Snap Links Plus_ addon, and only opened the link above. It resulted into 13% CPU load for one of the multiple Firefox processes on both systems described below. On a _VMWare_ virtual machine on System 1 configured to 4 CPU cores it was 25% CPU load.

After deactivating the addon and reloading the page with F5, CPU load fell down to a normal level.

# Applies to

## System 1
OS: Windows 7 Ultimate SP1 (64 bit)
Firefox version: 66.0.1 (64 bit)
Snap Links Plus version: 3.1.5
System: Intel Core i7-4790S @ 3.2 GHz (4 physical cores, 8 virtual cores), 16 GB RAM

## System 2
OS: Windows 10 Professional 1809 (64 bit)
Firefox version: 66.0.1 (64 bit)
Snap Links Plus version: 3.1.5
System: Intel Core i7-8550U @ 1.8 GHz (4 physical cores, 8 virtual cores), 16 GB RAM

**Comment by cpriest** [comment]
Thanks for the detailed report, I'll look into it.

**Comment by ReporterX** [comment]
The CPU surge happens in different websites. I tried a few sites like Google and Yahoo.

We don't need this addon to be always on. A quick fix might be a button to toggle the addon (enable/disable) like the legacy "Multi Links Plus" addon has.

**Comment by kulfoon** [comment]
DUPLICATE ! Because I already reporeted it here: https://github.com/cpriest/SnapLinksPlus/issues/231#issuecomment-473526421

**Comment by cpriest** [comment]
I just released 3.1.7 this morning, it's in the review queue.  If that release version doesn't fix this issue, please post a comment back here about it.

**Comment by kulfoon** [comment]
Now that the original issue has been closed a week ago, why not this trash-duplicate too?

**Comment by cpriest** [comment]
Thanks for looking through them @kulfoon, appreciate it.  @dinkumoil, if you still are experiencing this issue with 3.1.7 or higher, please comment on this ticket about it.

**Comment by dinkumoil** [comment]
@cpriest Problem solved, thank you.
