### ISSUE TITLE
Snapping links and scrolling not working

### ISSUE THREAD

**Issue by Salubritas** [cpriest/SnapLinksPlus#270]
See video:

https://youtu.be/R97SStm8DBw

Snapping links while scrolling appears to crash SnapLinks. Page reload required to get it working again. This used to work a while back, sorry I can't remember when this issue started.

Firefox 66.0.2.

**Comment by cpriest** [comment]
I tried this website just now and had no problems with scrolling, could 
only scroll the suggested videos on the right though.

Could you check the error log (Ctrl + Shift + J) and see if there's 
anything there pertaining to snap links?  Also the console log (F12) of 
the page.

It's best to open up the log windows, clear their entries, then refresh 
the page and try out SLP.

I'm not seeing any issue.

**Comment by Salubritas** [comment]
What website did you try? YouTube?

The link is to a screen capture video on YouTube showing the bug in action. The bug isn't with YouTube.

There is an error that appears in the log at the same time as the bug triggers:

TypeError: elPoint is null ElementIndexer.js:375:31

I've tested this a few times and the same error is logged each time the bug happens.

**Comment by cpriest** [comment]
Oh, my apologies, I'll check out the video.

**Comment by cpriest** [comment]
I just saw the video, thanks for that detail.  I see on the right-hand side of the video the main scroll bar and another bar that looks like a container scroll bar.  Is that one?

Is it possible for me to get to the page you are seeing this trouble on?  If not, would it be possible for you to save it as a web page (complete) and post it to this ticket?

**Comment by Salubritas** [comment]
Thanks Clint. It isn't actually a container scroll bar, it's just some page background showing, the color is very similar to the scroll bar color.

I've saved the page as HTML only and I can replicate the error with that - all script and CSS references removed. Attached here.

[snaplinks-test-page.zip](https://github.com/cpriest/SnapLinksPlus/files/3033619/snaplinks-test-page.zip)

**Comment by cpriest** [comment]
Thanks,

I'll give that a test and be sure I can reproduce it locally as well.

**Comment by Salubritas** [comment]
Were you able to reproduce locally?

**Comment by cpriest** [comment]
I have not had a chance to do so yet.

**Comment by remi-garcia** [comment]
I was not able to reproduce this bug.
