### ISSUE TITLE
Release notes link on main firefox addons page directs to a 404

### ISSUE THREAD

**Issue by pkerts** [cpriest/SnapLinksPlus#271]
Release notes link here https://addons.mozilla.org/firefox/addon/snaplinksplus/ resolves to a 404. https://github.com/cpriest/SnapLinksPlus/blob/master/ReleaseNotes.md (404). Should it point to this? https://cpriest.github.io/SnapLinksPlus/#/History

**Comment by cpriest** [comment]
Thanks for pointing that out, I've fixed that now.
