### ISSUE TITLE
Tutorial - "copy link" part: the description could be clearer

### ISSUE THREAD

**Issue by ReporterX** [cpriest/SnapLinksPlus#272]
https://cpriest.github.io/SnapLinksPlus/#/Tutorial

> Links
> 
> Google, Wikipedia
> 
>     Drag a selection around links to open them in new tab(s).
>     Hold down the control key to copy links to the clipboard.

I see a few people do not get it. They tried to hold down the control key first before dragging and failed. I see one complained that "control key to copy does not work" in the review. The instruction could be better to avoid misunderstanding.

I would suggest this re-write:

> Links
> 
> Google, Wikipedia
> 
>     To open both links in new tabs, drag a selection around links.
>     To copy both links to the clipboard, drag a selection around links, and then hold down the control key.

**Comment by cpriest** [comment]
Thanks, I'll look at modifying the tutorial page.  I'd accept a PR as well to update it.

**Comment by ReporterX** [comment]
I have no idea how to submit a PR to suggest text changes of a tutorial in this case. I'm glad to help if you point me how to do.

**Comment by cpriest** [comment]
Sure, the general idea would be:

1. Clone this repository to your account
2. Download your fork of the repository (files)
3. Make the modifications locally (in this case, to files in the docs folder)
4. Commit those changes to your local copy of the repo & push those changes back to GitHub
5. Create a pull request

Here is a good overall resource: https://www.firsttimersonly.com/

Their first link goes here: https://github.com/firstcontributions/first-contributions

Which goes over the above 5 steps in greater detail and in many languages.

Thank you for any help or attempts you make!

**Comment by ReporterX** [comment]
Great. I hope I did it right. I've submitted a pull request. Tell me if I did something wrong. Thank you.

**Comment by cpriest** [comment]
Hmm, I don't see any pull request.

**Comment by cpriest** [comment]
So looking at your fork I see it says it's 1 commit ahead, you should just need to click pull request to submit that.  It should show one commit with the diff of the file you edited.

**Comment by ReporterX** [comment]
OK thanks. I created a pull request. Check again. 

Tell me if I did something wrong. Thank you.

**Comment by cpriest** [comment]
Closed by @ReporterX with PR #275
