### ISSUE TITLE
[Feature request] Copy links in custom format

### ISSUE THREAD

**Issue by ReporterX** [cpriest/SnapLinksPlus#273]
I would like to copy both the link texts and the link urls.

For example
[Google!](http://google.com)

[Yahoo!](http://yahoo.com)

Drag and copy will produce this:
```
Google	http://google.com
Yahoo	http://yahoo.com
```
The custom format is:
`Link text<tab delimiter>Link URL`

The legacy "Multi Links Plus" has this feature.

**Comment by cpriest** [comment]
Thanks, I'll look at doing something like this.

**Comment by remi-garcia** [comment]
Either a duplicate of #198 or could be tackled by #409
