### ISSUE TITLE
Links not open in the same container

### ISSUE THREAD

**Issue by ReporterX** [cpriest/SnapLinksPlus#274]
Firefox 66.0.3 (64 bit)  
SnapLinksPlus 3.1.5

For example you are at https://www.google.com/search?q=happy in the container "Google".  
You drag a selection and open several links.  

Expected: The opened links are in the container "Google".

Actual: They are opened in the default container.

**Comment by cpriest** [comment]
There is an option for SnapLinks on FireFox under Advanced -> "Set opening tab property for new tabs."  I think that needs to be checked unless they changed the containers API or something.  I'll confirm that it still works correctly or fix it.

**Comment by ReporterX** [comment]
I don't see such an option in the SnapLinks options. Did I miss something?

**Comment by cpriest** [comment]
It's under the Advanced settings...

**Comment by ReporterX** [comment]
Are you using a newer non-public or beta version?

I have only one option in Advanced settings.

SnapLinksPlus 3.1.5

![Screenshot](https://user-images.githubusercontent.com/8235338/56076326-31cd6280-5e02-11e9-84d4-ac18acc6b27c.jpg)

**Comment by cpriest** [comment]
Strange, I must have some features that are "in the works" that I have not released yet, I have more options on my local build.  I'm going to try and put in some time tomorrow on this as the kids are away.  I'll try and get a release out which will have this.

**Comment by cpriest** [comment]
Looked into this, looks like a new permission is needed to maintain the cookieStoreId which controls the same container aspect.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create

I've added that permission to the manifest, so the next release should have this fixed.

If that doesn't take care of it, please feel free to re-open the ticket.
