### ISSUE TITLE
Enhancement request.

### ISSUE THREAD

**Issue by Joethelazy1** [cpriest/SnapLinksPlus#276]
Would it be possible to add a feature that would allow the user to add an adjustable delay between opening each link that is lasso'd? Some sites just kick back a "Too many requests" error, so you just have to go back and reload those pages manually. This would make your program that much more valuable. Also, if you lasso a whole bunch of links and the site has no request limitations, anybody else that is using the same internet connection suffers a big loss of speed until all the links are opened from the lasso. Just a thought or two.

Thanks, and your program is really helpful already!

**Comment by cpriest** [comment]
Thanks for the request, it has already been implemented in the soon to be released v3.1.6, see #114 for details.

-Clint
