### ISSUE TITLE
Some links fail to be selected

### ISSUE THREAD

**Issue by Anutrix** [cpriest/SnapLinksPlus#279]
Some links when right click and dragged are not detected as links and are hence not selected. Happened on many sites. Even release notes page had the issue. Pics as proof.
![Screenshot (26)](https://user-images.githubusercontent.com/11459028/56918009-8e0ad480-6ada-11e9-8857-a95a3ca9f4e3.png)
Each version numbers are links but are not selected. If I don't select the release notes, all version number links work. It's as if "Release Notes" link and the version number links are in different layers of website and can't be selected at same time.

**Comment by cpriest** [comment]
Snap Links has a feature that selects links based on font size, as detailed in our [Tutorial](https://cpriest.github.io/SnapLinksPlus/#/Tutorial).  This is a feature that can be disabled permanently in preferences, or while you are dragging (by holding down alt).

![image](https://user-images.githubusercontent.com/159323/56959525-405e8e00-6b13-11e9-9805-1f26e1ceebc8.png)

Image was taken while holding down alt.
