### ISSUE TITLE
Adds unwanted code to web content when editing page

### ISSUE THREAD

**Issue by TomatoJoe** [cpriest/SnapLinksPlus#281]
When saving content to our website,  SnapLinks adds code at bottom upon each save! 
```
<div class="SnapLinksContainer" style="margin-left: 0px; margin-top: 0px; display: none;"><!-- Used for easily cloning the properly namespaced rect --></div>
<div class="SnapLinksContainer" style="margin-left: 0px; margin-top: 0px; display: none;">
<div class="SL_SelectionRect">
<div class="SL_SelectionLabel" style="right: 2px; bottom: 2px;">0 Links</div>
</div>
<!-- Used for easily cloning the properly namespaced rect --></div>
<div class="SnapLinksContainer" style="margin-left: 0px; margin-top: 0px; display: none;"><!-- Used for easily cloning the properly namespaced rect --></div>
<div class="SnapLinksContainer" style="margin-left: 0px; margin-top: 0px; display: none;"><!-- Used for easily cloning the properly namespaced rect --></div>
<div class="SnapLinksContainer" style="margin-left: 0px; margin-top: 0px; display: none;"><!-- Used for easily cloning the properly namespaced rect --></div>
<div class="SnapLinksContainer" style="margin-left: 0px; margin-top: 0px; display: none;"><!-- Used for easily cloning the properly namespaced rect --></div>
<div class="SnapLinksContainer" style="margin-left: 0px; margin-top: 0px; display: none;">
<div class="SL_SelectionRect">
<div class="SL_SelectionLabel" style="right: 2px; bottom: 2px;">0 Links</div>
</div>
<!-- Used for easily cloning the properly namespaced rect --></div>
```
How to disable this,  undesirable code? Currently need to disable addon.

**Comment by cpriest** [comment]
It needs this markup to render elements on the page.  It only adds them on first use I believe so at the moment your options are to not use the addon when you intend to save the page or disable the addon.

**Comment by TomatoJoe** [comment]
1. The example code shows that the lines are added multiple times. probably on each save.
2. I dont see the relevance of these divs in pages I am creating, I dont want any addon dumping code into my pages. The addon is used for opening multiple links, nothing to do with the content my pages.
3. Yes, of couse I've disabled the addon as a workaround, but when has disabling an addon ever been a fix for a problem, or a valid solution to trigger closing a report?

**Comment by remi-garcia** [comment]
What do you mean: when saving content to our website? How can I reproduce it?

The fact that an addon write some code on pages is totally understandable. Maybe once is enough and the issue here is really the multiple writings

**Comment by cpriest** [comment]
Ahh, I missed that part, my apologies.  I'll look into that.  I can probably have it put into a document fragment just as easily as well.

**Comment by TomatoJoe** [comment]
> The fact that an addon write some code on pages is totally understandable.  ...
You have got to be kidding me !!!

**Comment by TomatoJoe** [comment]
We need to disable the addon and only enable when needed. An addon the must be disabled most of the time is less than acceptable.

**Comment by cpriest** [comment]
I'm wondering if the latest 3.1.7 release has already fixed this?  I thought I had confirmed this before but I am not seeing the behavior any more (on my regular HTML test page).

To be clear, it is adding (and leaving) two root elements, one is <STYLE> in the HEAD tag, the other is the DIV.SnapLinksContainer which is added (once) and remains after use.

1. Is the original issue (multiple root elements being added) still present?
     If so, please post a link to some page where this is happening.
2. If not, is there still an issue here?  Are you requesting that no elements are left in the document in between uses?

**Comment by TomatoJoe** [comment]
Obviously the issue is that is adds code. Not that it adds multiple lines but that it adds code at all! . Injecting code to user pages is unethical and is a security issue, I haven't tested the latest version as yet.

**Comment by TomatoJoe** [comment]
Hmmm. It seems that you completely misunderstand the issue.

**Comment by TomatoJoe** [comment]
We disable this add-on because of this issue. Adding code to html edited is not within the expected functionality nor purpose of this add-on. Users will lose confidence in a product that appears malicious even if it is not.
