### ISSUE TITLE
Snapping links still doesn't work with Reddit Modmail

### ISSUE THREAD

**Issue by jrmio** [cpriest/SnapLinksPlus#283]
I've made some changes that may take care of these problems, please check in the next release and let me know if there are further problems.

_Originally posted by @cpriest in https://github.com/cpriest/SnapLinksPlus/issues/222#issuecomment-447702128_

Hi Clint, I wanted to let you know that the issue is still there with the latest update. I thought of new screenshots or links to add but I didn't find any, so feel free to ask for anything that could help. If you don't have an account yet, you can still view the issue even without [logging in](https://github.com/cpriest/SnapLinksPlus/issues/222#issuecomment-373965632) btw.

**Comment by cpriest** [comment]
Closing this as I re-opened #222
