### ISSUE TITLE
High CPU impact on many polish sites (WP Group)

### ISSUE THREAD

**Issue by kulmegil** [cpriest/SnapLinksPlus#284]
WP group is a major player in polish internet. 
Except it's main news portal ([wp.pl](https://wp.pl/)) it controls a bit of other domains, like:

[open.fm](https://open.fm/) - many online radio stations
[dobreprogramy.pl](https://www.dobreprogramy.pl/) - software portal + news
[eholiday.pl](https://www.eholiday.pl/), [nocowanie.pl](https://www.nocowanie.pl/), [nocowanie.pl](https://www.nocowanie.pl/) - travel sites
[domodi.pl](https://domodi.pl/), [allani.pl](https://allani.pl/) - lifestyle
[direct.money.pl](https://direct.money.pl/),  [totalmoney.pl](https://totalmoney.pl/) - finance
[superauto24.com](https://superauto24.com/)- automotive
[homebook.pl](https://www.homebook.pl/), [extradom.pl](https://www.extradom.pl/) - interior/home design
[full list](https://onas.wp.pl/naszemarki.html)

All of them suffers High CPU impact (about:performance) and fast memory leaks - as soon as user with enabled Snap Links extension visits site. Active using SnapLinks is not required.

**Comment by kulmegil** [comment]
ups, looks like it has already reported [#231 (comment)](https://github.com/cpriest/SnapLinksPlus/issues/231#issuecomment-473526421)

**Comment by cpriest** [comment]
Thanks, yes the current 3.1.6 release has some speed issues at startup, the next 3.1.7 release due out very soon should be much faster.  If it is still causing problems, please go ahead and post another comment here or in #231.

**Comment by cpriest** [comment]
I just released 3.1.7 this morning, it's in the review queue.
