### ISSUE TITLE
[Feature request] Filter links by url or text content?

### ISSUE THREAD

**Issue by xlucn** [cpriest/SnapLinksPlus#286]
Current we can filter the links by font. I think it would be better if we can just select the links of which the url or text match certain pattern (maybe regex).
I need this because I want to download some torrent files in a webpage, but the buttons are in the same column with other links, e.g. categories, bookmark. So if I want to select multiple torrent links, I would be also selecting the same amount of the other links. This is when filtering by url/text comes in handy.

**Comment by cpriest** [comment]
I can put this on the list of requested features but to be honest this is probably never going to happen, given the time I have to work on the project.

One alternative might be for you to use Stylish and create your own CSS stylesheet for the site in question, making the links you're interested in bold(er).

**Comment by OliverLew** [comment]
The workaround seems a good idea, I will try it.

**Comment by xlucn** [comment]
I am not using this addon anymore. And it seems nobody else is interested in this feature, so I am closing it. (I am cleaning up all my opened issues)
