### ISSUE TITLE
[Feature request] Do not open release notes tab on every update

### ISSUE THREAD

**Issue by abulgatz** [cpriest/SnapLinksPlus#287]
Please do not open release notes tab on every update. It is annoying to have my browser randomly hijacked.

Otherwise, SnapLinks is amazing!

**Comment by cpriest** [comment]
Would you rather have this as an option to be unchecked or a browser notification that it was updated?

**Comment by remi-garcia** [comment]
An option would be nice

**Comment by abulgatz** [comment]
Optional but off by default.

**Comment by NatoBoram** [comment]
A browser notification is less intrusive and gets to the point better than interrupting someone's browsing after an update like https://github.com/projectdelphai/panorama-tab-groups/issues/116.
