### ISSUE TITLE
When I right-click to select links, page autmatically jumps to the bottom of the page with no links selected

### ISSUE THREAD

**Issue by cuntard** [cpriest/SnapLinksPlus#288]
It only happens on one site, www.bricklink.com.  for example, at this url: https://www.bricklink.com/catalogItemInv.asp?S=75175-1&viewItemType=M I want to select the three links directly to the left of the pictures of the minifigures (sw0818, sw0820, sw0819).  When I right click, the site jumps to the very bottom of the page without selecting any links.

**Comment by cpriest** [comment]
Hmm, I'll check into it.  I can definitely see it happening.  Probably something wrong with the HTML or something though.

**Comment by remi-garcia** [comment]
When I right click with SnapLinks activated I have this CSS error in Console:
`Error in parsing value for ‘height’.  Declaration dropped.`

This website gives me 120 Warnings and a bunch of CSS errors even without SnapLinks...

**Comment by cpriest** [comment]
Okay, many of these one-off site issues are because the website is designed poorly.  These can be quite tough problems to solve sometimes.  The document height calculations that SL3 currently uses is based on scrollHeight which, typically is the most accurate.
