### ISSUE TITLE
Feature request: copy links to clipboard

### ISSUE THREAD

**Issue by rapisho** [cpriest/SnapLinksPlus#289]
Hello folks,

I just wanted to ask for a feature that shouldnt be that complicated to implement but would be very usefull. In prior addon with similar functionality in old firefox versions you could decide weather to open links in new tabs or simply copy URLs to clipboard by using different hotkeys.

So what Im asking for is the possibilety to decide weather you want to open links in new tabs or copy the adresses, for example as in prior addon by using different hotkeys.

Thanks in advance, thx for this amazing addon and keep up the good work.

Regards,
Rapisho

**Comment by remi-garcia** [comment]
This is already implemented. Press CTRL before releasing the clic.
ALT allows you to ignore "filtering".

**Comment by cpriest** [comment]
Thanks @remi-garcia
