### ISSUE TITLE
it puts the square wherever it wants once i middle click..

### ISSUE THREAD

**Issue by xlovinglyx** [cpriest/SnapLinksPlus#290]
bug:

https://www.collarspace.com/Default.asp?bhfv=3&bhfx=32.0%20r0&bhsh=800&bhsw=1280&bhtz=9&bhqs=1  < tried it here for ex..

middle click in the middle of that vertical list, & a square pops covering the whole list,
needless to tell u i can't narrow my selections..

& still missing javascript links detection ?

**Comment by remi-garcia** [comment]
Can you precise that the link is **NSFW**?

**Comment by cpriest** [comment]
Unfortunately, this is because the website is built incorrectly, this is identical to #288.
