### ISSUE TITLE
Dev tabs and spaces

### ISSUE THREAD

**Issue by remi-garcia** [cpriest/SnapLinksPlus#297]
Is that an option to change all tabs for spaces?

Edit: asking because I just realized that I might be breaking your indentation :/

**Comment by cpriest** [comment]
Yeah, should be using tabs.  There is an .editorconfig file that should have those settings in them.  Are you using Visual Studio Code?  There is a plugin there to utilize the editorconfig file settings.

**Comment by remi-garcia** [comment]
I was pretty sure Visual Studio Code was for Windows only. I'll try it soon for SL3 then

**Comment by cpriest** [comment]
Nope, works on all platforms. I use PhpStorm, but WebStorm would be more appropriate. I think there are community editions as well.
