### ISSUE TITLE
Regression after 3.1.5

### ISSUE THREAD

**Issue by Quaraxkad** [cpriest/SnapLinksPlus#302]
In versions later than 3.1.5, when I draw a SnapLinks box with my keys set to Alt+Left Click: text and page content is highlighted as if I were drag-selecting text. This does not happen in 3.1.5 or prior.

**Comment by remi-garcia** [comment]
Can you precise your web browser and OS? (version)
Then I'll try to reproduce it.
Did you try it with no other extensions?

Thank you for your feedback

**Comment by cpriest** [comment]
I have confirmed this is the case, I don't think anything changed on my end but I have not tested extensively with left click.  I'll look into it.

This also happens with Ctrl + Left Click as well.

**Comment by Quaraxkad** [comment]
Firefox 63.0.3 (64-bit), Win 7. I didn't try without other extensions, but I did remove and install every version available [here](https://addons.mozilla.org/en-US/firefox/addon/snaplinksplus/versions/). Only 3.1.6 and 3.1.7 exhibit this behavior.

**Comment by remi-garcia** [comment]
Ok, that might be because I'm on Linux that I can't reproduce this. I'll try on Windows to see if I can understand what is happening.

**Comment by Quaraxkad** [comment]
SnapLinks 3.1.5 seems to no longer work in recent versions of Firefox, so I have had to upgrade. However this bug still exists in the latest 3.1.7.

**Comment by cpriest** [comment]
This is related to #308.  In Firefox, holding down the alt key while selecting something will let you select, even if you start selecting in the middle of a link.  This is a Firefox feature that I do not believe can be worked around.

**Comment by Quaraxkad** [comment]
Alt+Left does still work properly in 3.1.5 *without* highlighting any text, so there must have been something changed between 3.1.5 and 3.1.6.

**Comment by cpriest** [comment]
Indeed, I found this issue and have fixed it, will be working correctly in the next release.

**Comment by Quaraxkad** [comment]
Awesome, thanks!
