### ISSUE TITLE
Change strict_min_version from 50.0 to 53.0

### ISSUE THREAD

**Issue by davidhedlund** [cpriest/SnapLinksPlus#304]
https://addons.mozilla.org/en-US/firefox/addon/snaplinksplus/versions/  says that SLP 3.1.7 "Works with firefox 50.0 and later, android 50.0 and later".

However, I cannot use SLP 3.1.7 (I had to downgrade to SLP 3.1.6.) with:
* [Firefox 50.0 (64-bit) for GNU/Linux](https://ftp.mozilla.org/pub/firefox/releases/50.0/linux-x86_64/en-US/firefox-50.0.tar.bz2)
* [Firefox ESR 52.9.0 (64-bit) for GNU/Linux](https://ftp.mozilla.org/pub/firefox/releases/52.9.0esr/linux-x86_64/en-US/firefox-52.9.0esr.tar.bz2)

SLP 3.1.7 can be used with:
* [Firefox 53.0 (64-bit) for GNU/Linux](https://ftp.mozilla.org/pub/firefox/releases/53.0/linux-x86_64/en-US/firefox-53.0.tar.bz2)

Todo
* Can you please update strict_min_version from 50.0 to 53.0 in [manifest.json](https://github.com/cpriest/SnapLinksPlus/blob/master/src/templates/manifest.hbs)? Here's my [patch](https://github.com/cpriest/SnapLinksPlus/compare/master...davidhedlund:patch-1).
* Modify strict_min_version in 3.1.7 and re-upload it to addons.mozilla.org to make the current version display "Works with firefox 53.0 and later, android 53.0 and later" at https://addons.mozilla.org/en-US/firefox/addon/snaplinksplus/versions/

~~I cannot use SLP 3.1.7 ("Works with firefox 50.0 and later, android 50.0 and later") with IceCat (based on Firefox ESR) 52.3.0 (64-bit) for GNU/Linux. I tested this in a brand new profile and disabled all other add-ons.~~

**Comment by remi-garcia** [comment]
I've no problem with IceCat 60.7.0esr (64-bit). I'll try 52.3.0 too.

**Comment by davidhedlund** [comment]
> I've no problem with IceCat 60.7.0esr (64-bit). I'll try 52.3.0 too.
> 
> Edit: I can reproduce the issue with IceCat 52.3.0 (64-bit) on Ubuntu 18.04.3

Thanks, but this appears to be a Firefox ESR issue.

**Comment by remi-garcia** [comment]
I think we might need to change that `Works with firefox 50.0 and later, android 50.0 and later` for something newer. 

[This](https://github.com/cpriest/SnapLinksPlus/compare/v3.1.6...v3.1.7) might help to understand what have changed since SLP 3.1.6. For now I can't look into it but I will as soon as possible. Thanks for the issue.

**Comment by remi-garcia** [comment]
What might help too is to know what is the oldest Firefox version working with SLP 3.1.7. We might use a feature available since this version in SLP 3.1.7.

**Comment by davidhedlund** [comment]
@cpriest @remi-garcia I updated the issue, please read the top post.

**Comment by remi-garcia** [comment]
Thank you for your help solving this.

In your edits you modified 50 with 53:
> https://addons.mozilla.org/en-US/firefox/addon/snaplinksplus/versions/ says that SLP 3.1.7 "Works with firefox 53.0 and later, android 53.0 and later".

**Comment by davidhedlund** [comment]
> In your edits you modified 50 with 53:
> 
> > https://addons.mozilla.org/en-US/firefox/addon/snaplinksplus/versions/ says that SLP 3.1.7 "Works with firefox 53.0 and later, android 53.0 and later".

Oh, I corrected this, it was just a typo. Thanks

**Comment by davidhedlund** [comment]
https://github.com/cpriest/SnapLinksPlus/compare/master...davidhedlund:patch-1

**Comment by davidhedlund** [comment]
@cpriest Thanks for the commit. There's one more thing on the todo right?: Re-upload version 3.1.7 to addons.mozilla.org to make the current version display "Works with firefox 53.0 and later, android 53.0 and later" at https://addons.mozilla.org/en-US/firefox/addon/snaplinksplus/versions/
