### ISSUE TITLE
Page scrolling not working on mouse screen end

### ISSUE THREAD

**Issue by alexgarciab** [cpriest/SnapLinksPlus#305]
So if I try to select multiple links to be opened at once, the page scrolling is not working, as the mouse moves down. In order for the page to scroll, I need to use the trackpad to move the screen down. It is not ideally to keep holding the click on the trackpad while scrolling down with it at the same time. I guess that scrolling the page automatically when the mouse arrives to the end of the page/screen would be a better way of dealing with it (LinkClump actually works this way).

**Comment by cpriest** [comment]
This is already a feature, I just tested it.  You need to drag the rectangle off the edge of the document/window for it to activate.
