### ISSUE TITLE
dont work FF 70

### ISSUE THREAD

**Issue by Mrakobes666** [cpriest/SnapLinksPlus#306]
when highlighted with a rectangle, it writes 0 links

**Comment by cpriest** [comment]
I'm on FF 72 and it's working just fine, do you have any more details?

URL with the problem, a screenshot of the problem?  Any errors in the Ctrl+J console related to SnapLinks?

**Comment by Mrakobes666** [comment]
[img]https://i111.fastpic.ru/big/2019/1229/45/_6570541724cc4910e36effca6878b345.png[/img]
[url=https://i111.fastpic.ru/big/2019/1229/45/_6570541724cc4910e36effca6878b345.png][img]https://i111.fastpic.ru/thumb/2019/1229/45/_6570541724cc4910e36effca6878b345.jpeg[/img][/url]

+

[img]https://i111.fastpic.ru/big/2019/1229/53/d35cdb146805a05c799044354a121c53.png[/img]
[url=https://i111.fastpic.ru/big/2019/1229/53/d35cdb146805a05c799044354a121c53.png][img]https://i111.fastpic.ru/thumb/2019/1229/53/d35cdb146805a05c799044354a121c53.jpeg[/img][/url]

**Comment by Mrakobes666** [comment]
some horizontal stripes on the screen

**Comment by cpriest** [comment]
Do you have a URL for that page or can you save the web page as an archive and post it here? (You can attach files to this ticket).

Looks to me like they're using some non-standard HTML or something.

**Comment by Mrakobes666** [comment]
https://www.last.fm/ru/music/Insomnium/+images

it doesn’t work for me on any other (((

How to log an error?

**Comment by cpriest** [comment]
![image](https://user-images.githubusercontent.com/159323/71561585-1234a380-2a3e-11ea-8304-54d35612ae0f.png)

Works fine for me, there must be some other add-on you have installed that is conflicting with it.  

Try changing your activation setting (like to ctrl + right click) or try disabling some other add-ons to see which one is conflicting.

**Comment by Mrakobes666** [comment]
I believe you, I tried modifiers, it does not help, there was a suspicion that it is in conflict with something, blocking Java eg

really everything will have to turn off...????

**Comment by Mrakobes666** [comment]
Gesturefy

found! there is a temporary shutdown modifier control, and I set your control as a control, one turned on the other, turned it off and it worked !, thanks, sorry
