### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by pegship** [cpriest/SnapLinksPlus#307]
I'm using Firefox 72.0.1 on macOS 10.15.2 (Catalina), on a new MacBook Pro. I installed this add-on, but when I try to "draw a rectangle" with the right mouse button, the mouse selects a group of links as if I'm just highlighting them. When I release the mouse button, no new tabs or windows appear. As the add-on version was updated in July, perhaps some tweaking is in order to make it work with the latest Firefox. Please advise. pegship@sbcglobal.net

**Comment by cpriest** [comment]
I'm guessing that you have a conflict with another program or that some permission was not accepted.  I'm using it just fine in FF 73 Dev Edition.

You might try another page (like google search results), check that the number of links shown at the bottom right of the selection rectangle shows a number of links.

If another page doesn't work, try disabling some other extensions.  I know people have said Gesturify has been a problem in the past.

**Comment by pegship** [comment]
Aha! As it turns out, it was my "Magic Mouse" that was the issue. I had to set it to "right-click" in order to select a group of links. I had tried it with my touchpad to no avail, but now that I configured the mouse accordingly, Snap Links works a charm. Thanks for your patience. P

**Comment by cpriest** [comment]
No Problem. :)
    [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/cpriest/SnapLinksPlus/issues/307?email_source=notifications\u0026email_token=AABG4W3OQCKW4RX2R6CFGH3Q5SX3PA5CNFSM4KFUCM52YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIZZPNI#issuecomment-573806517",
"url": "https://github.com/cpriest/SnapLinksPlus/issues/307?email_source=notifications\u0026email_token=AABG4W3OQCKW4RX2R6CFGH3Q5SX3PA5CNFSM4KFUCM52YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIZZPNI#issuecomment-573806517",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
