### ISSUE TITLE
Snaplinks acting wierd on a particular page https://godotengine.org/article/gdscript-progress-report-writing-tokenizer

### ISSUE THREAD

**Issue by Anutrix** [cpriest/SnapLinksPlus#311]
Right-click dragging on https://godotengine.org/article/gdscript-progress-report-writing-tokenizer causes this weird behaviour. I will contact the page author too.
![godotsite-snaplinks3](https://user-images.githubusercontent.com/11459028/80998236-35de7f00-8e60-11ea-9a0d-c765d07b5221.gif)

Latest SnapLinks 3.1.7 on Firefox 75.0.

**Comment by remi-garcia** [comment]
I can't reproduce this. Can you give a list of the add-ons that you use? I'll try again then.

**Comment by cpriest** [comment]
I could not reproduce this either.  It would seem from your animated gif (thank you!) that snap links is getting into a weird state.  It looks like it's in that state from the start of your animation.

**Comment by Anutrix** [comment]
It seems that I can't reproduce it either now. It seems that some part of Firefox or its cache for that page was in some weird state. Sry about this.
