### ISSUE TITLE
For android users, tutorial touchpad

### ISSUE THREAD

**Issue by bobbely** [cpriest/SnapLinksPlus#312]
I could instal it i just dont know programing really, or if this works touchscreen or get a mouse app. Side note Im having, screen whatever that word is before i git this app gotta fix that, where its off center touch.

**Comment by remi-garcia** [comment]
Can you give more info on your system? Android X.X? Using Firefox app?

**Comment by cpriest** [comment]
I don't believe snap links would work with a touch interface at this time.  It *might* work if you set it to left-click, then regular touch & drag your finger.

**Comment by remi-garcia** [comment]
Closing this in favor of #310 
For now we could mention somewhere that despite leaving the possibility to install SLP3 on Android we have no guarantee that it can work properly.
