### ISSUE TITLE
How to disable synchronized settings? Or have one for trackpad and another for mouse.

### ISSUE THREAD

**Issue by rsalmei** [cpriest/SnapLinksPlus#313]
Hello man,

I have a macbook, where I configure snap links to Alt modifier and Left Click on the trackpad. This week I needed it in my desktop, where I have a mouse and configured as just Right Click (no modifier).
How could I disable or prevent settings from being synced?

Or, another alternative, would be support for trackpads and mouses differently. If someday I plug a mouse into my macbook, I'd be happy to just drag with Right Click...

**Comment by rsalmei** [comment]
Hey @remi-garcia, could you please take a look at this one too?
I just want to use this differently where I have a mouse and where I only have a trackpad.
But unfortunately the config is synced between them, and I always have to change again to match the one I'm using.

**Comment by remi-garcia** [comment]
That's probably beyond my capabilities but I'll take a look.

**Comment by remi-garcia** [comment]
After some research I think I can tell that there is no good solution. Roughly, your Trackpad/Touchpad and a mouse are both handled the same way by Javascript (there exists [events](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events) dedicated to Trackpads).

What we can do is, as you suggested, prevent settings from being synced. Locally I think it can be done by setting to false `extensions.webextensions.ExtensionStorageIDB.migrated.snaplinks@snaplinks.mozdev.org` in `about:config`. However I'm not sure it will work as I don't use Firefox Sync.

As far as I understood we have everything ready for adding this feature in Preferences but I cannot test it and @cpriest expertise is needed on that. I'll open a PR for further discussion.

**Comment by cpriest** [comment]
The ability to use local or sync storage will be available in the next release.
