### ISSUE TITLE
Bug: Lassoed links don't open when an activation modifier is used.

### ISSUE THREAD

**Issue by McBobb** [cpriest/SnapLinksPlus#319]
I recently got a new addon that I really needed, but it uses the right mouse button to activate, and using it causes Snaplinks to activate as well, opening up copies of the current tab when used.

I looked at the Snaplinks options, and saw that there was the ability to add a modifier to press to activate it, so I added one. I tried using all the modifier options, but while the green lasso was produced and usable, lassoing links did not cause them to open in tabs like it did when no modifier was used.

I'm using Snaplinks 3.1.7
Firefox 84.0.2 64bit
WIn 10 Home (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0
Windows_NT 10.0 19041

Other Info:

Add-ons
-------

Name: British English Dictionary (Marco Pinto)
Type: dictionary
Version: 2.92
Enabled: true
ID: marcoagpinto@mail.telepac.pt

Name: Canadian English Dictionary
Type: dictionary
Version: 3.1.2
Enabled: true
ID: en-CA@dictionaries.addons.mozilla.org

Name: AdBlocker for YouTube™
Type: extension
Version: 0.3.3
Enabled: true
ID: jid1-q4sG8pYhq8KGHs@jetpack

Name: AddToAny: Share Anywhere
Type: extension
Version: 3.4.1
Enabled: true
ID: {35d49e56-0142-4a7b-82a8-6ace7d28ff92}

Name: AdNauseam
Type: extension
Version: 3.9.201
Enabled: true
ID: adnauseam@rednoise.org

Name: Advanced Downloader for Instagram™
Type: extension
Version: 1.1
Enabled: true
ID: {9b11086c-a4ef-4a17-8cf5-ec412c2550ed}

Name: Amazon.co.uk
Type: extension
Version: 1.3
Enabled: true
ID: amazon@search.mozilla.org

Name: Ant Video downloader
Type: extension
Version: 4.7
Enabled: true
ID: anttoolbar@ant.com

Name: Bing
Type: extension
Version: 1.2
Enabled: true
ID: bing@search.mozilla.org

Name: BlockSite - Stay Focused & Control Your Time
Type: extension
Version: 4.5.0.1
Enabled: true
ID: {dd3d7613-0246-469d-bc65-2a3cc1668adc}

Name: Bookmark Tab Here
Type: extension
Version: 1.0
Enabled: true
ID: {bc21b9a1-3ad6-4b00-bca4-ef5b7e21253b}

Name: Bookmark Tabs to the Right
Type: extension
Version: 1.3
Enabled: true
ID: {ff6861bf-c02f-4da5-94a2-476a2152ad3e}

Name: Bookmarks Organizer
Type: extension
Version: 3.1.0
Enabled: true
ID: bookmarksorganizer@agenedia.com

Name: Clear Site Cookies
Type: extension
Version: 1.2
Enabled: true
ID: clearsitecookie@mhillsystem.com

Name: Code Injector
Type: extension
Version: 0.3.2
Enabled: true
ID: {b12a78ef-3319-45fa-800e-a7efa56b6da4}

Name: Country Flags & IP Whois
Type: extension
Version: 0.3.8
Enabled: true
ID: {802a552e-13d1-4683-a40a-1e5325fba4bb}

Name: Dark Background and Light Text
Type: extension
Version: 0.7.4
Enabled: true
ID: jid1-QoFqdK4qzUfGWQ@jetpack

Name: Dark Reader
Type: extension
Version: 4.9.26
Enabled: true
ID: addon@darkreader.org

Name: Delete History
Type: extension
Version: 2.3
Enabled: true
ID: history-delete@dsrini-open.github.com

Name: DeviantArt Filter
Type: extension
Version: 6.1.1
Enabled: true
ID: {a2ce7c11-e47d-42cf-b6db-ede36265cf6c}

Name: Disconnect
Type: extension
Version: 20.3.1.1
Enabled: true
ID: 2.0@disconnect.me

Name: Don't Fuck With Paste
Type: extension
Version: 2.7
Enabled: true
ID: DontFuckWithPaste@raim.ist

Name: Download IG Video/Photo (for Instagram)
Type: extension
Version: 1.0.7
Enabled: true
ID: {dc736b00-bf31-4daf-910a-51f95054ae62}

Name: Download instagram images/video
Type: extension
Version: 3.7
Enabled: true
ID: {c998715d-acd9-41dd-8e61-841a2477d748}

Name: Download Manager (S3)
Type: extension
Version: 5.12
Enabled: true
ID: s3download@statusbar

Name: Download with Free Download Manager (FDM)
Type: extension
Version: 0.2.0
Enabled: true
ID: {1fb1ffdc-b95d-451e-be52-7303adf9a0d3}

Name: Downloader for Instagram™
Type: extension
Version: 1.0.4
Enabled: true
ID: {83bdc210-e037-4d76-8889-2e127ecc06c7}

Name: DownThemAll!
Type: extension
Version: 4.2.6
Enabled: true
ID: {DDC359D1-844A-42a7-9AA1-88A850A938A8}

Name: DuckDuckGo
Type: extension
Version: 1.1
Enabled: true
ID: ddg@search.mozilla.org

Name: Easy Youtube Video Downloader Express
Type: extension
Version: 16.8
Enabled: true
ID: {b9acf540-acba-11e1-8ccb-001fd0e08bd4}

Name: easyGestures N
Type: extension
Version: 6.5
Enabled: true
ID: easyGesturesN@ngdeleito.eu

Name: eBay
Type: extension
Version: 1.2
Enabled: true
ID: ebay@search.mozilla.org

Name: Element Blocker
Type: extension
Version: 1.5
Enabled: true
ID: element-blocker@lukepeters.me

Name: Element-Hider
Type: extension
Version: 1.1
Enabled: true
ID: {402b80e2-c899-4152-9814-f17cd6c753af}

Name: Empty Cache Button
Type: extension
Version: 3.4
Enabled: true
ID: {4cc4a13b-94a6-7568-370d-5f9de54a9c7f}

Name: Enhancer for YouTube™
Type: extension
Version: 2.0.101
Enabled: true
ID: enhancerforyoutube@maximerf.addons.mozilla.org

Name: Find & Replace for Text Editing
Type: extension
Version: 1.3.17
Enabled: true
ID: {ad1a1412-512a-4955-8bea-3ac63a5d970b}

Name: Firefox Multi-Account Containers
Type: extension
Version: 7.0.2
Enabled: true
ID: @testpilot-containers

Name: Fixed Zoom
Type: extension
Version: 2.1.5
Enabled: true
ID: {a655a6b2-69a5-40de-a3b8-3f7f200c95a7}

Name: Flash Player
Type: extension
Version: 1.1.9
Enabled: true
ID: {87e997f4-ae0e-42e6-a780-ff73977188c5}

Name: FoxReplace
Type: extension
Version: 2.3.2
Enabled: true
ID: fox@replace.fx

Name: FoxyTab
Type: extension
Version: 2.15
Enabled: true
ID: foxytab@eros.man

Name: Free Download Manager
Type: extension
Version: 3.0.52
Enabled: true
ID: fdm_ffext2@freedownloadmanager.org

Name: Go to Top of Page Button
Type: extension
Version: 1.3
Enabled: true
ID: top-page-single@codefisher.org

Name: Google
Type: extension
Version: 1.1
Enabled: true
ID: google@search.mozilla.org

Name: Grammar and Spell Checker — LanguageTool
Type: extension
Version: 3.2.3
Enabled: true
ID: languagetool-webextension@languagetool.org

Name: Greasemonkey
Type: extension
Version: 4.10.0
Enabled: true
ID: {e4a8a97b-f2ed-450b-b12d-ee082ba24781}

Name: Happy Right-Click
Type: extension
Version: 1.1.0
Enabled: true
ID: {dd10d63e-3096-4492-ab0e-5edcf4baf988}

Name: Hide Fixed Elements
Type: extension
Version: 1.2
Enabled: true
ID: hidefixedelements@commonground.systems

Name: Honey
Type: extension
Version: 12.4.5
Enabled: true
ID: jid1-93CWPmRbVPjRQA@jetpack

Name: Image Download for Instagram
Type: extension
Version: 1.0.0
Enabled: true
ID: image_download_for_instagra@image_download_for_instagra.org

Name: Image Zoomer
Type: extension
Version: 1.1
Enabled: true
ID: {ef6f09da-955d-45db-b9c4-b174adba0b15}

Name: image-resizer
Type: extension
Version: 1.7.2c
Enabled: true
ID: jid0-hd39BGK3EuIbK47rGW3fZdR163o@jetpack

Name: ImTranslator: Translator, Dictionary, TTS
Type: extension
Version: 15.74
Enabled: true
ID: {9AA46F4F-4DC7-4c06-97AF-5035170634FE}

Name: insta-download
Type: extension
Version: 2.1
Enabled: true
ID: {7b21dc78-ddbd-44c8-8621-161bb293598d}

Name: Insta-guest
Type: extension
Version: 1.4
Enabled: true
ID: {8e6822de-d72f-4284-9400-1164ee39b07d}

Name: Instagram Downloader
Type: extension
Version: 4.2.1
Enabled: true
ID: HuiiBuh.InstagramDownloader@github.com

Name: Instagram Photo and Video Downloader
Type: extension
Version: 1.0
Enabled: true
ID: @instagramdownloader

Name: Instagram Photo Plus
Type: extension
Version: 2.8.0
Enabled: true
ID: {feb6c5e7-41e5-4da1-a08f-5e3b73055be2}

Name: Instagram Unlock
Type: extension
Version: 0.0.1
Enabled: true
ID: {ee60cf91-27cd-4d0b-9c06-093612ecce9c}

Name: Kee - Password Manager
Type: extension
Version: 3.6.27
Enabled: true
ID: keefox@chris.tomlinson

Name: Lenz Image Downloader
Type: extension
Version: 0.1.2
Enabled: true
ID: {d9a74bd4-3c76-47d1-81fe-59bfad2ec86c}

Name: Media Helper
Type: extension
Version: 1.17.1
Enabled: true
ID: {85603edc-044f-4391-9a95-a94682f449b4}

Name: Media Panel
Type: extension
Version: 2.6
Enabled: true
ID: {68d048f4-9449-4c97-8425-6dac7f743b14}

Name: Merge Windows
Type: extension
Version: 1.0
Enabled: true
ID: {07532c74-a5e9-491b-82d6-e55bc0e03d67}

Name: MeWe+
Type: extension
Version: 1.4
Enabled: true
ID: {e6ca51c3-628e-4b17-bad6-50bd3c8a0a2f}

Name: Nuke Anything
Type: extension
Version: 2.4
Enabled: true
ID: {1ced4832-f06e-413f-aa14-9eb63ad40ace}

Name: Official Media Bias Fact Check Icon
Type: extension
Version: 1.7.1
Enabled: true
ID: {6ba00d80-d8f3-4e1a-bc70-e1b6c64ae4a0}

Name: OneTab
Type: extension
Version: 1.39
Enabled: true
ID: extension@one-tab.com

Name: Open Frame
Type: extension
Version: 7
Enabled: true
ID: {c853c31a-d96d-4394-bff3-da25ba9ab8b9}

Name: Open in Chrome
Type: extension
Version: 0.2.7
Enabled: true
ID: {086f665e-6a55-4107-9147-f9a14e72b137}

Name: Open Links in Tabs
Type: extension
Version: 1.0.6
Enabled: true
ID: open.links.in.tabs@gmail.com

Name: Open Not in New Tab
Type: extension
Version: 1.1.1
Enabled: true
ID: openinsametab@filewo.net

Name: Open Page in Private Window
Type: extension
Version: 1.2.1
Enabled: true
ID: open-page-in-private-window@cpeterso.com

Name: Px Downloader
Type: extension
Version: 3.5.0
Enabled: true
ID: {a3650a89-273e-474b-9e32-46ba5397cf46}

Name: Reload Tabs Button
Type: extension
Version: 1.3
Enabled: true
ID: reload-all-tabs-single@codefisher.org

Name: Restart Browser
Type: extension
Version: 1.2
Enabled: true
ID: Restartfirefox@vazextension.com

Name: Rotate and Zoom Image
Type: extension
Version: 1.5
Enabled: true
ID: rotate-and-zoom-image@mikk.cz

Name: Search by Image
Type: extension
Version: 3.4.3
Enabled: true
ID: {2e5ff8c8-32fe-46d0-9fc8-6b8986621f3c}

Name: Show/Hide passwords
Type: extension
Version: 0.4
Enabled: true
ID: shpassword@shpassword.fr

Name: Simple Tab Groups
Type: extension
Version: 4.7
Enabled: true
ID: simple-tab-groups@drive4ik

Name: Smart Tab Mute
Type: extension
Version: 1.0.1.1
Enabled: true
ID: smart-tab-mute@die-antwort.eu

Name: Snap Links
Type: extension
Version: 3.1.7
Enabled: true
ID: snaplinks@snaplinks.mozdev.org

Name: Stylus
Type: extension
Version: 1.5.13
Enabled: true
ID: {7a7a4a92-a2a0-41d1-9fd7-1e92480d612d}

Name: Tabby - Window and Tab Manager
Type: extension
Version: 2.1.1
Enabled: true
ID: tabby@whatsyouridea.com

Name: Text Link
Type: extension
Version: 6.1.1
Enabled: true
ID: {54BB9F3F-07E5-486c-9B39-C7398B99391C}

Name: Textarea Cache
Type: extension
Version: 4.2.1
Enabled: true
ID: textarea-cache-lite@wildsky.cc

Name: The Pirate Bay Torrent Search
Type: extension
Version: 0.1.8
Enabled: true
ID: {682b93a2-cb50-4363-8682-334b590efd71}

Name: Tile Pages WE
Type: extension
Version: 3.11
Enabled: true
ID: tilepages-we@DW-dev

Name: Tree Style Tab
Type: extension
Version: 3.6.5
Enabled: true
ID: treestyletab@piro.sakura.ne.jp

Name: Turbo Download Manager (3rd edition)
Type: extension
Version: 0.6.4
Enabled: true
ID: jid0-dsq67mf5kjjhiiju2dfb6kk8dfw@jetpack

Name: Undo Closed Tabs Menu
Type: extension
Version: 2.0
Enabled: true
ID: tst-closed_tabs_menu@dontpokebadgers.com

Name: Video Downloader Pro
Type: extension
Version: 1.4.0
Enabled: true
ID: @video_downloader_pro

Name: Video DownloadHelper
Type: extension
Version: 7.4.0
Enabled: true
ID: {b9db16a4-6edc-47ec-a1f4-b86292ed211d}

Name: Web Developer
Type: extension
Version: 2.0.5
Enabled: true
ID: {c45c406e-ab73-11d8-be73-000a95be3b12}

Name: Wikipedia (en)
Type: extension
Version: 1.1
Enabled: true
ID: wikipedia@search.mozilla.org

Name: YouTube Video and Audio Downloader (Dev Edt.)
Type: extension
Version: 1.1.3
Enabled: true
ID: {f73df109-8fb4-453e-8373-f59e61ca4da3}

Name: YouTube Video Downloader/YouTube HD Download
Type: extension
Version: 1.1.21
Enabled: true
ID: youtubedownloader@youtubedownloadvideo1clickgroup.com

Name: YouTube™ No Buffer (Stop Auto-playing)
Type: extension
Version: 0.3.2
Enabled: true
ID: {551f032e-353d-4d10-b186-b0026b1a666d}

Name: Zoom Page WE
Type: extension
Version: 17.12
Enabled: true
ID: zoompage-we@DW-dev

Experimental Features
---------------------

about:home startup cache (browser.startup.homepage.abouthome_cache.enabled): false
Cookies: SameSite=Lax by default (network.cookie.sameSite.laxByDefault): false
Cookies: SameSite=None requires secure attribute (network.cookie.sameSite.noneRequiresSecure): false
Cookies: Schemeful SameSite (network.cookie.sameSite.schemeful): false
CSS: Constructable Stylesheets (layout.css.constructable-stylesheets.enabled): false
CSS: Pseudo-class: :focus-visible (layout.css.focus-visible.enabled): false
CSS: Masonry Layout (layout.css.grid-template-masonry-value.enabled): false
Developer Tools: Colour Scheme Simulation (devtools.inspector.color-scheme-simulation.enabled): false
Developer Tools: Compatibility Panel (devtools.inspector.compatibility.enabled): false
Developer Tools: Execution Context Selector (devtools.webconsole.input.context): false
Developer Tools: Service Worker debugging (devtools.debugger.features.windowless-service-workers): false
Fission (Site Isolation) (fission.autostart): false
JavaScript JIT: Warp (javascript.options.warp): true
Media: AVIF (image.avif.enabled): false
Multiple Picture-in-Picture Support (media.videocontrols.picture-in-picture.allow-multiple): false
Print Preview Redesign (print.tab_modal.enabled): true
Web API: beforeinput Event (dom.input_events.beforeinput.enabled): false
Web API: inputmode (dom.forms.inputmode): false
Web API: <link rel="preload"> (network.preload): true
Web API: WebGPU (dom.webgpu.enabled): false
WebRTC Global Mute Toggles (privacy.webrtc.globalMuteToggles): false

Important Modified Preferences
------------------------------

accessibility.browsewithcaret: true
accessibility.browsewithcaret_shortcut.enabled: false
accessibility.force_disabled: 1
accessibility.typeaheadfind.flashBar: 0
browser.cache.disk.amount_written: 2092493
browser.cache.disk.capacity: 1048576
browser.cache.disk.filesystem_reported: 1
browser.cache.disk.hashstats_reported: 1
browser.cache.disk.smart_size.first_run: false
browser.cache.disk.smart_size.use_old_max: false
browser.cache.disk.telemetry_report_ID: 104
browser.cache.frecency_experiment: 4
browser.contentblocking.category: custom
browser.display.document_color_use: 1
browser.display.show_loading_image_placeholder: true
browser.display.use_system_colors: true
browser.download.folderList: 2
browser.download.useDownloadDir: false
browser.link.open_newwindow.override.external: 3
browser.link.open_newwindow.restriction: 0
browser.places.smartBookmarksVersion: 8
browser.search.openintab: true
browser.search.region: CA
browser.sessionstore.upgradeBackup.latestBuildID: 20210105180113
browser.startup.homepage: http://ca.my.msn.com/
browser.startup.homepage_override.buildID: 20210105180113
browser.startup.homepage_override.mstone: 84.0.2
browser.startup.page: 3
browser.tabs.closeWindowWithLastTab: false
browser.tabs.drawInTitlebar: false
browser.tabs.loadBookmarksInBackground: true
browser.tabs.remote.autostart: false
browser.tabs.remote.autostart.2: false
browser.urlbar.lastSuggestionsPromptDate: 20170831
browser.urlbar.matchBuckets: general:5,suggestion:Infinity
browser.urlbar.placeholderName: Google
browser.urlbar.placeholderName.private: Google
browser.urlbar.suggest.openpage: false
browser.urlbar.timesBeforeHidingSuggestionsHint: 0
browser.urlbar.tipShownCount.tabToSearch: 2
browser.zoom.siteSpecific: false
doh-rollout.balrog-migration-done: true
doh-rollout.disable-heuristics: true
doh-rollout.doneFirstRun: true
doh-rollout.doorhanger-decision: UIOk
dom.ipc.processCount: 2
dom.ipc.processCount.web: 4
dom.popup_allowed_events: change click dblclick mouseup pointerup notificationclick reset submit touchend
dom.push.userAgentID: 9b6a5513801a41e69f630a9aff85637a
dom.security.https_only_mode_ever_enabled: true
extensions.formautofill.addresses.usage.hasEntry: false
extensions.lastAppVersion: 84.0.2
font.internaluseonly.changed: false
font.language.group: x-armn
font.minimum-size.x-armn: 30
font.minimum-size.x-western: 14
font.name.serif.x-armn: Futura
font.size.fixed.x-western: 20
font.size.monospace.x-armn: 30
font.size.variable.x-armn: 44
font.size.variable.x-western: 26
general.autoScroll: false
gfx.crash-guard.d3d11layers.appVersion: 56.0
gfx.crash-guard.d3d11layers.deviceID: 0x00ba
gfx.crash-guard.d3d11layers.driverVersion: 10.0.17763.1
gfx.crash-guard.d3d11layers.feature-d2d: false
gfx.crash-guard.d3d11layers.feature-d3d11: false
gfx.crash-guard.d3d11video.appVersion: 67.0.2
gfx.crash-guard.d3d11video.deviceID: 0x1c82
gfx.crash-guard.d3d11video.driverVersion: 25.21.14.1891
gfx.crash-guard.status.d3d11layers: 2
gfx.crash-guard.status.d3d11video: 2
gfx.crash-guard.status.d3d9video: 2
gfx.crash-guard.status.wmfvpxvideo: 3
gfx.crash-guard.wmfvpxvideo.appVersion: 84.0.2
gfx.crash-guard.wmfvpxvideo.deviceID: 0x1c82
gfx.crash-guard.wmfvpxvideo.driverVersion: 27.21.14.5730
idle.lastDailyNotification: 1611201282
layers.acceleration.disabled: true
layers.mlgpu.sanity-test-failed: true
media.autoplay.enabled: false
media.benchmark.vp9.fps: 199
media.benchmark.vp9.versioncheck: 5
media.gmp-gmpopenh264.abi: x86_64-msvc-x64
media.gmp-gmpopenh264.lastUpdate: 1573587463
media.gmp-gmpopenh264.version: 1.8.1.1
media.gmp-manager.buildID: 20210105180113
media.gmp-manager.lastCheck: 1611198324
media.gmp-widevinecdm.abi: x86_64-msvc-x64
media.gmp-widevinecdm.lastUpdate: 1581522554
media.gmp-widevinecdm.version: 4.10.1582.2
media.gmp.storage.version.observed: 1
media.hardware-video-decoding.failed: false
media.videocontrols.picture-in-picture.video-toggle.enabled: false
network.cookie.cookieBehavior: 0
network.cookie.prefsMigrated: true
network.dns.disableIPv6: true
network.dns.disablePrefetch: true
network.http.pipelining: true
network.http.pipelining.maxrequests: 35
network.http.proxy.pipelining: true
network.http.speculative-parallel-limit: 0
network.predictor.cleaned-up: true
network.predictor.enabled: false
network.prefetch-next: false
network.trr.blocklist_cleanup_done: true
network.trr.mode: 5
places.database.lastMaintenance: 1611114883
places.history.expiration.transient_current_max_pages: 123073
plugin.disable_full_page_plugin_for_types: application/pdf
plugin.flash.lastmod_hi: 374
plugin.flash.lastmod_lo: 1174945026
plugin.state.flash: 2
plugins.ctprollout.cohort: user-changed-from-test
plugins.ctprollout.cohortSample: 0.074979
plugins.flashBlock.enabled: false
privacy.cpd.cookies: false
privacy.cpd.formdata: false
privacy.cpd.offlineApps: true
privacy.cpd.sessions: false
privacy.history.custom: true
privacy.purge_trackers.date_in_cookie_database: 0
privacy.sanitize.pending: [{"id":"newtab-container","itemsToClear":[],"options":{}}]
privacy.sanitize.timeSpan: 0
privacy.socialtracking.notification.counter: 1
privacy.socialtracking.notification.enabled: false
privacy.socialtracking.notification.lastShown: 1573630584747
privacy.userContext.enabled: true
privacy.userContext.extension: simple-tab-groups@drive4ik
privacy.userContext.longPressBehavior: 2
privacy.userContext.ui.enabled: true
security.default_personal_cert: Select Automatically
security.disable_button.openCertManager: false
security.disable_button.openDeviceManager: false
security.remote_settings.crlite_filters.checked: 1611281113
security.remote_settings.intermediates.checked: 1611281113
security.sandbox.content.tempDirSuffix: {ce7f09d9-5f4c-4095-8030-8e27d23b73f1}
security.sandbox.plugin.tempDirSuffix: {1a8b5f25-b83b-4873-8e0e-d2153f22a6b1}
security.ssl.enable_ocsp_stapling: false
security.ssl.errorReporting.automatic: true
services.sync.declinedEngines:
services.sync.engine.creditcards: true
services.sync.engine.prefs.modified: false
services.sync.lastPing: 1611198663
services.sync.lastSync: Thu Jan 21 2021 21:55:33 GMT-0500 (Eastern Standard Time)
signon.importedFromSqlite: true
signon.rememberSignons: false
signon.usage.hasEntry: true
storage.vacuum.last.index: 1
storage.vacuum.last.places.sqlite: 1610858401
svg.context-properties.content.enabled: true
ui.osk.debug.keyboardDisplayReason: IKPOS: Touch screen not found.
ui.osk.enabled: false

Important Locked Preferences
----------------------------

fission.autostart: false
fission.autostart.session: false

**Comment by cpriest** [comment]
This is possibly related to #317, have you tried holding down the modifiers the entire time, including when you release the mouse button?

**Comment by McBobb** [comment]
Yes. It still doesn't work. It creates the green lasso, and enumerates the number of links lassoed as intended, but that's all it does. Even holding the modifier down for some time after releasing the mouse button doesn't cause the links to open in tabs.

**Comment by cpriest** [comment]
Are you getting any errors in the error log?  Either F12 or the browser error log (Ctrl + Shift + J) related to SnapLinks?

**Comment by McBobb** [comment]
This is what I got in the consule when I tried using CTRL as a modifier, or any combination including CTRL

contentscript.js: https://hotfub.forum2go.nl/viewtopic.php?f=100013&t=8019&view=unread#unread <empty string> contentscript.js:24:9
Some cookies are misusing the recommended “SameSite“ attribute 4
Loading mixed (insecure) display content “http://cdn-thumbs.imagevenue.com/6d/a8/88/ME1202RO_t.jpg” on a secure page
2 viewtopic.php
<script> source URI is not allowed in this document: “https://www.googletagmanager.com/gtag/js?id=UA-1416385-4”. viewtopic.php:47:1
<script> source URI is not allowed in this document: “https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js”. viewtopic.php:292:1
<script> source URI is not allowed in this document: “https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js”. viewtopic.php:300:1
<script> source URI is not allowed in this document: “https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js”. viewtopic.php:528:1
Uncaught ReferenceError: lightbox is not defined
    <anonymous> https://hotfub.forum2go.nl/viewtopic.php?f=100013&t=8019&view=unread#unread:1809
viewtopic.php:1809:2
* port already set to: page

And under Errors:

contentscript.js: https://hotfub.forum2go.nl/viewtopic.php?f=100013&t=8019&view=unread#unread <empty string> contentscript.js:24:9


And these from the error tab of the Broswer Error Log

REMOVE CACHED eyJhbGciOiJSUzI1NiIsInR5cCI6ImF0K0pXVCIsImtpZCI6IjIwMTkwNzMwLTU0ZmY5NTZlIn0.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmZpcmVmb3guY29tIiwiYXVkIjoiaHR0cHM6Ly90b2tlbi5zZXJ2aWNlcy5tb3ppbGxhLmNvbSIsImNsaWVudF9pZCI6IjU4ODIzODZjNmQ4MDE3NzYiLCJleHAiOjE2MTE1ODk0ODYsImlhdCI6MTYxMTU2Nzg4NiwianRpIjoiN2VmNzJmM2FhYTVkMjBkZmExNWRlODViMjU1ZTQ2MzVmNzRhZWYxZmVhMzUxNDg5YzA5NmYwODFlZjM0NTY3YyIsInNjb3BlIjoiaHR0cHM6Ly9pZGVudGl0eS5tb3ppbGxhLmNvbS9hcHBzL29sZHN5bmMiLCJzdWIiOiI3YzFlZGQ1YjBlNzA0Yzc1YjA5ZjM5MmJlN2IwZjNlNSIsImZ4YS1nZW5lcmF0aW9uIjoxNTc5MDExMjMyNDUyLCJmeGEtcHJvZmlsZUNoYW5nZWRBdCI6MTU3OTAxMTIzMjQ1Mn0.YTt6RgtPEH0PpnTPuTHH8xKf9s6sMIrzLbBguZy_GGhANv-djJBtVGZojLQusWq7URnywIJzdAk2PtajJyvWQT9YfCZs6FwEnz3-z3cSIVOM6gR7T2bde4ojiZCf1eSRbuPLDnfDfQ7-POlM7UpTgAgVOSims_I8rf6_GAf1LO4xCAV55yY6sNMnUOsPk22cMLpSxoy3R5ycz5-y9-UvkRbwJvFew5FOoMTGplGUTQzzaWrEBj8umHd6cN7r2pJ7Mhpv4KsxSKErGySxBxiWg4-JhTm1QlNi_UzzHsYBn1FafN0ugYaHrQD5wjn8ngrdEEc7bi_ULwR9173pJo4nSQ browserid_identity.js:511:19
Use of nsIFile in content process is deprecated. 50 NetUtil.jsm:253:8
Use of nsIFile in content process is deprecated. 49 NetUtil.jsm:253:8
Use of nsIFile in content process is deprecated. 4 NetUtil.jsm:253:8
debuggee 'resource://devtools/shared/base-loader.js:289' would run

Shift and Alt+Shift work as modifiers, too, but anything with CRTL in it creates the green lasso and enumerates the links, but doesn't open anything.

I've forgotten how to make and use a new profile for Firefox, unfortunately

**Comment by cpriest** [comment]
Hmm, can you try it on another website?  Do you by chance have popups turned off?

None of those errors are related to SnapLinks.

**Comment by cpriest** [comment]
Assuming this is no longer an issue.
