### ISSUE TITLE
Icon won't show in toolbar

### ISSUE THREAD

**Issue by Stefan-B-Martens** [cpriest/SnapLinksPlus#323]
Icon is also not available in 'Customize...'
FF 85.0.2. (64 bit)

**Comment by cpriest** [comment]
Snap Links provides no additional toolbar icons besides the main plugin icon.  That plugin icon will only show on the main toolbar areas or in the 'overflow menu.'

In customize... mode you can move the snap links icon to wherever FF allows you to.
