### ISSUE TITLE
Copy links doesnt work anymore

### ISSUE THREAD

**Issue by lurkmaster12** [cpriest/SnapLinksPlus#324]
When copying links with ctrl, the links arent copied and the following error shows up in the console:

document.execCommand('cut'/'copy') was denied because it was not called from inside a short running user-generated event handler.

Granted, I have the following pref set to false in about:config: dom.allow_cut_copy, but I believe it used to work before?

**Comment by cpriest** [comment]
Hmm, have you tried changing the pref back?  It could be that there are new permission requirements that SL+ is not up to snuff with.  It hasn't been updated in a long time.

Please see if its your particular pref setting though to be sure.

**Comment by lurkmaster12** [comment]
It is the pref, it does work when I change it back, but it is a hardening pref that is pretty common from what I gather. I think standard clipboard practice may have changed. 
https://stackoverflow.com/questions/41094318/firefox-document-execcommand-cut-copy-was-denied-because-it-was-not-calle
It probably is a permission thing. Would be nice if it was fixed, really useful function.

**Comment by cpriest** [comment]
Yeah, looks like they tightened up the permissions further.

**Comment by cpriest** [comment]
I'll be working on this for the next release 3.1.9.
