### ISSUE TITLE
[Feature request] Possible to use mouse trail to mark and open links?

### ISSUE THREAD

**Issue by Johsnon** [cpriest/SnapLinksPlus#326]
Hi,
I was wondering if - instead of a rectangle - you could also use your **mouse to "draw a trail"** over the links on a page you want to open...

That would provide another flexible way of getting (only) the links you want to open.

**Comment by cpriest** [comment]
Do you mean something like a lasso tool from a graphics program?  I'm open to contributions, but it's not likely I'll ever write such a feature.

**Comment by Johsnon** [comment]
A lasso has same start and stop position, right? No I don't mean that.
Just a freestyle mouse gesture of sorts, and all the links that get covered under the trail will be opened (once I release the mouse button)

**Comment by remi-garcia** [comment]
Do you have a specific case in mind for which that option would be better than a rectangle or multiple middle clicks?

Roughly, adding this option would mean to override the whole rectangle computation and only open links with a "mouseover" option. It should not be too hard but IMHO this enhancement has a low priority.

**Comment by Johsnon** [comment]
hm, I guess it depends on the site... but I don't have a solid example that can't be solved otherwise 😅

**Comment by remi-garcia** [comment]
Closed in favor of #329
