### ISSUE TITLE
Sometimes activates itself without me doing anything

### ISSUE THREAD

**Issue by dvorapa** [cpriest/SnapLinksPlus#330]
Sometimes it activates itself without me doing anything. And opens huge amount of links I didn't wanted. I teached myself to hit escape key every time it show up, but it is not convenient

**Comment by cpriest** [comment]
Is your computer sluggish at all or have stalls?  

What happens if you use a more difficult to activate combination, such as ctrl/shift left/right click?

**Comment by dvorapa** [comment]
_Is your computer sluggish at all or have stalls?_

No, pretty quick: not low end not high end, just in the middle. Never had problems with it being slow or something.

_What happens if you use a more difficult to activate combination, such as ctrl/shift left/right click?_

My all time favourite Ctrl + left click from Linkclump Chrome extension does not work at all in SnapLinksPlus on Firefox. Other shortcuts are not much convenient.

It happens once in a few days, but is really annoying. Competing extension to SnapLinksPlus called Tabrador does not have this issue, but it can not scroll down during mouse drag action, which makes SnapLinksPlus win some points.

**Comment by remi-garcia** [comment]
I already experimented that, but not that often. Can you check on your CPU consumption when that occurs? I will try to check it myself if that happened again.

**Comment by dvorapa** [comment]
Okay, I'll try it next time

**Comment by cpriest** [comment]
Yeah, this is the first this type of thing
      has been reported and the extension has been in the wild for quite
      some time.  This is why I suspect its something locally to your
      install.
      
      Like, as an example, if the activation event occurrs and your
      computer gets busy and you let the combination go technically at
      the right spot but due to the busyness of the computer and the
      completion event comes back with different parameters (because its
      processed by some part of the busy computer late), then I could
      see something like this happening.

**Comment by dvorapa** [comment]
> I already experimented that, but not that often. Can you check on your CPU consumption when that occurs? I will try to check it myself if that happened again.
Sorry for the delay, here it is, it seems there is no direct link between CPU consumption and when the issue happens.
![Snímek obrazovky pořízený 2021-11-13 21-48-49](https://user-images.githubusercontent.com/5113916/141658683-970fec6c-ab39-4fd9-b41f-f628f9af2c19.png)

**Comment by dvorapa** [comment]
> Yeah, this is the first this type of thing has been reported and the extension has been in the wild for quite some time.  This is why I suspect its something locally to your install. Like, as an example, if the activation event occurrs and your computer gets busy and you let the combination go technically at the right spot but due to the busyness of the computer and the completion event comes back with different parameters (because its processed by some part of the busy computer late), then I could see something like this happening.

It should not be something locally on my install as this happens also on my other computer, which is Windows 10 (the screenshot is from Linux, where it is easier to check actual CPU/RAM consumption)

**Comment by cpriest** [comment]
Hmm, I've never seen this happen and I only use right click drag.  

You use Ctrl + Left Click?  

Could you try using Alt + Left Click or Ctrl + Alt + Left Click?

Do you use any software that messes with the keyboard like AutoHotKey or some other key remapping software?  Windows, at least, probably others as well have a Physical and Logical state for each key, some programs can mess with the logical state of a key and with the modifier keys they can be logically down but not physically.

If this happens in Linux as well as Windows then the previous paragraph probably isn't the cause.  I would wonder if it's possibly hardware.

That being said, I'll switch mine to Ctrl + Left Click for a while and see if I find any issues with that.

**Comment by cpriest** [comment]
Speaking of which, do you use the normal ctrl+left click action of firefox?  It opens a link in a new window.  I just tried it and SL does not appear to be interfering with that.

Linux/Firefox does handle mouse events differently, at least with right-click, Linux/Firefox tries to launch the context menu on the right-click down event, other o/s's do this on the mouse up event.

Can you tell me if Linux/Firefox activates on a left-click-down for an ordinary link or does it activate when you let go of the left-click?

**Comment by dvorapa** [comment]
I use right drag for extension and yes, I use Left Ctrl + left click browser shortcut a lot. On Windows I use Autohotkey to check for Left Ctrl + U + code, but not on Linux. I'll try to switch to Left Ctrl + left drag for a while (I used to use this combo in Chrome's Linkclump extension before I switched to Firefox). I'll also deactivate both other extensions I use for a while.

**Comment by dvorapa** [comment]
Left Ctrl + Left Alt + left drag combo has got one caveat that I have to release keys first and then release mouse to make it work.

**Comment by cpriest** [comment]
Wait, it should always do that no matter the combination on Windows or Linux.

**Comment by dvorapa** [comment]
> Left Ctrl + Left Alt + left drag combo has got one caveat that I have to release keys first and then release mouse to make it work.

If you release mouse and keys simultaneously, then you have 50 % possibility that you are successful, either your computer recognizes mouse released few miliseconds later than keys, then SLP opens marked links, or your computer recognizes mouse released few miliseconds earlier than keys, then SLP does nothing (drag action being canceled, like hitting Esc).

**Comment by cpriest** [comment]
no need to let go of the keys before the mouse, always release the mouse first.

**Comment by dvorapa** [comment]
> no need to let go of the keys before the mouse, always release the mouse first.

Doesn't work

**Comment by cpriest** [comment]
oh duh, of course.  Because the modifier keys also affect what it chooses to do if held down when released.

Sorry I had this backward, they should only be held down to start the drag operations, then let them go and just use the mouse, release when ready.
