### ISSUE TITLE
[Feature request] Better new tabs positioning

### ISSUE THREAD

**Issue by raqua** [cpriest/SnapLinksPlus#332]
Hi. At first, this is great extension, thank you!

I have suggestion that will improve it for me an hopefully others as well. 
At the moment I have option to open new tabs to the left of current tab or at the end of the queue. I would like to have some kind of mix of these two approaches. 
Consider this example:
I have 1 tab open and then open 3 tabs from this tab. Then I open another 3 tabs still staying in the first tab. Then I move to the second tab and open 3 links from that one. 

Case1: 
If I have setting to open tabs at the end enabled then:
- Links opened from first tab are behaving as expected, so the tabs are added at the end
- Links opened from the second tab are also added to the end, but that is imho not correct (at least for me) and I would like to open them to the right of the tab I opened them from.

Case 2:
If I have setting to open tabs at the end disabled then:
- Links opened from first tab are NOT behaving as expected, because the second batch of links is positioned in front of the first batch I have opened. 
- Links opened from the second tab are positioned as I expect them, to the right of the second tab.

Proposed solution: 
Always add links opened from the same tab to the right of the tab, but keep the order they are opened in.
In my example:
- Links opened from the first tab are opened to the right of current tab, but the second batch is added behind the first batch.
- After moving to the second tab, do not open links at the end of the overall tab list but add them to the right of the current tab. If there are multiple batches of links open from the same tab, they should be added at the end of the queue of tabs opened FROM THE SAME TAB.

I hope that it is clear from my description and thank you for considering this.

**Comment by remi-garcia** [comment]
I'll come back with some html to illustrate your request. I think I understood it and I agree that the behavior you ask for would be great. It is how middle click works (at least with Firefox).

I think SLP would need access to some kind of "memory". If that's the case I'm not sure we want to add permissions to the add-on. Wait on @cpriest opinion on this.

In any case I won't have time to develop this enhancement for now. However, feel free to open a PR for that, I'll happily help you through it.

**Comment by cpriest** [comment]
Actually, this isn't exactly how Firefox handles middle-click.  I was just testing it myself.  It opens new middle-click tabs to the end of the "current tab stack."

So 1st MC opens to the right of current tab
2nd MC opens after that
3rd MC opens after that

But, if you switch tabs, it resets.  Going back to the original tab (with the 3 MC opened tabs) and open another one via middle click, it opens to the right of the current tab.

SLP could implement this either way, it would just have to store a reference to the tab it last opened (per tab).  They would need to be weak references and handle the expected window no longer existing falling back to something (perhaps same as no "last tab opened").

**Comment by raqua** [comment]
Either way would be ok for me @cpriest @remi-garcia. I don't really care what happens when I switch back to some tab. 99% of my browsing with this extension would be that I close the original tab and move to the next one. I just want to keep the relative order I opened the tabs from current tab. 
Thank you again.

**Comment by cpriest** [comment]
Can you tell me if the latest release has fixed this issue?  There was some code submitted a while back that would have affected tab opening order.

**Comment by raqua** [comment]
@cpriest I have tested only case1 as that is what I use for now and it still behaves the old way as described in my initial post.

**Comment by cpriest** [comment]
@raqua Is this with the new v3.1.8 that was released?

**Comment by raqua** [comment]
@cpriest Yes.

**Comment by cpriest** [comment]
I'm going to take a stab at fixing this for the next release, which I was about to go do until I saw you responded. :)

**Comment by cpriest** [comment]
3.1.9 should be approved very soon, there is a new option to open tabs the same way firefox does which I believe takes care of this.
