### ISSUE TITLE
about:addons link broken

### ISSUE THREAD

**Issue by akerbeltz** [cpriest/SnapLinksPlus#336]
In Firefox when I visit the about:addons about SnapLinksPlus the project link given is
https://cpriest.github.com/SnapLinksPlus
but this leads to error 404. It should be updated to 
https://github.com/cpriest/SnapLinksPlus

**Comment by cpriest** [comment]
Thanks, actually they need to be changed to cpriest.github.io.

Thanks for the heads up though!

**Comment by akerbeltz** [comment]
You're welcome
