### ISSUE TITLE
Right-click malfunction under a spoofed user agent environment

### ISSUE THREAD

**Issue by haoshu** [cpriest/SnapLinksPlus#34]
Hi,

Problem Summary: Have to right click twice to popup the native context menu, when the firefox user agent is spoofed as Linux and choose SnapLinksPlus Start Selection With Right Button.

Environment: Windows 8 & Firefox 26.2 ESR

Steps to Reproduce:
1. install user agent spoofer, e.g. random-agent-spoofer
    https://addons.mozilla.org/en-US/firefox/addon/random-agent-spoofer/
2. fix the spoofed user agent as Linux
3. open SnapLinksPlus options and choose Start Selection With Right Button, then save
4. visit whatever web page
5. hit left click once in the content area and then a right click
     -> the context menu won't show
6. hit the right click again
     -> the context menu shows after the 2nd right click
7. repeat step 5-6 to reproduce the flip-flop situation
By the way, SnapLinksPlus drag to select works as design.

Reproducible: Always

Possible Cause:
Found codes shown below in snaplinks.js to detect the platform and use as a flag to sink the mouse event later.
        if(e.button == 2 /\* RMB */ && this.ChromeWindow.navigator.userAgent.indexOf('Linux') != -1) {
            this.StoppingNextContextMenuPopup = true;

Since navigator.userAgent might report a fake value and is no reliable, you might want to use nsIXULRuntime instead.
https://developer.mozilla.org/docs/XPCOM_Interface_Reference/nsIXULRuntime

Thanks!

**Comment by cpriest** [comment]
This might be the oldest open ticket, but it relates to XPCOM which is no longer around, closing.
