### ISSUE TITLE
Won't pull images from cache.

### ISSUE THREAD

**Issue by Joethelazy1** [cpriest/SnapLinksPlus#345]
Hello,
Great extension first of all! It has saved me countless hours over time in my work, almost custom made for it, so I appreciate your time.
 I'm having an issue in which I can't get Image Picka to save images from cache. I do have the option checked in the config page, but after opening each image in it's own tab, which means it's already downloaded, when I click save the extension re-downloads all the images again.
 I did an experiment where I cleared the total cache in Firefox and opened the empty folder. When I open each image in it's own tab, I can see the entry entered in the cache folder. When I click save, Image Picka re-downloads the pictures and adds it's own entry in the cache. If I leave the tabs open and click save again the the process happens almost immediately, so then I know that it obviously is saving the image from cache at that point. It's almost like there's a naming difference in which Image Picka can't recognize that the image entries in the cache file are the same entries that it is looking to save. Then, after you run save once and it re-downloads the pictures and creates it's own entries in the cache file, if you run save again it CAN recognize the entries and it pulls the images from cache in practically no time. It's possible I have a setting wrong or something, but I can't figure it out. Can you please help with this? I'm updated to the latest versions of both the extension and Firefox as of this writing.
Thank you.

**Comment by cpriest** [comment]
This definitely wouldn't be anything that SnapLinks is causing.  All it does is open a new tab to the link(s) you selected.

What could be the case is that the image that is being shown is different than the image the link is pointing at.

As an example:
```html
<a href="image_full.jpg"><img src="image_thumbnail.jpg"></a>
```

In the above example, the image that is downloaded on the source page is the `image_thumbnail.jpg` while the link is opening to the file `image_full.jpg`.

**Comment by Joethelazy1** [comment]
Okay, and I appreciate the quick reply. I just wanted to make sure that because it was opened in SnapLinks there wasn’t a different naming convention or something like that. I have the same question submitted to Image Picka. You helped greatly on your end and I do appreciate it.

**Comment by cpriest** [comment]
My pleasure.
