### ISSUE TITLE
Hiding a box makes visible links unclickable

### ISSUE THREAD

**Issue by kruuve** [cpriest/SnapLinksPlus#348]
Thanks for creating this great extension that I've been using for a long time! But now I've ran into a problem that seems to have appeared after the last update (3.1.8).

 I'm using Snap Links Plus (3.1.8) for Firefox 91.0.1 (64-bit), and sometimes the extension fails to recognize all links; here's an example where this happens:
https://en.wikipedia.org/wiki/Special:RecentChanges

It seems to occur when the "List of abbreviations" box is hidden (see the screenshots below).
![snaplinkissue1](https://user-images.githubusercontent.com/89306764/130324278-d4a9c230-a0e0-4b57-bfc8-7fd9aafa516d.png)
![snaplinkissue2](https://user-images.githubusercontent.com/89306764/130324282-12694045-adaa-4bed-9771-237706f443d3.png)

**Comment by cpriest** [comment]
Hmm, the show/hide is a red herring.  This happens even without clicking on that if you resize the web page. 

I'll look into this and get it fixed.
