### ISSUE TITLE
HTML checkboxes don't work

### ISSUE THREAD

**Issue by leodoi3** [cpriest/SnapLinksPlus#352]
On pages like this , the checkboxes / radiobuttons don't get recognized. 
Example: https://usproducttesting.com/

![image](https://user-images.githubusercontent.com/46114199/131263636-9abedf2c-9d85-4b13-9cd1-04e5f0f0c107.png)

**Comment by cpriest** [comment]
I'm not seeing those checkboxes that you have in your screenshot, but I can tell you they are not standard checkboxes or radio buttons, they are custom controls that the website has created; Snap Links cannot detect these custom situations unfortunately.
