### ISSUE TITLE
Links aren't opened anymore

### ISSUE THREAD

**Issue by maggotb** [cpriest/SnapLinksPlus#356]
Hello, since the last update links aren't opened anymore. I use the latest Firefox version. 

Here is a [screen](https://i.imgur.com/VjuQw6Q.png) of the options

Select+ctrl works.

I tried reinstalling the extension it didn't fix it

**Comment by cpriest** [comment]
You're right, I confirmed it, though I don't know why yet.  I'll try and have a hotfix out today for it.  I would suggest switching back to 3.1.8 in the meantime.

**Comment by cpriest** [comment]
I've reverted the published version to 3.1.8.  

Version 3.1.10 has been published and is awaiting approval by Mozilla.  Sorry about that!

**Comment by cpriest** [comment]
Unfortunately 3.1.10 also has other issues and it has now also been disabled, so 3.1.8 is the version that should be available on Mozilla and the one to go with.
