### ISSUE TITLE
'Switch focus to new tab' can't turn off.

### ISSUE THREAD

**Issue by pulbitz** [cpriest/SnapLinksPlus#358]
Snap Links 3.1.10 'Switch focus to new tab' always.
I can't off it.

**Comment by vodzl** [comment]
Yes, same for me since 3.1.9 release. Latest FF and TOR.
Switching storage settings are also cannot be saved although i am not sure how it supposed to work.

**Comment by cpriest** [comment]
Ugh, sorry I'll look right into this.

**Comment by thaliel** [comment]
can I revert back to an older version in the meantime while this issue persists?

**Comment by cpriest** [comment]
Yes, you can go to the addons page and bring up version history and install an older version.

**Comment by oddPT** [comment]
Was coming here to report on this bug.
Will be regressing to a previous version.

**Comment by joe-synapps** [comment]
Snap Links has been my favorite and most often used extension. Unfortunately, this new bug totally throws off my workflow. It's frustrating, and snap links is just not quite as useful anymore. Going into the Options and unchecking "switch focus" does nothing. I will try to downgrade, if possible, and hope this can be fixed at some point.

**Comment by racofer** [comment]
Same issue here, the setting reverts back to on. Additionally, after unchecking "Switch focus to new tab", it stops working and doesn't open any link anymore.

Reverted to 3.1.8 on Firefox and stopped updates for the time being.

**Comment by Joethelazy1** [comment]
Just to add some info to maybe help you in trying to debug. When version 3.1.10 is installed and after trying to uncheck the switch focus button, at least on my system it seems to ignore the settings for the time on opening tabs. It opens tabs at around one per second, and obviously I can't tell about the clicking elements setting. When I fall back to the previous version everything is as expected. Hope this helps, and thanks for your work. Very useful in my job!

**Comment by cpriest** [comment]
I have this issue fixed but I am trying to fix one further problem and will hopefully be releasing 3.1.11 today, sorry for the trouble.

**Comment by Joethelazy1** [comment]
Man, don't worry about that! I really appreciate the time you take to build the extension. It literally saves me hours on my work.
________________________________

**Comment by peluche-nerv** [comment]
@cpriest Thanks for your work dude.

**Comment by RichDG** [comment]
Just wanted to add my thanks for your continued efforts with your excellent extension, can't browse without it, Thanks for all your hard work, so easy for us to take things for granted and only realise how much we need something when there is a glitch so thanks again for the upcoming fix too.

**Comment by mattm3** [comment]
I'm also having this issue, it's not allowing me to save the options.

**Comment by cpriest** [comment]
Thanks for the positive comments, it means a lot!  3.1.11 is pending Mozilla review and god-willing everything will be perfect again, with a new long-awaited feature.

**Comment by pulbitz** [comment]
3.1.11 perfect.
Thanks for your work.
