### ISSUE TITLE
Switch focus to new tab cannot be unchecked anymore

### ISSUE THREAD

**Issue by vodzl** [cpriest/SnapLinksPlus#359]
Hello,
Since 3.1.9/10 releases unchecking Switch focus to new tab option option
doesn't work anymore. After closing setting this option is still remaining enabled
despite the fact i have unchecked it.
Changing storage option are also doesn't work but i do not know if it supposed to since i do not use it.

**Comment by vodzl** [comment]
Somebody just posted same issue while i was posting this one.

**Comment by cpriest** [comment]
@vodzl Thanks for checking/seeing that and closing this one. :)
