### ISSUE TITLE
Links are not opened anymore after closing opened links from same page

### ISSUE THREAD

**Issue by vodzl** [cpriest/SnapLinksPlus#360]
Hello,
Since 3.1.10 release. Latest FF and TOR.
Links are not opened anymore after closing opened links from same page.
Example to reproduce:
1 Go to cpriest.github.io/SnapLinksPlus/#/Tutorial
2 Open Google, Wikipedia links.
3 Close those opened tabs.
4 Try to open those links again or any other links.
5 No luck doing that until restart a browser or open that whole page in a new tab.

**Comment by cpriest** [comment]
Strange, this I did test thoroughly before 3.1.9.  Just before I released 3.1.9 I did some cleanup work that broke 3.1.9, perhaps there is more that was broken.  I'll try and get this fixed/released today as well.

**Comment by carb0n0x** [comment]
Same here, the addon stopped working since a couple days ago on Firefox.
Not sure if it's due to FF's update or the new SnapLinks version.

**Comment by Ronald-G-Andrade** [comment]
Same bug :( Please fix it :(
