### ISSUE TITLE
Tutorial Keeps Coming Up (Likely Addon Interaction)

### ISSUE THREAD

**Issue by Firefairy** [cpriest/SnapLinksPlus#364]
I am aware this is probably an interaction with another mod. My point is that there should be a way to handle this.

What happens: The popup for the new install/tutorial comes up every time I open my browser. Which covers the window controls in the top right corner, which is very annoying.

What I would expect: The popup comes up once after installing/updating the extension.

What I think is happening: SnapLinks uses a cookie or something similar to tell when it is a new install, and one of my security apps is cleaning that up because it isn't whitelisted.

What I would like as a fix: Either use a method to detect new installs that doesn't run afoul of basic security measures, add something to the documentation about how to whitelist the appropriate cookie/whatever, or, if I am wrong about the cause, the bug fixed so this doesn't pop up repeatedly.

My setup: Firefox Developer Edition 93.0b2 (64-bit) under Windows 10
I use Cookie AutoDelete and uBlock Origin. I don't know if my other mods are relevant.

**Comment by cpriest** [comment]
I believe this is happening due to the .9 and .10 releases being messed up.  But I have made a change that should prevent this from happening again in the future if it is what I expect was causing it.

v3.1.11 should be getting released today and will be available pending review.

**Comment by Firefairy** [comment]
Great to hear! I love SnapLinks and wasn't liking the idea of having to choose between losing the functionality or putting up with the popup indefinitely.
