### ISSUE TITLE
Switching to new tabs after opening option stays always enabled.

### ISSUE THREAD

**Issue by wojciechhajduczenia** [cpriest/SnapLinksPlus#367]
Unchecked box to prevent switching focus to new tab and still switches.
Looks like this option is always set to true by default whenever the browser is started and doesnt save the configuration.
![image](https://user-images.githubusercontent.com/45210743/132990886-72e731ae-db38-45a0-ae55-f10cd6b47371.png)

**Comment by cpriest** [comment]
Please see #358

**Comment by cpriest** [comment]
duplicates #366 #358
