### ISSUE TITLE
Request: A version for edge would be fab!

### ISSUE THREAD

**Issue by boardtc** [cpriest/SnapLinksPlus#369]
Hi,

Have you considered a version for edge?

Thanks!

**Comment by cpriest** [comment]
I may consider it once there is more consensus by all of the web browsers.  It's quite a ways from that.  I had put a version out for Chrome (when I was using that), but for silly reasons (new hoops to jump through) they took down the listing and I left it at that.

Feel free to fork and give it a go yourself if you'd like.

**Comment by boardtc** [comment]
No Need, I just found out that all chrome extensions work in edge! Everyday is a school day :-)
