### ISSUE TITLE
[Feature Request] Action timeout

### ISSUE THREAD

**Issue by byzod** [cpriest/SnapLinksPlus#378]
Add an option that allow user to cancel action if they didn't move and release the action button after `timeout` milliseconds. This option can be turned off by default to remain back compatibility

### Why
If I regret to open any links, I need to change the selection rectangle carefully to include none of any links and release the action button

If `timeout` is implemented, I can just wait half a second and release the button anywhere, no worry of open any link unintentionally

### Current option example
Select link when hold down `shift` and I `right click` and drag for `5` px

### New option example
Select link when hold down `shift` and I `right click` and drag for `5` px
Cancel selection if I didn't move more than `10` px for `500` milliseconds

**Comment by cpriest** [comment]
You can already press escape to cancel.
