### ISSUE TITLE
Issue on Youtube

### ISSUE THREAD

**Issue by RNavarro3000** [cpriest/SnapLinksPlus#39]
I'm having a major issue with SnapLinks and Youtube.
a.  At Youtube, went to "My Subscriptions"
b.  Clicked "Uploads only"
c.  Clicked "Load more" button 10 time to get to some older content
d.  Quick right clicked on a video to get the context menu (wanted to open it in new tab)
e.  At this point SnapLinks selection box popped up and went nuts.  The green selection box appeared and I could not get it to disappear.  The selection box moved with my mouse cursor but I was not holding down the mouse button (my start selecting trigger is just the right button). Firefox UI became unresponsive.  Task manager reported memory usage for Firefox process was quickly climbing.  Around the 3GB mark Firefox crashed.
f.  This behavior was repeatable several times.
g.  Disabling SnapLinks, I am able to browse Youtube, with the same steps above, without any issues.

Windows7 / Firefox 28 / SnapLinks 2.4.0

**Comment by cpriest** [comment]
I think this issue may be resolved in the next version 3.1.6, please re-open if not.
