### ISSUE TITLE
[Feature Request] Option to display selected url without opening it

### ISSUE THREAD

**Issue by Hyoros** [cpriest/SnapLinksPlus#390]
(update: as per Garcia remark below I haven't test how would Snaplink 3.1.11 react to same link in other browser so it is possible the problem is from FF itself)
This is my history of using Snaplink, you can skip to next paragraph for my request. I’ve been using Snaplink at least since May 2016 in Firefox. I’m someone who doesn’t update most of everything I use. I have been using ver Version 2.4.3 (I just restore my Firefox to 3 days ago, now I'm updating it step by step to see where it went wrong) in my 2015 Firefox for 4 years now to open website link or my custom hyperlinks I created in Excel. But on September (I only find out last week) “Let's Encrypt's cross-signed root certificate” expired, breaking many websites on old browser and forcing me to update my Firefox to the latest ver (94),  and with it the new Snaplink. 

Today I find the ‘new’ Snaplink behave differently than the one from 4 years ago, the details are explained  [here](https://stackoverflow.com/questions/69869818/new-firefox-doesn-t-recognize-url-from-html-if-it-start-with-space-or-slash-nee (if you want to see my thought process before realizing this niche behavior of Snaplink)  )

but to summarize, I use Snaplink in a .HTML file to display custom hyperlinks containing “either a space or slash followed by number” into Firefox url bar. Just to display, not opening the hyperlink like a normal url. 
The html look like this
``` 
<A HREF="https:// /1394879/"</A>Hyperlink name</a>
```
and Snaplink will open it to look like this in url bar 
```
https:// /1394879/
```

I only find it today that I wasn’t suppose to write url like that, but it worked. I don’t know since which version this behavior changed, I checked in https://addons.mozilla.org/en-GB/firefox/addon/snaplinksplus/versions/ Ver 3.1.5 doesn’t even work for FF94. Ver 3.1.6 forward can open the link but here’s what different from old Snaplink: 
If the html is like this 
```
<A HREF="https:///1394879/"</A>Hyperlink name</a> 
```
‘new‘ Snaplink will open that number and browser will convert the number into IP address
If the html is like this 
```
<A HREF="https:// /1394879/"</A>Hyperlink name </a> 
```
Snaplink 3.1.11 in FF94 won’t recognize the hyperlink as url and will ignore it 
When old Snaplink encounter my custom hyperlinks,  it will simply open them all in new tabs without attempt to open it. Yeah that sound like a niche way to browse things. I sound like a defrosted caveman asking you to bring your tech level down to me and I feel bad for this but it is the only thing I got. 

So I want to request that Snaplink provide an additional option to treat incomplete url like I described. If you need reference this behavior still work in ver 2.4.3 in Pale Moon and 3.1.4 chrome.

**Comment by remi-garcia** [comment]
[Workflow](https://xkcd.com/1172/)

I believe we should not verify if urls are correct or not but open anything provided by href. My first intuition is that Firefox sanitizes the urls and not the add-on. Can you provide a minimal html file so that we can try to see the behavior of SLP3 on this?

**Comment by Hyoros** [comment]
" but open anything provided by href. "
Yes like that! I never attach file in reply before, the html simply contain line like this
```
<A HREF="https:// /963188/"</A>A4</a>
<A HREF="https:// /1065780/"</A>A5</a>
<A HREF="https:// /1099387/"</A>A6</a>
<A HREF="https:// /1165242/"</A>A7</a><br> 
```
If this is not suffice, where should I upload the sample html? I don't see upload button in the reply box

**Comment by remi-garcia** [comment]
You can rename the file from .html into .txt and it should work. The upload button is below the reply box, you can click on "Attach files by dragging & dropping, selecting or pasting them.".

I have been a bit occupied recently but I'll try to take a look at that problem soon.

**Comment by Hyoros** [comment]
Here you go
[Hyoros url.txt](https://github.com/cpriest/SnapLinksPlus/files/7492939/Hyoros.url.txt)

**Comment by remi-garcia** [comment]
I did some tests and my conclusion is that Firefox won't open ill-formatted urls anymore.
SLP3 opens links using default Firefox behavior,
```JS
browser.runtime.sendMessage({
	Action: OPEN_URLS_IN_TABS,
	tUrls:  links,
});
```

and we shouldn't change that.

I believe that your workflow cannot be applied to newer versions of Firefox and you're left with two possibilities: either change your workflow or have an old Firefox instance available for your specific use case. The latter cannot be recommended on a machine that has access to the internet.

IMHO you should find a solution to your use case that does not rely on a web-browser and SLP. From what I understood, a simple Python/Bash/etc. script could probably replace your current workflow.

**Comment by Hyoros** [comment]
I see. About this workflow of mine. Recently I am aware of how my workflow is like building house on beach sand. Except it is even shakier than I thought it is. 9 more FF versions (and 4 hours) later I find that FF speed to return the corresponded URL is something I take for granted. between FF 48-56,  half of them took 3-4 seconds, the other halves need user to manually type a website name (doesn’t have to be the target web), paste the number and wait few second for FF to show the urls from history. Even if the recognition speed return in FF57,  the Legacy Add Appon (my other lifeboat) only work up to, you guess it, FF56. This is some cosmic level coincidence. 

Sunday took 10 hours, today took 4. Do you think I could’ve learn how to write and sign manifest, replace SL3.1.11 content with SL2 to work in latest FF then add this to Mozilla’s addon page with that time?

**Comment by Hyoros** [comment]
Long journey for 4 days and I end up return home to FF42. But 1 last ride. 
I download zip file for both SL3 11 and SL 2. From your lead I seek what SL defined as link. I found ‘open url’ in SL3 and another function in global.js that declare link from there I try finding anything that define what to open in SL2. 
That href give me idea so I find that SL2 defined object it interact with with 2 ways: the one that have href length === 0 something something and the other who define things like radio button or checkboxes. I find something similar but written in different in SL3 so I thought maybe this is what the developer drop when migrating to new addon format
Then I find the same code in SL3.  But Idk if it is just there for documentation. 
If anyone in future want to put it back to modern SL, you can contact me on Youtube.  I only here for temporary session

**Comment by cpriest** [comment]
SnapLinks is pretty simple in its behavior.  It just gets the .href property of each <A>nchor element and sends it to the background worker to open the links (privilege reasons.)  

If FF is not returning a value or a valid value then it will just not act upon it with FF's built-in security.  I would bet that the previous XUL-based version got the HREF attribute via .getAttribute() which most likely would not have had any FF sanitization features.
