### ISSUE TITLE
Sideloading Chrome version 

### ISSUE THREAD

**Issue by leodoi3** [cpriest/SnapLinksPlus#395]
I used your addon on Firefox mainly for selecting multiple checkbox / radio buttons. Seeing that your Chrome link isn't working could you update it please? If not possible could you include instructions for sideloading into Chrome?

**Comment by cpriest** [comment]
Yeah, they de-listed it some time ago for reasons I no longer remember so I stopped updating it there.  I do not know how to side-load it into Chrome, unfortunately.
