### ISSUE TITLE
<Ctrl + Left Click> default interaction effectively reversed

### ISSUE THREAD

**Issue by willhansen** [cpriest/SnapLinksPlus#403]
"Pressing CTRL after selection to modify default action".  Well, when you are already pressing control, that happens every time.

When a control key is selected as a required modifier, the default action is effectively the opposite of whatever is selected in the settings.  An easy workaround is to just select the opposite of what you want, but it's still a bug.
![Selection_005](https://user-images.githubusercontent.com/2918280/147861207-6d0d6c92-1898-42dd-b931-2a0e52053a43.png)

**Comment by cpriest** [comment]
Hmm, are you sure if you use ctrl + left click, start the drag, then let go of control and let go of the mouse it does the opposite?  

The above sentence is for starting the drag, only the same mouse button must remain down during the drag and at the completion.

**Comment by willhansen** [comment]
You're right, the order the buttons are released matters.

**Comment by cpriest** [comment]
It's not, but at the time the 'hold ctrl to do X' was written, there was no option to change what started the drag option.
