### ISSUE TITLE
How it works

### ISSUE THREAD

**Issue by harrystein** [cpriest/SnapLinksPlus#41]
Mr. Priest:

What do I need to do with the mouse to get the links into the clipboard.  Letting go the mouse after I drag to subsume the links simply defaults to opening those links in new tabs.  Yet you note that one can also caused the information to be added to the clipboard for pasting into a spreadsheet.   I have yet to figure out how this is done, precisesly.

I tend to agree with the follow who was surprised there was no documentation whatsoever.  Not even on GIT.

Thanks in advance.  Harry Stein

**Comment by cpriest** [comment]
Closing this ticket, the next release will welcome new users to an introduction page.
