### ISSUE TITLE
Snap Links doesn't work on firefox on linux

### ISSUE THREAD

**Issue by thibaultmol** [cpriest/SnapLinksPlus#433]
I can't get snap links to work in firefox on linux (Have never gotten it to work, last year i tried as well iirc).
I'm on the latest version of both the extension 3.1.11 and firefox 102.0.1 (64-bit)
Looking at the reviews of the extension on the firefox store, multiple of the recent negative reviews are also from linux (and a mac) user.
I'm not sure what's going wrong, but it's just not working. I drag to select them and it counts the amount of selected links corrected. But then doesn't open them. I can use the extension with checkboxes and stuff and that works fine, but not links.
I've tried multiple keyboard combo's; left or right mouse button. No configuration seems to make it work.
I've tried on a fully seperate firefox profile that had no other extensions on it and that wouldn't work either.
If look at the console output on the page itself I get this

> {
>   "Links": [
>     {},
>     {},
>     {},
>     {},
>     {},
>     {},
>     {},
>     {},
>     {},
>     {},
>     {},
>     {},
>     {},
>     {},
>     {},
>     {},
>     {},
>     {},
>     {},
>     {}
>   ],
>   "FilteredLinks": [],
>   "Clickable": [],
>   "FilteredClickable": [],
>   "Checkboxes": [],
>   "RadioButtons": [],
>   "Unknown": [],
>   "GreatestType": "Links"
> }

**Comment by cpriest** [comment]
Hmm, there are some development features that would need to be enabled for those logs to show up.  One of those features is "perform no action."  Is that perhaps checked?
![image](https://user-images.githubusercontent.com/159323/179250672-82fca373-0c7b-4698-b177-c5a05d9ed436.png)

**Comment by cpriest** [comment]
I will try and get a VM up and running to test this on some version of Linux and see what's up.

**Comment by fabiodm7** [comment]
The same issue occur in Windows 10 with Firefox 103.0.2. It is ok for checkboxes but not ok for links.

**Comment by thibaultmol** [comment]
Still doesn't work btw

**Comment by Thebuilderekes** [comment]
I'm using Linux mint 21.1 and it works just fine for me on Firefox 113.0.1.

**Comment by KAGEYAM4** [comment]
It works for me here too, i think issue got fixed and can be closed.

**Comment by charliefrance** [comment]
Works with checkbox but not links
