### ISSUE TITLE
[bug] "Default Action" inverted

### ISSUE THREAD

**Issue by EmberHeartshine** [cpriest/SnapLinksPlus#436]
Browser: Firefox 104.0
OS: Windows 10 LTSC
SL Version: 3.1.11

**Steps to reproduce:**
1. Install Snap Links
2. Change the default action to "copy links to clipboard"  
![image](https://user-images.githubusercontent.com/50666308/186431465-da70159a-57d8-436c-9188-9e5b7259d4e6.png)
3. Try to select multiple links to copy

**Expected behavior:**
* The links should be copied to the clipboard with a newline between each

**Actual behavior:**
* The links open in new tabs

**Comment by cpriest** [comment]
Be sure you are not holding down ctrl/alt/shift when you release the mouse.

**Comment by cpriest** [comment]
I just tested this with my action being ctrl + right-click-drag, releasing control after the drag has begun, and grabbing links copies them to the clipboard.  Tried it with just right-click-drag to start and the same results.  Works as intended.
