### ISSUE TITLE
Windows/Firefox: Modifiers break SnapLinksPlus

### ISSUE THREAD

**Issue by Prometheos2** [cpriest/SnapLinksPlus#440]
Hello,

I've noticed that the add-on does not open links on Firefox on Windows when a modifier is set.
Having "No modifier" set makes the add-on open links properly.

I enabled all developer options in later attempts, but that did not fix the problem.
I could send you the logs if you tell me where to find them.

## Steps to reproduce
1. Set "Ctrl" modifier
2. Go to a website with links (e.g., https://cpriest.github.io/SnapLinksPlus/#/Tutorial)
3. Select links/buttons with the lasso with Ctrl+RMB

**Comment by cpriest** [comment]
It's probably fighting with some other addon.  also note that The modifiers selected need to be exactly those modifiers and no additional

**Comment by Prometheos2** [comment]
> It's probably fighting with some other addon.
That would be a problem, I have quite a few addons.

> also note that The modifiers selected need to be exactly those modifiers and no additional
I tried again to make sure, and now only Ctrl modifiers do not work, so I don't know if it's that or something else...
I soft-reset Firefox yesterday, so maybe some of the blocking addons were removed. 

I will check with Firefox troubleshooter mode, and come back at you.

**Comment by cpriest** [comment]
I just realized what you're running into.  The behavior is such that holding down control *when releasing* the button will cause it to do the opposite of the default action (which is to copy the links to the clipboard).

![image](https://user-images.githubusercontent.com/159323/204338806-6154da96-0bb9-4ecf-8e42-6c03b2667765.png)

**Comment by Prometheos2** [comment]
Glad to see you found the issue

Have a nice day!
