### ISSUE TITLE
MacOS functionality issues [videos showcasing exact problems inside]

### ISSUE THREAD

**Issue by throwaway000000000** [cpriest/SnapLinksPlus#450]
First of all, thank you for this addon. It's been so helpful to me while using my Windows desktop that I literally created a GitHub account just so that I might have the same functionality on my MacBook.

--------------------------------------------

Now to the two issues at hand.

**My setup is: MacBook Air M1 - MacOS Ventura 13.1 - Firefox 110.0 - SnapLinks latest version

--------------------------------------------

**ISSUE 1**

https://user-images.githubusercontent.com/126399896/221415448-0db56ddc-4eec-471c-9fe5-6a26df20d2e0.mov

Actions I did on this video:

    1. Open new tab in Firefox
    2. Open random news site
    3. Right click and drag to use SnapLinks

So the issue is that when you open a new page and try to use the right click + drag for the first time, it opens the regular MacOS right click menu instead every time.
And this ONLY happens the FIRST time you try to use SnapLinks on a new page.
As you see on the video after that I make my FIRST problematic attempt the REST of my attempts show normal SnapLinks functionality.
But every time you land on a new page or every time you refresh a page this same thing is happening: the first right click & drag always pops up the MacOS menu instead. Once it gets that out of its system (so to speak) it works normally as it should.

--------------------------------------------

**ISSUE 2**

https://user-images.githubusercontent.com/126399896/221415513-a193ce16-1a9e-42ba-bb5e-f1a456639026.mov

Actions I did on this video:

    1. Open new tab in Firefox
    2. Open random news site
    3. Right click so that I can use the regular MacOS right click menu and NOT SnapLinks

The issue here is that when I simply right click WITHOUT any dragging, SnapLinks is somehow activated. In the video I simply right clicked and selected something from the MacOS right click menu but as you see SnapLinks was activated for no reason and I was left with an undesirable selection area.

--------------------------------------------

I tried to be as thorough as I could in my descriptions. Thanks in advance for any help!

**Comment by cpriest** [comment]
The problem is that Mac/Linux variants operate differently with the right click.  They show the context menu on the mousedown vs. the standard of showing it on the mouseup.  This is an outstanding issue I haven't been able to address because I don't have a way to test it on a Mac.

**Comment by throwaway000000000** [comment]
I see! So I suppose it's not something that could be solved anytime soon since you don't have access to a Mac. In any case, thanks for replying and thanks for making this addon! It has improved my browsing experience a lot since I found it.

**Comment by remi-garcia** [comment]
See https://github.com/cpriest/SnapLinksPlus/issues/400#issuecomment-1005638078

**Comment by remi-garcia** [comment]
I've edited your message to replace `#1` by `1` so it does not trigger a link to the issue number 1.

**Comment by cpriest** [comment]
Thanks @remi-garcia I forgot about that workaround!

**Comment by throwaway000000000** [comment]
> See [#400 (comment)](https://github.com/cpriest/SnapLinksPlus/issues/400#issuecomment-1005638078)

This works indeed! Thank you so much!
