### ISSUE TITLE
[Feature Request] Change keybind

### ISSUE THREAD

**Issue by misspent** [cpriest/SnapLinksPlus#451]
Hello, this is a great extension. 

I'd love the ability to change the keybind to middle-mouse button (scroll wheel) or left click. I use an extension called [Gesturefy](https://addons.mozilla.org/en-US/firefox/addon/gesturefy/), and I'd love to have the option to change the keybind of this to middle-mouse button. If you've already got this as an option, then I'm sorry for wasting your time.

**Comment by remi-garcia** [comment]
![Screenshot from 2023-03-27 07-45-37](https://user-images.githubusercontent.com/47191601/227851350-2a737f68-1e13-47c9-b07e-60455d001f7c.png)

You can find this option in Preferences
