### ISSUE TITLE
Seems to have stopped working when FF went to 118?

### ISSUE THREAD

**Issue by BobZyerunkl** [cpriest/SnapLinksPlus#461]
Anyone else lose functionality with the latest FF build, or it is just me?  I hoped it would come back with the first couple of bugfix updates, but they have now updated 2 more times (currently 118.02) and the green frame still no longer appears when dragging and there seems to be no way to select links.

**Comment by cpriest** [comment]
I just tried it and I'm on 119.b06 and it works fine.  Perhaps it is conflicting with another extension or the activation method was changed?
