### ISSUE TITLE
[Question] The right click Trigger - and a Bug - issues with Linux Mint 21.2

### ISSUE THREAD

**Issue by cxbignekoc** [cpriest/SnapLinksPlus#465]
Glad to find you here.
There is one Bug and some issues aound
**This issues is maybe an Linux specific Issues i have not found a solution yet.**
So maybe you guys got a smart idea about it.

```
I use Linux Mint 21.2 MATE flavor
Metacity (Marco)
FF 119.0.1 (mint-001 - 1.0)
```
```
~$ localectl status
   System Locale: LANG=de_DE.UTF-8
       VC Keymap: n/a
      X11 Layout: de
       X11 Model: pc105
```

There is a Feature inside Linux that let you open the right-click menu with 1-click (on push) and choose/ select with **release** the button (2 - click, on release). So in Windows you open it the same way but only on release.
This feature makes some issue when using the right click to draw an rectangle for Snap, what is the most comfortable way to me using Snap.

i know that some settings can be a walkaround:

- using a modifier (want to keep it most comfortable one hander)
- using middle mouse button (what is also COPY from Clipboard)
- using left button and more pixel (that can work but not on scrollbars, when not using mouse wheel)
- action at more Pixels, works but not on an open right click menu (remember that open on right click push, what activate the rectangle)

**A Bug:** - from the last Point above !

There is a bug when using the "open in new tab" from the right click menu on a Link.
it opens a Link in a new Tab but also draw an rectangle without follow the setting rules of 200 Pixel.
It not use the Rule of the Pixels when using right click menu. snap instantly draw an rectangle

https://github.com/cpriest/SnapLinksPlus/assets/31941245/8a10f95e-743e-4a70-8acc-b9264721da4e

**Comment by remi-garcia** [comment]
I believe this is the same issue as #400 

You'll find a workaround here: https://github.com/cpriest/SnapLinksPlus/issues/400#issuecomment-1003714487

**Comment by cxbignekoc** [comment]
solved with this edit in FF
