### ISSUE TITLE
How to convert pasted urls copied in clipboard to Tabs?

### ISSUE THREAD

**Issue by KAGEYAM4** [cpriest/SnapLinksPlus#468]
We have option to copy the urls into clipboard instead of openint in new tabs.

Can you please tell us where can we this feature?

One usecase that i found was, to converst the clipboard copied url to tabs at later point but couldn't find any way to do it.

My problem is sometimes i open different browsed to do some side word like mullvad, librewolf, or chromimum based browser, now i want to move those tabs to my main firefox browser and i can't find any way to do it, so snaplike came to my mind because it copies the like to clipboard but i couldn't make it work. 

any idea on how to solve the above problem ?

**Comment by cpriest** [comment]
This is outside the scope of the program.  You can, however, easily open a bunch of tabs by running this at the command line:

firefox.exe <link1> <link2> <link3>...
