### ISSUE TITLE
Snap Links Plus no longer works with Chorme?

### ISSUE THREAD

**Issue by egozi44** [cpriest/SnapLinksPlus#469]
I've been using it for some years but seems like it's not in the google store anymore, 
Is there any way to get it (while hope it's still working on new ver of Chrome)

Also I've for some idea that was on some old link opener addon that I've used before which I wish this pluging will get one day,
But that's for later assuming it's still being worked on

**Comment by cpriest** [comment]
Yes it was de-listed some time ago on Chrome because of new policy changes and I never jumped through their new hoops.  I believe they migrated everyone to some other add-on.  Likely you haven't been using SnapLinks for some time.

**Comment by egozi44** [comment]
I've used it on my old machine who didn't updated the chorme for awhile,
I assume there's no hopes to see it on chorium apps anymore now? :0

**Comment by remi-garcia** [comment]
> I assume there's no hopes to see it on chorium apps anymore now? :0

I don't think so. You can see the original issue on that topic: #309

**Comment by egozi44** [comment]
Ah shame, I've used a lot of multi-link like extentions over the years, most of them lost support which forced me to move each time, Snap link was the closet to the best one I've used before, the current replacements are meh compared to it

**Comment by remi-garcia** [comment]
I am sorry to ear that. I wish you the best in your search for a replacement. If you find anything good for Chrome, do not hesitate to link it here.
