### ISSUE TITLE
Selection "drop" issue

### ISSUE THREAD

**Issue by PHPDev-CA** [cpriest/SnapLinksPlus#47]
I've encountered this a quite few times when select scrolling long documents:

I'll start selection and at some point the system will register that I lift the right mouse button and immediately press it again.  This usually happens when using the 3 finger scroll or mousewheel, not the keys.  As a result it's probably a driver bug you can't do anything about, however, after release the context menu doesn't appear to pop up, it instead immediately goes into a new selection box.  I attempted adjusting the "Delay between actions" option but it seemed to have no effect on this particular issue.

Any ideas on how to keep this from happening or at least get the context menu to pop up?

**Comment by remi-garcia** [comment]
This is an issue with @PHPDev-CA mouse, solving #10 or #45 will provide a workaround to this issue.
Can be closed
