### ISSUE TITLE
Not working on https://rss-bridge.org/bridge01/

### ISSUE THREAD

**Issue by KAGEYAM4** [cpriest/SnapLinksPlus#471]
https://rss-bridge.org/bridge01/

**Comment by cpriest** [comment]
Hmm it works for me though it does take a moment from a right-click before it starts showing the bounding box.  I'm guessing this is due to the sheer size of the page.

**Comment by KAGEYAM4** [comment]
> Does it work for you if you activate and hold the activation for a couple of seconds and then drag?

Yes it's working this way.

**Comment by KAGEYAM4** [comment]
i will be closing this issue, as its not that important, also it works - it's just the site is too large which is edge case.
