### ISSUE TITLE
SnapLinks is scrolling very fast in Firefox - I think it's due to a FF update

### ISSUE THREAD

**Issue by PartyRambo** [cpriest/SnapLinksPlus#474]
Just in the last week or so, I've noticed that when I copy a list of links on a page which is longer than one screen - ie. one needs to scroll to get to the bottom of it - the scrolling becomes very fast & uncontrollable.
I have a regular task with just 15 links on the page; they usually all fit on one screen, so I just need to SnapLink down to the bottom of the SCREEN, not the bottom of the PAGE.  But because it scrolls out of control now, it goes all the way down.
Then I have to manually scroll back to the top to click to the next page.
I have this automated in a keyboard macro, but it isn't working because the scroll is out of control.
FF has updated a couple of times this month (v. 126.0 right now), and SnapLinks hasn't - so it's pretty clear to me it's a FF issue.
While this isn't SnapLinks' fault, I'm hoping it can be reviewed... thanks...

**Comment by Zaeems** [comment]
Seeing another issue with scrolling - in youtube - holding right click causes the page to scroll down on its own.

**Comment by Parsnip** [comment]
Yep, just noticed the youtube related issue and came here to report it. If I have snaplinks set to activate on holding right click, on youtube I can no longer right click normally at all. Adding a modifier such as ctrl+right click makes it so I can use normal right click again, but it doesn't fix the behavior of the extension otherwise. Selecting multiple links on youtube seems impossible now.

**Comment by barbaduk** [comment]
found a workaround - extension works fine with 120% page scale (and some others, but not any. try different and find what works for you)

**Comment by Parsnip** [comment]
Can confirm that the workaround works on youtube, 110% works on my end for example. That's kind of an insane workaround too, how in the world did you even find it?

🥇

**Comment by PartyRambo** [comment]
> found a workaround - extension works fine with 120% page scale (and some others, but not any. try different and find what works for you)

Cool!!   Unfortunately, I have hundreds of keyboard/mouse macros doing the work I do as a hobby, that require a standard screen size of 90%.  Changing the zoom level, would require manually re-setting all of the mouse positions in them - not possible to re-do several years of trial & error...  I'm hoping that clint (or anyone else who's working on this extension) will read this thread & report...
But good on you for finding that!  I can use it for a couple of other things.

**Comment by SmilingMadCat** [comment]
Still having the same issue. Youtube, Archive of Our Own, and others.

**Comment by cpriest** [comment]
My apologies everyone, I will try and get this new fix in a new
    version release in the next few days.
