### ISSUE TITLE
Display Size is logged to console

### ISSUE THREAD

**Issue by CennoxX** [cpriest/SnapLinksPlus#499]
If I rightclick on a website with the addon version 3.1.12 using Firefox 130.0.1 (64-Bit), the display size is logged to console (for example `1908 812 globals.js:175:53`) even if I have Dev Mode not activated. My expected behaviour is, that these infos are only logged to console, if I "Enable Dev Mode" in the settings.

**Comment by cpriest** [comment]
I've released a new 3.1.13 for Mozilla approval.
