### ISSUE TITLE
Not working with application/xhtml+xml pages

### ISSUE THREAD

**Issue by Keith94** [cpriest/SnapLinksPlus#50]
I can't open the commit links here for example:
https://github.com/cpriest/SnapLinksPlus/commits/master.atom

**Comment by remi-garcia** [comment]
Isn't that solved already?

**Comment by cpriest** [comment]
Hmm, when I try to open that link it just wants to download the file.  If I have it open that file in Firefox then SnapLinks is not loaded as its not a web page.
