### ISSUE TITLE
navigator.clipboard.writeText(links.join("\r\n"));

### ISSUE THREAD

**Issue by wincmd64** [cpriest/SnapLinksPlus#510]
Hi !
We found a bug in the transfer links to **httpdownloader** 
Can you pls help us?
https://github.com/erickutcher/httpdownloader/issues/316

**Comment by remi-garcia** [comment]
@cpriest 
It seems that changing
https://github.com/cpriest/SnapLinksPlus/blob/5035cbcf515474cb0bbb063c7ced75d83bae1fd1/src/content-scripts/ActionMgr.js#L15-L15
to
```JS
navigator.clipboard.writeText(links.join("\r\n"));
```
would solve their issue and should not change anything for SLP.

**Comment by cpriest** [comment]
Seems easy enough, it should be that way for Windows anyways.
