### ISSUE TITLE
New tabs opening in the wrong browser window

### ISSUE THREAD

**Issue by nemo701** [cpriest/SnapLinksPlus#513]
There seems to be a slight bug whereby if you use SnapLinksPlus to open a large number of links, and switch windows part way through those tabs being opened, some of those tabs will be opened in the "wrong" window 

Steps to reproduce -

1. Have two firefox windows open (1) and (2)
2. Open a page in (1) with multiple links on it (eg https://www.theregister.com/), and use SnapLinksPlus to open those links
3. (Quickly) click on/activate (2) during the course of the links being opened, and the remainder of the tabs being opened will be opened in (2), rather than (1)

Expected behaviour - all of the links should be opened in (1)

The problem is more noticeable with longer lists of links

**Comment by cpriest** [comment]
I've verified this is happening, I'll see what I can do about it.

**Comment by nemo701** [comment]
Confirmed fixed in version 3.1.15, thank you very much!
