### ISSUE TITLE
Using CRLF as a separator causes problems on Linux

### ISSUE THREAD

**Issue by neeshy** [cpriest/SnapLinksPlus#517]
The commit made for #510 causes problems on Linux. When pasting into a terminal (I've tried xterm, urxvt, and st) `\r\n` is interpreted as two newlines.

Something like:

```js
navigator.clipboard.writeText(links.join((await browser.runtime.getPlatformInfo()).os === chrome.runtime.PlatformOs.WIN ? '\r\n' : '\n'));
```

would fix it. `navigator.platform === 'Win32'` could be used instead but it seems like that API is deprecated.

**Comment by cpriest** [comment]
Could you submit a pull request?

**Comment by neeshy** [comment]
Done: #518
