### ISSUE TITLE
It's dead in youtube..

### ISSUE THREAD

**Issue by delicacy1** [cpriest/SnapLinksPlus#53]
Please update it for youtube. when a search is made, either i try to open a link on a new tab or several, it just opens one page in the foreground..

thanks

**Comment by delicacy1** [comment]
I don't think you should restructure sites stupidly coded in html,
this userscript fixes the issue:

https://greasyfork.org/en/scripts/9932-youtube

thanks

**Comment by cpriest** [comment]
Cool, thanks for finding that.  Sorry I haven't had time to deal with this or many of the other long overdue issues, but I am working on a re-write (v3).
