### ISSUE TITLE
e10s compatibility issue 

### ISSUE THREAD

**Issue by wsmwk** [cpriest/SnapLinksPlus#56]
Snap Links Plus 2.4.0 not working at all with e10s. Enable e10s by setting the about:config pref browser.tabs.remote.autostart to true. Attempt to open some links, cllick+drag shows no rectangle.

I have filed https://bugzilla.mozilla.org/show_bug.cgi?id=1061277

**Comment by cpriest** [comment]
Closing this as no further fixes/development is being done to v2.x branch, new v3 is a complete re-write. Please re-open if issue is still present in v3 when released.
