### ISSUE TITLE
Suggestion: Tabs to Open at End

### ISSUE THREAD

**Issue by CaseyStellar** [cpriest/SnapLinksPlus#58]
The current configuration of SnapLinksPlus opens new selected links between currently opened tabs instead of at the end of currently opened tabs. So for example, if I have tabs A, B, C and D open and I select 4 hyperlinks to be opened in tab A, tabs A1, A2, A3 and A4 opens directly in between tabs A and B instead of at the end, to the right of tab D. I would like to see the option to choose this behavior in the future. Thank you in advance. Best regards.
![capture 1](https://cloud.githubusercontent.com/assets/8676530/4174670/5b91279e-35a0-11e4-8096-20298b36118b.png)
![capture 2](https://cloud.githubusercontent.com/assets/8676530/4174672/650030c2-35a0-11e4-969b-80a94a6b8ffd.png)
![capture 3](https://cloud.githubusercontent.com/assets/8676530/4174673/6a13d442-35a0-11e4-8129-fdb25b4875e1.png)
![capture 4](https://cloud.githubusercontent.com/assets/8676530/4174675/6e11ec78-35a0-11e4-8479-3aca0165afbc.png)

**Comment by CaseyStellar** [comment]
I know it's been a while but, have you implemented this feature yet? Long story why I'm replying so late..

**Comment by cpriest** [comment]
oh yes, long ago.

**Comment by CaseyStellar** [comment]
Awesome. Thanks lol. But, to clarify, is it an option that can be turned on and off or?
