### ISSUE TITLE
Snap Links Plus is currently broken on Firefox Nightly(since 2014-09-16)

### ISSUE THREAD

**Issue by BenYeeHua** [cpriest/SnapLinksPlus#60]
Hi, just want to tell that it is currently broken on Nightly, because of this change.

Bug 1001090 - Implement ES6 "temporal dead zone" for let and const
https://bugzilla.mozilla.org/show_bug.cgi?id=1001090

And also thank you for making this addon. :)

**Comment by cpriest** [comment]
Release 2.4.2 should have taken care of the problem, I tested up to Australia release FF36 before the release.  SLP is not compatible presently with electrolysis.

**Comment by tivac** [comment]
Thanks so much!

**Comment by wsmwk** [comment]
Nightly works great. Thanks very much for fixing this.

**Comment by BenYeeHua** [comment]
It is working now, Thank for the fix! :)

**Comment by cpriest** [comment]
Your welcome.
