### ISSUE TITLE
remove shadow in tabs selected info

### ISSUE THREAD

**Issue by thaliel** [cpriest/SnapLinksPlus#61]
I am visually impaired, and since the addonbar no longer exists (unless you use classic theme restorer), I have moved the info about number of tabs selcted next to the mouse pointer. But the shadow behind the text makes the text appear somewhat blurry to my eyes. I think simply removing the shadow would be a great help

**Comment by cpriest** [comment]
Hmm, I think there may be something else going on with your machine, there is no shadow that is applied by SLP to the link count in either location.

**Comment by thaliel** [comment]
well then what is this? (indicated by arrow)
http://i364.photobucket.com/albums/oo86/Thaliel/SLS_zpsf8e25ab1.jpg

**Comment by cpriest** [comment]
Not sure whats causing it but its nothing SLP is doing...
Id suggest trying it in a new FF profile and younshould see what i mean.
-Clint






 From: thaliel <notifications@github.com> To: cpriest/SnapLinksPlus <SnapLinksPlus@noreply.github.com> CC: Clint Priest <github-general@rxv.me> Subject: Re: [SnapLinksPlus] remove shadow in tabs selected info (#61) Date: 1/13/15, 8:43 AM

 
well then what is this? (indicated by arrow)
 http://i364.photobucket.com/albums/oo86/Thaliel/SLS_zpsf8e25ab1.jpg?

**Comment by cpriest** [comment]
Must be getting inherited by some other plugin that's adding the shadow.  I can add a force-no-shadow type css declaration sometime.

**Comment by cpriest** [comment]
Closing this as no further fixes/development is being done to v2.x branch, new v3 is a complete re-write. Please re-open if issue is still present in v3 when released.
