### ISSUE TITLE
Stopped working with FF35 Beta

### ISSUE THREAD

**Issue by MoltenTesseract** [cpriest/SnapLinksPlus#63]
I've gotten into work after 2 weeks off and noticed that the plugin has stopped working.

Also, the preview of what the selections lines look like in the options menu is always blank, no matter what colour and thickness I pick.
![Uploading Capture.PNG . . .]()

Running FF35 Beta with the latest updates.

**Comment by cpriest** [comment]
I'm working on a new release right now to fix it for FF35, I'll check 
into this as well.

**Comment by cpriest** [comment]
This should be taken care of with the latest release 2.4.2 just approved by Mozilla.
