### ISSUE TITLE
Add accesskeys

### ISSUE THREAD

**Issue by yfdyh000** [cpriest/SnapLinksPlus#68]
In context menu and options window items.

**Comment by davidhedlund** [comment]
Set **Esc** to cancel Snap Links Plus lasso.

One thing of particular importance is the ability to cancel current selection which just happened to me on a non-valid HTML page: I tried to select Bluehell Firewall and Bookmarks Checker but instead _everything above_ them was selected which eventually collapsed my browser.

![untitled](https://cloud.githubusercontent.com/assets/6416073/19421905/4e5bfc86-940b-11e6-8235-041f9fa3ff06.png)

**Comment by davidhedlund** [comment]
[mylabel:bug](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Abug%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by cpriest** [comment]
Sorry, yes the current version that is released has quite a number of issues, all of which have been addressed in the development version which is due to be released sometime this week hopefully.

**Comment by davidhedlund** [comment]
@cpriest I can cancel selected links with Esc now. I think you can close this issue.

Or do you have something else in mind @yfdyh000?

**Comment by yfdyh000** [comment]
@davidhedlund This issue is not about Esc key. https://addons.mozilla.org/firefox/addon/snaplinksplus/versions/?page=1#version-3.1.0.4 (https://github.com/cpriest/SnapLinksPlus/commit/1f80c05afd9786967d7d0ccc677e3d62fd2028f1) maybe fixed that issue.

The context menu is not available in the new 3.x for now.

**Comment by davidhedlund** [comment]
@yfdyh000 Perhaps the issue should be open then?

**Comment by yfdyh000** [comment]
Waiting for the context menu, hopefully it may carry this request directly.

**Comment by davidhedlund** [comment]
@yfdyh000 Ok, let's hope for the best.
