### ISSUE TITLE
Bootstrapped extension

### ISSUE THREAD

**Issue by yfdyh000** [cpriest/SnapLinksPlus#69]
https://developer.mozilla.org/en-US/Add-ons/Bootstrapped_extensions

**Comment by cpriest** [comment]
This is actually in progress, kindof.  I started this quite some time ago but have been pulled away to other duties.  I believe the bootstrapped stuff I have worked on (mostly playing around and such) is in the master branch.

**Comment by cpriest** [comment]
Closing this as no further fixes/development is being done to v2.x branch, new v3 is a complete re-write. Please re-open if issue is still present in v3 when released.
