### ISSUE TITLE
Feature request: Do not open visited links

### ISSUE THREAD

**Issue by theSLY** [cpriest/SnapLinksPlus#72]
Hello! Thank you for great plug-in! I use it every day and find it very useful! Is it possible to make option to open only unvisited links instead of opening all selected links?

**Comment by cpriest** [comment]
I think that's a possibility, would it be something you'd want to choose 
just like you can now choose the default of 'open all selected links' 
and alternatively select it on specific invocation via ctrl menu?

Unfortunately I have not had time to work on SLP in quite some time and 
there is an impending deadline on the not to distant horizon with 
Mozilla's Electrolysis feature which has to be completed first.  It's 
going to be a big job and it hasn't even been started yet.

**Comment by theSLY** [comment]
In my opinion Hotkey modifiers for this option will conflict with current 'Start selecting with' policy. So it could be a feature for selected URLs, and thus user can modify behavior of add-on for selected web-sites. Other way, it could be a 'double click + drag' for activating this feature, if it possible.

**Comment by cpriest** [comment]
Hmm, I may implement basic support for it first (utilizing the current activation method + alternate) and later down the road allow for more customization of activation like being able to configure RCD = this and Ctrl+RCD = this and Double RCD = this...

**Comment by remi-garcia** [comment]
Closed in favor of #322
