### ISSUE TITLE
Doesn't work on Firefox 41 when multi-process option is enabled

### ISSUE THREAD

**Issue by delbv9** [cpriest/SnapLinksPlus#73]
I know it's in nightly version. But multi-process feature is really great, it reduces a lot memory usage to almost 80%,
SnapLinks shows the rectangle when selecting but it doesn't do anything after that.

Thanks.

**Comment by cpriest** [comment]
Yes, it's completely unprepared for e10s.  I use e10s in dev edition and 
have stopped using it myself for the time being.  I miss it.

**Comment by drivencompassion** [comment]
Created a new profile with Firefox 42 and SLP can select and count links, but doesn't open them in new tabs, even though that's what it's optioned to do in the preferences.

I also don't see how to disable "multi-process" to test if that works.

**Comment by cpriest** [comment]
I don't believe the multi-process is enabled for release use yet.  Only on the developers edition which is now FF 44.  In my version of FF, tools -> options and it's the 2nd checkbox on the first page: "Enable multi-process ...

**Comment by wsmwk** [comment]
delbv9, a newer version of SLP is available at https://github.com/cpriest/SnapLinksPlus/issues/73 

Does it resolve your problem?

**Comment by wsmwk** [comment]
It is working for me when using SLP 3.0.0.2.  I've closed https://bugzilla.mozilla.org/show_bug.cgi?id=1061277

**Comment by GieltjE** [comment]
Multi process has been enabled for a select group (only those without plugins for now), scaling to other groups will commence lateron: https://wiki.mozilla.org/Electrolysis#Schedule
