### ISSUE TITLE
doesn't work on any of the pirate bay domains

### ISSUE THREAD

**Issue by ericc2728** [cpriest/SnapLinksPlus#76]
https://thepiratebay.se/

**Comment by cpriest** [comment]
Could you expand on this a bit?  I just tried it myself and it works fine for the few links I've tried.  Is there a specific URL you can direct me to and perhaps a screenshot of what you're highlighting that isn't working?

**Comment by ericc2728** [comment]
Hi, When i drag you can see that the box is being made but nothing is getting selected. Then when i let go nothing happens
![image](https://cloud.githubusercontent.com/assets/13821038/11325886/ee77efc8-9127-11e5-993b-3cd9d0a8460f.png)

**Comment by ericc2728** [comment]
not sure why it's only the pirate bay domain as it seems to work on other sites

**Comment by cpriest** [comment]
They are possibly not using <A>nchor tags which is the appropriate 
element to use.  We look for a few others such as <INPUT> and such.

**Comment by cpriest** [comment]
Is this still an issue?

**Comment by ericc2728** [comment]
It works now, as long as the javascript links is checked in the options. Thanks! This is great!

 

Eric
