### ISSUE TITLE
interferes with spell checking

### ISSUE THREAD

**Issue by atomGit** [cpriest/SnapLinksPlus#77]
slightly different than the other spell-check bug

the suggested words in the spell-check context menu are not always cleared - for example...

dooor - context menu might list 'door'
winndow - context menu might list 'door' and 'window'

FF 40.0.2 and earlier
Win 7
SLP 2.4.2.1

**Comment by cpriest** [comment]
I'm not sure how SLP would be interfering with this, the only thing it does with the context menu is prevent it from occurring if a RC drag is large enough...  Seems like a bug with whatever spell checking you might be using...

**Comment by atomGit** [comment]
i use the default FF spell check and i have verified that SLP is causing the issue - also, i am not the only one to report it...

https://addons.mozilla.org/en-US/firefox/addon/snaplinksplus/reviews/722202/

https://github.com/cpriest/SnapLinksPlus/issues/16

https://github.com/cpriest/SnapLinksPlus/issues/71

i no longer use the extension
