### ISSUE TITLE
2.4.3b2 Build statusbar link numbers .. .

### ISSUE THREAD

**Issue by delicacy1** [cpriest/SnapLinksPlus#78]
Can you add this in the next beta build ?

my issue: since that feature is not present in the "customize toolbar" window..
it appears anywhere between other icons which looks horrible. & i'd like to put it before all icons
of the right part of the status bar & not in the middle nor in the far right side.

**Comment by cpriest** [comment]
Thanks for the request.   I'll see about doing that though this extension is due to be extinct sooner or later (when multi-process firefox comes out) as I have not had time to even work on that.  That being said when I do get back to this project I'll try and put this in.  I assume you're using the AddOn Bar restored or something?

**Comment by delicacy1** [comment]
restored ? probably, something like that, since i'm using palemoon & turned
my back on australis & all stupid ui mods by mozilla..
is multi-process a snaplinks replacement ? if so, then introduce a first
beta with the function i proposed, if i won't be keeping snaplinksplus..
(no need to waste ur time updating snaplinksplus if a new generation is
about to be published..

& don't forget the youtube results that still don't open one by one in tabs
but in the same window..

just add the ability to put the links count on the status bar from the
icons window in snaplinksplus
if ur not near a beta version of multi-process

**Comment by delicacy1** [comment]
& don't forget to migrate the javascript frames to tabs open capacity to
the new addon, that's a great implementation when i couldn't open tabs in
myspace on the past
& you implemented it..

**Comment by cpriest** [comment]
Multi-process is Mozilla Electrolysis, it will change the way plugins 
interact with the browser in order to allow the browser to be 
multi-process, the way chrome does it.  Unfortunately it takes some 
plugin modifications to do it.

**Comment by delicacy1** [comment]
if it takes time, just try to add the tweak to the actual beta build of
snaplp please

**Comment by delicacy1** [comment]
still no fix after many years ? it seems that you can't fix the youtube
issue. & isn't your so called "multi-process firefox"already active in the
browser ? & i don't see how this will replace snaplinks..

**Comment by delicacy1** [comment]
Also, the palemoon team stated: 
Unless specifically stated otherwise, what Mozilla does with Firefox will have absolutely no bearing on us.
We are a fork, not a clone. we already have an Add-on SDK available that is compatible with our core. We offer XUL, we offer bootstrapped, we offer Jetpack. "WebExtensions" as far as I understood is just a continuation of Jetpack under a different name?

Pale Moon has NO reason or desire to embrace their new cross-chrome add-ons support. Even in the event we did It would NOT mean the deprecation and removal of what can be considered a superior system that we all ready have and that has evolved for more than a decade.

Hell for all I know.. it might be entirely possible to implement this cross-chrome extension system as a transition layer in Pale Moon in the form of a foundational extension its self.. The nature of the legacy mozilla extension and xul/xpcom extensibility and support is as such that it is completely theoretically possible to implement such a framework in much the same way the Jetpack SDK is done..

In fact.. the Jetpack SDK doesn't even need to really be IN the browser and used to be included in extensions that use it with only a few minimal hooks and accommodations actually required in the browser its self. We simply have it because of our own Firefox Extension legacy requirements.

By pure circumstance it seems Pale Moon will end up being the sole heir of fundamental and core technologies that Mozilla has unwisely decided to abandon. Which of course goes far beyond tech but also ideals like user choice, customization, and all the things that Mozilla has forsaken.

The quote "Pale Moon is not Firefox and never will be again" holds more meaning than ever.. No we are not Firefox because Firefox is something completely different now and Mozilla isn't the non-profit foundation pushing for freedom on the internet anymore.

The motto/slogan/tagline "Your browser, Your Way" also holds more meaning as well. There isn't a browser on the market that I know of that allows the limitless choice, customization, and freedom to do whatever you want to your web browser than Pale Moon. We are not bound to a service or a mega company.. Our goals are NOT motivated by massive amounts of profit or marketshare or greed.. We don't push Pale Moon on users, lock them in, force them to do everything in a specific way. We hope that Pale Moon is useful and if it isn't for you we don't want you to be forced to use the browser. We want you to use what works best for you not what we say is best for you.

Also, we all are volunteers and users as well.. I for one don't get paid.. I work for the project and for the users because I believe in having a sane product I can make my own and can make better..

Since I seem to be moving from topic to topic albeit related ones I will end the "speech" here..

We won't suddenly lose the ability to run existing add-ons. Add-on developers who may have seen little use in supporting us before might be more inclined to develop/update their existing add-ons for us in lieu of completely rewriting it (if even possible) using specialized APIs that may or may not be created by Mozilla in an unknown time frame. In addition, many add-ons don't need a lot of active development because they are very task-specific, and if they work, they work. This whole constant need for updating in Firefox has been caused by Firefox and their rabid release schedule.

I think the future is quite different. People who love using extensions will be more inclined to switch to Pale Moon because it offers an existing framework with many existing extensions, instead of having to throw a lot of them out that aren't going to be available or rewritten for Firefox.next.

Let's make a tally about what (in broad strokes) has recently be deprecated by Firefox:

    UI configurability (Australis)
    Complete themes
    Binary components in extensions (this has landed on release)
    XUL and SDK extensions as a whole (to be replaced with Chrome "extensions")
    XUL as a browser framework language
    NPAPI (plugins)


If all this lands, what will Firefox be, lacking all three types of add-ons?
It will be a browser that cannot be extended, cannot be themed and cannot use plugins. You'd have a browser that can only be used in the way Mozilla intends it, using only components Mozilla deems fit for inclusion (including those you might not want to have). IMHO that isn't Firefox anymore.

Shall we recall why Firefox became a thing, to put it in perspective? It was exactly because it was extensible, configurable, flexible, and could be made to work exactly the way the user (or IT department) wanted it, without compromising on its core function to browse the web.

**Comment by cpriest** [comment]
I'm not sure what your goal is here... Are you suggesting I support a browser I had never heard of until my extension stopped working with it?  Pale Moon is of no interest to me.

**Comment by delicacy1** [comment]
The fact your addon doesn't work on youtube & the report has been made more
than 5 years ago & the fact you ignore all the senseful comments i've added
about palemoon, shows that you either have mental issues since a few years
ago, you decided to abandon your project instead of fixing it when you've
spent years on it which is totally unproductive & immature. you also told
me more than 2 times that you'd look at it & never did year after year. if
trolls like you existed all over the web, the online productivity would be
highly degraded. since browsers are used to improve productivity. & if
people like the authors of palemoon didn't exist, after their statements
you totally ignored by giving me a trollish inconsistent & totally indirect
reply, then many coders for mozilla would have released an obsolete work &
wasted years of contribution for many of them, like you, RETARD.

you know what your addon needs now ? a lil tweaking by someone who should
take back the code.

grow up & go play with yourself trash.

**Comment by cpriest** [comment]
@delicacy1, I hesitate to even dignify your comments with a response, however; you seem like a relatively intelligent fellow, given your seriously sophisticated vocabulary and political prowess.

Given your intelligence level, it seems to me that you could **easily** learn how to program for yourself. You could then take off with the code, fix it, change it, make it fly to the moon if you want even; the sky would literally be the limit.  

Until then, I am, so is my job, my wife, my two kids, my sanity, etc.

**Comment by delicacy1** [comment]
If i had time..

you have a wife ? i don't.
you have a job ? i don't.
Trying to construct a life is more consuming than "enjoying it".. .

but i won't develop my arguments to explain you how.

the problem with you, is that when you've learned a language that takes a
lot of time as a passion, if someone asks you to contribute
by fixing it, you pretend that you're going to look at it & years go by, &
the next time someone asks you to reconsider it because
your project that took you a while to develop & update, the same pretension
is offered until someone insists to see if you can outpass
your pretensions "objectively" & you decide to denigrate him with a
radicalist form of negativism & i dont give a shit attitude.

now telling me, i should learn the language & spend the time you've spent
for a fix, is not simply "gay",
BUT UNPRODUCTIVE, RETARDED, EGOCENTRIC & TOTALLY VAIN.
