### ISSUE TITLE
URL change after copying to clipboard

### ISSUE THREAD

**Issue by iriman** [cpriest/SnapLinksPlus#79]
Ampersand sign in URLs will convert to `&amp;` after copying urls to clipboard. for example `http://www.website.com/default.aspx?tabid=1&stuffid=1` will change to `http://website.com/default.aspx?tabid=1&amp;stuffid=1`.
Thanks for this useful addon!

**Comment by cpriest** [comment]
I'll check into that, probably a simple fix.

**Comment by cpriest** [comment]
Closing this as no further fixes/development is being done to v2.x branch, new v3 is a complete re-write.  Please re-open if issue is still present in v3 when released.
