### ISSUE TITLE
Feature request: add option for opening links at the end of tab list

### ISSUE THREAD

**Issue by jishuoyang** [cpriest/SnapLinksPlus#83]
Would it be possible to add a checkbox for opening links at the end of the tab list, instead of immediately behind the referrer tab?

I have a use case where I'm opening multiple documents from multiple tabs, and it would be fantastic to have all the new document tabs grouped at the end.

Thanks.

**Comment by cpriest** [comment]
It's possible to add this, I'll keep the ticket open as a feature request.

**Comment by gabrielaSal** [comment]
I'd need the opposite. Btw.: SnapLinks and Firefox itself don't do this the same way: When I rightclick a link and use the Firefox command "Open in new Tab", it opens right next to the current tab (which is what I want). When I mark the link by dragging a rectangle (which is SnapLinks) they open at the end of the tab list. Which I find uncomfortable. I'd suggest we need an option for that.

**Comment by cpriest** [comment]
So the latest release coming in the next few days, after some testing will have it open next to the current tab as v2 always did.  @jishuoyang When I add the Options UI to the next release, I will be sure to have this as an option.

**Comment by btanner2** [comment]
+1

**Comment by btanner2** [comment]
Is this issue probably a duplicate of https://github.com/cpriest/SnapLinksPlus/issues/193 ?

**Comment by cpriest** [comment]
This has already been implemented, closing.
