### ISSUE TITLE
Doesn't work with Mozilla Firefox Nightly 46

### ISSUE THREAD

**Issue by M9k** [cpriest/SnapLinksPlus#85]
This plugin, like others (stylish for esample, it is fixed with the last beta update), doesn't work anymore with the last version of firefox.

**Comment by M9k** [comment]
PS: I don't use multiprocessor or advanced settings, I try it on a copy of Nightly 45 and it work fine, under Nightly 46 with the same profile doesn't work.

**Comment by cpriest** [comment]
Hmm, I don't target the nightly builds, nor have I had time to work on 
this project. But.. What errors are showing up in the error console?  
What specifically is it doing or not doing?

**Comment by M9k** [comment]
It just doesn't work, no error, it's like it's disable, just like the stable version of stylish, I can see the icon, I can enter in stylish settings but it doesn't work like it's disable, I don't know if it's a bug of firefox 46 that doesn't run some plugins or they have changed something.
For now the other plugins seem work fine, maybe they have the same problem:
https://github.com/JasonBarnabe/stylish/pull/265

**Comment by cpriest** [comment]
No errors in the error log (Ctrl + J)

**Comment by danald** [comment]
Firefox 46 removed the [old array comprehension syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Array_comprehensions#Differences_to_the_older_JS1.7JS1.8_comprehensions)  that is used in [Selection.js](https://github.com/cpriest/SnapLinksPlus/blob/master/src/content/Selection.js#L818-L819).
