### ISSUE TITLE
Not working in Firefox 46.0 on Windows

### ISSUE THREAD

**Issue by Duchamp** [cpriest/SnapLinksPlus#88]
When attempting to select links nothing happens. 

In the console the following shows up:

`ReferenceError: SLPrefs is not defined snaplinks.js:164:1
ReferenceError: SLPrefs is not defined snaplinks.js:205:1
`

Please check, thank you.

**Comment by jedikalimero** [comment]
also tried with snaplinksplus-2.4.3b3.xpi, but still not working.

**Comment by sfragata** [comment]
The extension doesn't work on Ubuntu 14.04 too

**Comment by cpriest** [comment]
There is a 2.4.3 already on AMO, for some reason it is stuck on 
preliminarily approved though they already approved it (by email).  I 
emailed them about it.

Status: Close
