### ISSUE TITLE
Not working in FF46

### ISSUE THREAD

**Issue by Salubritas** [cpriest/SnapLinksPlus#89]
Not working for me at all in FF46. Also mentioned in a few recent reviews.

**Comment by Thefirsh** [comment]
How come it works with an older version of SLP? https://addons.mozilla.org/en-US/firefox/addon/snaplinksplus/reviews/793725/

**Comment by cpriest** [comment]
AMO had an issue when they went to approve the newest build, been up there a couple of weeks.  It's live/published now, v2.4.3
