### ISSUE TITLE
Not working with Pale Moon 26.2.1

### ISSUE THREAD

**Issue by mojo-chan** [cpriest/SnapLinksPlus#92]
Since updating to Pale Moon 26.2.1 I have found that Snap Links Plus doesn't work any more. The selection rectangle appears but does not pick up or open any links.

**Comment by cpriest** [comment]
I'm sorry but pale moon isn't a supported browser.  I would accept non-breaking pull requests for fixes, but beyond that there isn't anything I personally can do.
