### ISSUE TITLE
squared line takes time to appear..

### ISSUE THREAD

**Issue by delicacy1** [cpriest/SnapLinksPlus#93]
Even if snaplinksplus needs to analyze the content in javascript or not etc before snapping links,
it would be better if the lines would appear in real time, otherwise, ppl need to wait with the button pressed till they appear, so i get bored & leave the mouse & the links get snapped without seeing the square in the end.. those lines should appear in realtime whatever time snaplinksplus needs to analyze the links before opening them .. .

**Comment by cpriest** [comment]
2.x is no longer in development, 3.x is being developed as time permits.  However, you could try snap links plus in a fresh profile, your firefox profile is likely bogged down as SnapLinks is by no means slow.  Is this happening on a specific page/url you can share?

**Comment by delicacy1** [comment]
Application Basics
------------------

Name: Pale Moon
Version: 26.2.2
User Agent: Mozilla/5.0 (Windows NT 6.2; rv:38.9) Gecko/20100101 Goanna/2.0
Firefox/38.9 PaleMoon/26.2.2

Extensions
----------

Name: Adblock Latitude
Version: 3.5.0b1
Enabled: true
ID: adblocklatitude@addons.palemoon.org

Name: Adblock Plus Pop-up Addon
Version: 0.9.2.1-signed.1-signed
Enabled: true
ID: adblockpopups@jessehakanen.net

Name: Autofill
Version: 3.7
Enabled: true
ID: firefox-autofill-fixed-by-scriptkitz@gmail.com

Name: Bgsound Player
Version: 1.0.1-signed.1-signed
Enabled: true
ID: jid0-m8sEicXAApwGawpz1bNw3ZSfTAE@jetpack

Name: Bookmark Favicon Changer
Version: 2.29
Enabled: true
ID: bookmarkfaviconchanger@sonthakit

Name: bug892485_PreventScrollOnHistory
Version: 1.1.1-signed.1-signed
Enabled: true
ID: bug892485@alice

Name: checkCompatibility
Version: 1.3.1-signed.1-signed
Enabled: true
ID: check-compatibility@dactyl.googlecode.com

Name: Clean Links
Version: 2.7.1-signed.1-signed
Enabled: true
ID: {158d7cb3-7039-4a75-8e0b-3bd0a464edd2}

Name: Close Repeated Tabs
Version: 1.0.1-signed.1-signed
Enabled: true
ID: {3d2d0570-d7f1-45c0-932e-9bf4eb28fb1c}

Name: ColorfulTabs
Version: 30.0.3
Enabled: true
ID: {0545b830-f0aa-4d7e-8820-50a4629a56fe}

Name: Cookie Controller
Version: 5.4
Enabled: true
ID: {ac2cfa60-bc96-11e0-962b-0800200c9a66}

Name: deskCut
Version: 0.6.0.3.1-signed.1-signed
Enabled: true
ID: {9125C9CB-BE2B-4389-A0C7-46A4BDD46AEA}

Name: Disconnect
Version: 3.15.3.1-signed.1-signed
Enabled: true
ID: 2.0@disconnect.me

Name: Downloads Window
Version: 0.4.5
Enabled: true
ID: {a7213cf2-fa1e-4373-88ff-255d0abd3020}

Name: DownThemAll!
Version: 3.0b5
Enabled: true
ID: {DDC359D1-844A-42a7-9AA1-88A850A938A8}

Name: Ease Link
Version: 2.0.135
Enabled: true
ID: easelink@ashi.cn

Name: Easy DragToGo+
Version: 1.1.7.b17
Enabled: true
ID: {21cfaec0-dbb3-11dc-95ff-0800200c9a66}

Name: eCleaner
Version: 1.4.1-signed.1-let-fixed.1-signed
Enabled: true
ID: {c72c0c73-4eb0-4fb3-af0f-074e97326cfd}

Name: Element Hiding Helper for Adblock Plus
Version: 1.3.2.495-beta
Enabled: true
ID: elemhidehelper@adblockplus.org

Name: FlashStopper
Version: 1.4.2
Enabled: true
ID: flashstopper@byo.co.il

Name: Focus Regainer
Version: 0.11.0
Enabled: true
ID: focus@regainer.wproxym

Name: Greasemonkey
Version: 2.0.1-signed
Enabled: true
ID: {e4a8a97b-f2ed-450b-b12d-ee082ba24781}

Name: Image Zoom
Version: 0.6.3.1-signed.1-signed
Enabled: true
ID: {1A2D0EC4-75F5-4c91-89C4-3656F6E44B68}

Name: Link Password
Version: 4.0.1.0.1-signed.1-signed
Enabled: true
ID: LinkPassword@EvighetensFilosofi

Name: Link Status Redux
Version: 2.6
Enabled: true
ID: linkstatus@jha.iki.fi

Name: Location Bar Enhancer..
Version: 5.2.1-signed.1-let-fixed
Enabled: true
ID: UI.Enhancer@girishsharma

Name: Menu Wizard
Version: 5.01
Enabled: true
ID: s3menu@wizard

Name: Middle Click Tabbar
Version: 14.12.05.1-signed
Enabled: true
ID: middle-click-tabbar@senicar.net

Name: MIME Edit
Version: 0.600901070000
Enabled: true
ID: {fb4eaeed-d1c9-45d1-a2bb-f2876142daf0}

Name: MozArchiver
Version: 1.0.0
Enabled: true
ID: mozarchiver@lootyhoof-pm

Name: NoUn Buttons
Version: 1.1.4.1.1-signed.1-signed
Enabled: true
ID: {99f30549-35d4-11d9-8a2a-396c6e707e82}

Name: Open link in...
Version: 1.9.1-signed.1-signed
Enabled: true
ID: {ff81e780-5cc0-11d9-9669-0800200c9a66}

Name: OpenDownload²
Version: 4.1.1
Enabled: true
ID: {210249CE-F888-11DD-B868-4CB456D89593}

Name: Organize Status Bar (Revived)
Version: 0.1.0.1-signed.1-signed
Enabled: true
ID: obsrev@alexancarlproject.net

Name: Personas Plus
Version: 99.99
Enabled: true
ID: personas@christopher.beard

Name: Precise Clear History
Version: 1.3.1-signed.1-signed
Enabled: true
ID: preciseclearhistory@vano

Name: Remove Cookie for Google Account Chooser
Version: 1.0.1-signed.1-signed
Enabled: true
ID: jid1-Rm4h1P3jB1IL4w@jetpack

Name: Restartless Restart
Version: 9.1-signed.1-signed
Enabled: true
ID: restartless.restart@erikvold.com

Name: S3.Google Translator
Version: 5.23
Enabled: true
ID: s3google@translator

Name: Save Page As
Version: 0.3
Enabled: true
ID: {93a7f837-de67-11da-8770-0050c2490048}

Name: SearchWith
Version: 0.4.4.1-signed.1-signed
Enabled: true
ID: {79898015-E980-457c-BDE0-D2ECCAF4B654}

Name: Session Manager
Version: 0.8.1.7
Enabled: true
ID: {1280606b-2510-4fe0-97ef-9b5a22eafe30}

Name: Show Picture
Version: 3.0.1-signed
Enabled: true
ID: LDshowpicture_plashcor@gmail.com

Name: Skip Cert Error
Version: 0.4.4.1-signed.1-let-fixed.1-signed
Enabled: true
ID: skipcerterror@foudil.fr

Name: Snap Links Plus
Version: 2.4.3
Enabled: true
ID: snaplinks@snaplinks.mozdev.org

Name: Stylish
Version: 2.0.6
Enabled: true
ID: {46551EC9-40F0-4e47-8E18-8E5CF550CFB8}

Name: Tab Counter
Version: 1.9.9.3
Enabled: true
ID: tabcounter@morac

Name: Thumbnail Zoom Plus
Version: 3.7
Enabled: true
ID: thumbnailZoom@dadler.github.com

Name: UnPlug
Version: 2.059
Enabled: true
ID: unplug@compunach

Name: URL Link
Version: 2.04.3.1-signed.1-signed
Enabled: true
ID: {139a120b-c2ea-41d2-bf70-542d9f063dfd}

Name: YouTube Auto Replay
Version: 3.3.1-signed.1-signed
Enabled: true
ID: YouTubeAutoReplay@arikv.com

Important Modified Preferences
------------------------------

accessibility.typeaheadfind: true
accessibility.typeaheadfind.flashBar: 0
accessibility.typeaheadfind.prefillwithselection: false
accessibility.typeaheadfind.timeout: 999000
browser.cache.disk.smart_size.first_run: false
browser.cache.disk.smart_size.use_old_max: false
browser.cache.disk.smart_size_cached_value: 307200
browser.display.show_image_placeholders: false
browser.link.open_newwindow: 1
browser.link.open_newwindow.override.external: 2
browser.newtab.url: about:blank
browser.places.smartBookmarksVersion: -1
browser.search.update: false
browser.search.useDBForOrder: false
browser.sessionstore.enabled: true
browser.sessionstore.max_tabs_undo: 70
browser.sessionstore.max_windows_undo: 30
browser.sessionstore.restore_on_demand: false
browser.sessionstore.upgradeBackup.latestBuildID: 20140605174243
browser.startup.homepage: about:blank
browser.startup.homepage_override.buildID: 20160507222152
browser.startup.homepage_override.mstone: 2.0.2
browser.tabs.animate: false
browser.tabs.autoHide: true
browser.tabs.drawInTitlebar: false
browser.tabs.loadDivertedInBackground: true
browser.tabs.loadInBackground: false
browser.tabs.opentabfor.middleclick: false
browser.tabs.tabMinWidth: 100
browser.tabs.warnOnClose: false
browser.tabs.warnOnOpen: false
browser.urlbar.rss: false
dom.disable_beforeunload: true
dom.disable_window_move_resize: true
dom.disable_window_open_feature.directories: true
dom.disable_window_open_feature.menubar: true
dom.disable_window_open_feature.minimizable: true
dom.disable_window_open_feature.scrollbars: true
dom.disable_window_open_feature.toolbar: true
dom.ipc.plugins.enabled.npietab2.dll: true
dom.max_chrome_script_run_time: 0
dom.max_script_run_time: 0
dom.mozApps.runUpdate: false
dom.mozApps.used: true
dom.push.enabled: false
dom.report_all_js_exceptions: true
dom.successive_dialog_time_limit: 0
dom.w3c_touch_events.expose: false
dom.webnotifications.enabled: false
extensions.checkCompatibility.25.1: false
extensions.checkCompatibility.25.2: false
extensions.checkCompatibility.25.3: false
extensions.checkCompatibility.25.4: false
extensions.checkCompatibility.25.5: false
extensions.checkCompatibility.25.6: false
extensions.checkCompatibility.25.7: false
extensions.checkCompatibility.25.8: false
extensions.checkCompatibility.26.0: false
extensions.checkCompatibility.26.1: false
extensions.checkCompatibility.26.2: false
extensions.checkCompatibility.nightly: false
extensions.lastAppVersion: 26.2.2
font.internaluseonly.changed: true
general.autoScroll: false
gfx.blacklist.suggested-driver-version: 10.6
gfx.direct2d.disabled: true
gfx.direct3d.checkDX10: false
gfx.direct3d.last_used_feature_level_idx: 1
javascript.options.showInConsole: false
keyword.URL:
http://www.google.com/search?complete=0&pws=0&Gf=0&safe=off&hl=en&q=
layers.acceleration.disabled: true
media.gstreamer.enabled: true
network.cookie.prefsMigrated: true
network.http.max-persistent-connections-per-server: 70
places.database.lastMaintenance: 1463017671
places.history.expiration.transient_current_max_pages: 79483
places.history.expiration.transient_optimal_database_size: 42910022
plugin.disable_full_page_plugin_for_types:
plugin.importedState: true
plugin.state.flash: 2
plugin.state.java: 2
plugin.state.npctrl: 2
plugin.state.npdeployjava: 2
plugin.state.npdivx: 0
plugin.state.np-mswmp: 0
plugin.state.npovshelper: 0
plugin.state.npqtplugin: 2
plugin.state.npunity3d: 0
plugin.state.npvlc: 2
plugins.click_to_play: false
plugins.hide_infobar_for_outdated_plugin: true
plugins.load_appdir_plugins: true
plugins.notifyMissingFlash: false
print.printer_Microsoft_XPS_Document_Writer.print_bgcolor: false
print.printer_Microsoft_XPS_Document_Writer.print_bgimages: false
print.printer_Microsoft_XPS_Document_Writer.print_colorspace:
print.printer_Microsoft_XPS_Document_Writer.print_command:
print.printer_Microsoft_XPS_Document_Writer.print_downloadfonts: false
print.printer_Microsoft_XPS_Document_Writer.print_duplex: -2147483599
print.printer_Microsoft_XPS_Document_Writer.print_edge_bottom: 0
print.printer_Microsoft_XPS_Document_Writer.print_edge_left: 0
print.printer_Microsoft_XPS_Document_Writer.print_edge_right: 0
print.printer_Microsoft_XPS_Document_Writer.print_edge_top: 0
print.printer_Microsoft_XPS_Document_Writer.print_evenpages: true
print.printer_Microsoft_XPS_Document_Writer.print_footercenter:
print.printer_Microsoft_XPS_Document_Writer.print_footerleft: &PT
print.printer_Microsoft_XPS_Document_Writer.print_footerright: &D
print.printer_Microsoft_XPS_Document_Writer.print_headercenter:
print.printer_Microsoft_XPS_Document_Writer.print_headerleft: &T
print.printer_Microsoft_XPS_Document_Writer.print_headerright: &U
print.printer_Microsoft_XPS_Document_Writer.print_in_color: true
print.printer_Microsoft_XPS_Document_Writer.print_margin_bottom: 0.5
print.printer_Microsoft_XPS_Document_Writer.print_margin_left: 0.5
print.printer_Microsoft_XPS_Document_Writer.print_margin_right: 0.5
print.printer_Microsoft_XPS_Document_Writer.print_margin_top: 0.5
print.printer_Microsoft_XPS_Document_Writer.print_oddpages: true
print.printer_Microsoft_XPS_Document_Writer.print_orientation: 0
print.printer_Microsoft_XPS_Document_Writer.print_page_delay: 50
print.printer_Microsoft_XPS_Document_Writer.print_paper_data: 0
print.printer_Microsoft_XPS_Document_Writer.print_paper_height: 11.00
print.printer_Microsoft_XPS_Document_Writer.print_paper_name:
print.printer_Microsoft_XPS_Document_Writer.print_paper_size_type: 1
print.printer_Microsoft_XPS_Document_Writer.print_paper_size_unit: 0
print.printer_Microsoft_XPS_Document_Writer.print_paper_width: 8.50
print.printer_Microsoft_XPS_Document_Writer.print_plex_name:
print.printer_Microsoft_XPS_Document_Writer.print_resolution: 518
print.printer_Microsoft_XPS_Document_Writer.print_resolution_name:
print.printer_Microsoft_XPS_Document_Writer.print_reversed: false
print.printer_Microsoft_XPS_Document_Writer.print_scaling: 1.00
print.printer_Microsoft_XPS_Document_Writer.print_shrink_to_fit: true
print.printer_Microsoft_XPS_Document_Writer.print_to_file: false
print.printer_Microsoft_XPS_Document_Writer.print_unwriteable_margin_bottom:
0
print.printer_Microsoft_XPS_Document_Writer.print_unwriteable_margin_left: 0
print.printer_Microsoft_XPS_Document_Writer.print_unwriteable_margin_right:
0
print.printer_Microsoft_XPS_Document_Writer.print_unwriteable_margin_top: 0
privacy.cpd.cookies: false
privacy.cpd.extensions-sessionmanager: false
privacy.cpd.formdata: false
privacy.cpd.historysession: true
privacy.cpd.offlineApps: true
privacy.cpd.sessions: false
privacy.donottrackheader.value: 0
privacy.item.extensions-privacyplus: true
privacy.popups.showBrowserMessage: false
privacy.sanitize.migrateFx3Prefs: true
privacy.sanitize.timeSpan: 0
security.default_personal_cert: Select Automatically
security.dialog_enable_delay: 200
security.disable_button.openDeviceManager: false
security.OCSP.enabled: 0
security.ssl.allow_unsafe_ocsp_response: true
security.ssl3.rsa_rc4_128_md5: true
security.ssl3.rsa_rc4_128_sha: true
security.warn_entering_weak: false
security.warn_entering_weak.show_once: false
security.warn_submit_insecure: false
security.warn_viewing_mixed: false
security.xssfilter.whitelist: yimg.com,paypalobjects.com
storage.vacuum.last.dta_queue.sqlite: 1460626010
storage.vacuum.last.index: 2
storage.vacuum.last.places.sqlite: 1462659211

Graphics
--------

Adapter Description: Mobile Intel(R) 4 Series Express Chipset Family
(Microsoft Corporation - WDDM 1.1)
Adapter Drivers: igdumd32 igd10umd32
Adapter RAM: Unknown
Device ID: 0x2a42
DirectWrite Enabled: false (6.2.9200.16581)
Driver Date: 3-24-2012
Driver Version: 8.15.10.2702
GPU #2 Active: false
GPU Accelerated Windows: 0/7 Basic
Vendor ID: 0x8086
WebGL Renderer: Google Inc. -- ANGLE (Mobile Intel(R) 4 Series Express
Chipset Family (Microsoft Corporation - WDDM 1.1) Direct3D9Ex vs_3_0 ps_3_0)
windowLayerManagerRemote: false
AzureCanvasBackend: skia
AzureContentBackend: cairo
AzureFallbackCanvasBackend: cairo

JavaScript
----------

Incremental GC: true

Accessibility
-------------

Activated: false
Prevent Accessibility: 1

Library Versions
----------------

NSPR
Expected minimum version: 4.10.10
Version in use: 4.10.10

NSS
Expected minimum version: 3.19.4.2 Basic ECC
Version in use: 3.19.4.2 Basic ECC

NSSSMIME
Expected minimum version: 3.19.4.2 Basic ECC
Version in use: 3.19.4.2 Basic ECC

NSSSSL
Expected minimum version: 3.19.4.2 Basic ECC
Version in use: 3.19.4.2 Basic ECC

NSSUTIL
Expected minimum version: 3.19.4.2
Version in use: 3.19.4.2

**Comment by delicacy1** [comment]
java se 8 U92 11.92.2.14
flash 22.0.0.144
silverylight 5.1.40728.0
vlc plugin 2.2.2.0

**Comment by delicacy1** [comment]
Now, it appears when i middle click as a very mini square & when i've encircled the links, it appears around the links 3 seconds after. i couldn't even see the mini square when middle clicking, probably due to a recent update, i donno.
