### ISSUE TITLE
Conflict with spell-checkers

### ISSUE THREAD

**Issue by Irvinehimself** [cpriest/SnapLinksPlus#94]
Great add-on, and exceptionally useful... Unfortunately there is a conflict with spell checkers. 

I am running Ubuntu Studio, (Xenial Xerus,) and the basic symptoms are as follows:

   1)  Although the spell-checkers highlight misspellings and offer a selection of correct spellings, when clicked, the selection does not replace the misspelled word.
    2) The offered correct spellings are not cleared after moving out of the text area or to a new page. Meaning that every time I try to use a spell-checker, I add a list of words to the right click menu. Depending on my session history, this list can become very large! 

Note1: I have tried the obvious like changing dictionaries and disabling language packs to no-avail

Note2: I disabled all add-ons before laboriously re-enabling them one at a time. It is definitely Snap-Link Plus that is the source of the problem.

Thanks for a great add-on,

Irvine

**Comment by cpriest** [comment]
Thanks, this has been reported before.  v2 is no longer under development, but v3 is on its way.  Let's see if the new version has this same problem.
