### ISSUE TITLE
Open selected links in new Group

### ISSUE THREAD

**Issue by Peuj** [cpriest/SnapLinksPlus#95]
Hi,

Is it possible to add an option to open the selected links in a new Group?

Thanks

**Comment by cpriest** [comment]
The 2.x branch is no longer actively developed as the 3.0 re-write is under way.  I'm not sure that the "group" feature is going to be sticking around, I thought I had read that they were going to pull it at some point.

**Comment by Keith94** [comment]
There's a replacement extension available: https://addons.mozilla.org/en-US/firefox/addon/tab-groups-panorama/

**Comment by cpriest** [comment]
Thanks, I hadn't realized someone picked up the torch.  Any idea if this 
addon is Electrolysis compatible?

**Comment by Keith94** [comment]
Yup it's e10s compatible, I installed the beta version and it works fine.
