### ISSUE TITLE
Context menu no longer works after right-click dragging

### ISSUE THREAD

**Issue by DoomTay** [cpriest/SnapLinksPlus#97]
This is with Snap Links v3

Nightly
Version 	50.0a1
Build ID 	20160702030219

After selecting links with this addon, right-clicking does not open the context menu at all until the tab is reloaded.

**Comment by cpriest** [comment]
Thanks, I've confirmed this is an issue, I'll address it before the next release.

**Comment by cpriest** [comment]
I'm assuming you're speaking of the other ticket you posted.  It's a *nix issue I'll address there.
