### ISSUE TITLE
Corrupt archive v3.0.0.2

### ISSUE THREAD

**Issue by delicacy1** [cpriest/SnapLinksPlus#98]
Needs to be reuploaded, you uploaded a 28kb file.. or haven't uploaded it totally.

https://addons.mozilla.org/firefox/downloads/file/457593/snap_links_plus-3.0.0.2.xpi

**Comment by cpriest** [comment]
Works fine for me in Firefox 45+

**Comment by delicacy1** [comment]
lol, how can i explain thise in another language than english ))
the updated version you uploaded to the mozilla addon site is not fully
uploaded......
it's not a question of compatibility, you haven't read me properly.
you uploaded like 28 to 32kb
